Importing necessary libraries and fixing random seed

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8')
sns.set_context('talk')
RANDOM_SEED = 42

Importing TRAIN data

In [3]:
data_path = 'ecommerce_price_prediction-train.csv'
df = pd.read_csv(data_path, parse_dates=['capturedAt'], low_memory=False)
print(f'Read {len(df):,} rows and {df.shape[1]} columns from {data_path}')
df.tail()

Read 306,226 rows and 26 columns from ecommerce_price_prediction-train.csv

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
306221,2025-03-22 04:27:05.302,1009757562,26058443824,246415388990,16500000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306222,2025-03-22 04:27:05.302,1009757562,26058443824,207734010381,15900000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306223,2025-03-22 04:27:05.302,1009757562,26058443824,207734010380,29100000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306224,2025-03-22 04:27:05.302,1009757562,26058443824,207734010380,29100000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306225,2025-03-22 04:27:05.302,1009757562,26058443824,246415388993,28400000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f

Adding TRAIN tag to the train dataset so that it wont get mixed later

In [4]:
df['tag1']='TRAIN'

In [5]:
df.shape

(306226, 27)

In [6]:
df.duplicated().sum()

2244

In [7]:
duplicate_rows = df[
    df.duplicated(keep=False)
]

duplicate_rows.head(5)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller,tag1
3722,2025-01-06 08:00:19.394,1000050896,19691496580,186929387166,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,50.0,1,f,f,f,TRAIN
3723,2025-01-06 08:00:19.394,1000050896,19691496580,186929387166,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,50.0,1,f,f,f,TRAIN
10658,2025-02-02 01:05:09.437,1000050896,21791490000,148309242735,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,57.0,1,f,f,f,TRAIN
10659,2025-02-02 01:05:09.437,1000050896,21791490000,148309242735,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,57.0,1,f,f,f,TRAIN
10681,2025-02-02 01:05:10.221,1000050896,19691496580,186929387166,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,57.0,1,f,f,f,TRAIN

In [8]:
df = df.drop_duplicates()

In [9]:
df.shape

(303982, 27)

Importing TEST data

In [10]:
test_data_path = 'ecommerce_price_prediction-test-3-days.csv'
test__real_df = pd.read_csv(test_data_path, parse_dates=['capturedAt'], low_memory=False)
print(f'Read {len(test__real_df):,} rows and {test__real_df.shape[1]} columns from {test_data_path}')
test__real_df.head()

Read 25,900 rows and 26 columns from ecommerce_price_prediction-test-3-days.csv

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
0,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-03-22 04:27:05.325,1009757562,27904817781,241162534604,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Adding TEST tag so that it wont get mixed with train data

In [11]:
test__real_df['tag1']='TEST'
test__real_df.shape

(25900, 27)

Checking TRAIN data info

In [12]:
print('Shape:', df.shape)
print('\nColumns:')
print(df.columns.tolist())

df.info()

Shape: (303982, 27)

Columns:
['capturedAt', 'shopId', 'itemId', 'modelId', 'price', 'priceBeforeDiscount', 'promotionId', 'cat_id', 'stock', 'normal_stock', 'raw_discount', 'show_discount', 'brand', 'is_free_shipping', 'is_pre_order', 'item_price_min', 'item_price_max', 'review_rating', 'total_rating_count', 'cmt_count', 'shop_rating', 'shop_response_rate', 'shop_follower_count', 'is_official_shop', 'is_verified', 'is_preferred_plus_seller', 'tag1']
<class 'pandas.core.frame.DataFrame'>
Index: 303982 entries, 0 to 306223
Data columns (total 27 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   capturedAt                303982 non-null  datetime64[ns]
 1   shopId                    303982 non-null  int64
 2   itemId                    303982 non-null  int64
 3   modelId                   303982 non-null  int64
 4   price                     303982 non-null  int64
 5   priceBeforeDiscount       303982 non-null  int64
 6   promotionId               303982 non-null  int64
 7   cat_id                    303982 non-null  int64
 8   stock                     3728 non-null    float64
 9   normal_stock              3728 non-null    float64
 10  raw_discount              303982 non-null  int64
 11  show_discount             303982 non-null  int64
 12  brand                     199832 non-null  object
 13  is_free_shipping          303982 non-null  object
 14  is_pre_order              303982 non-null  object
 15  item_price_min            303982 non-null  int64
 16  item_price_max            303982 non-null  int64
 17  review_rating             303982 non-null  float64
 18  total_rating_count        303982 non-null  int64
 19  cmt_count                 303982 non-null  int64
 20  shop_rating               303982 non-null  float64
 21  shop_response_rate        302783 non-null  float64
 22  shop_follower_count       303982 non-null  int64
 23  is_official_shop          303982 non-null  object
 24  is_verified               303982 non-null  object
 25  is_preferred_plus_seller  303982 non-null  object
 26  tag1                      303982 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(14), object(7)
memory usage: 64.9+ MB

Checking TRAIN data missing numbers

In [13]:
missing_report = df.isna().sum().to_frame('missing_count')
missing_report['missing_pct'] = 100 * missing_report['missing_count'] / len(df)
missing_report.sort_values(by='missing_pct', ascending=False).head(20)

                          missing_count  missing_pct
stock                            300254    98.773612
normal_stock                     300254    98.773612
brand                            104150    34.261897
shop_response_rate                 1199     0.394431
capturedAt                            0     0.000000
item_price_min                        0     0.000000
is_preferred_plus_seller              0     0.000000
is_verified                           0     0.000000
is_official_shop                      0     0.000000
shop_follower_count                   0     0.000000
shop_rating                           0     0.000000
cmt_count                             0     0.000000
total_rating_count                    0     0.000000
review_rating                         0     0.000000
item_price_max                        0     0.000000
is_free_shipping                      0     0.000000
is_pre_order                          0     0.000000
shopId                                0     0.000000
show_discount                         0     0.000000
raw_discount                          0     0.000000

Checking TEST data info

In [14]:
print('Shape:', test__real_df.shape)
print('\nColumns:')
print(test__real_df.columns.tolist())

test__real_df.info()

Shape: (25900, 27)

Columns:
['capturedAt', 'shopId', 'itemId', 'modelId', 'price', 'priceBeforeDiscount', 'promotionId', 'cat_id', 'stock', 'normal_stock', 'raw_discount', 'show_discount', 'brand', 'is_free_shipping', 'is_pre_order', 'item_price_min', 'item_price_max', 'review_rating', 'total_rating_count', 'cmt_count', 'shop_rating', 'shop_response_rate', 'shop_follower_count', 'is_official_shop', 'is_verified', 'is_preferred_plus_seller', 'tag1']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25900 entries, 0 to 25899
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   capturedAt                25900 non-null  datetime64[ns]
 1   shopId                    25900 non-null  int64
 2   itemId                    25900 non-null  int64
 3   modelId                   25900 non-null  int64
 4   price                     300 non-null    float64
 5   priceBeforeDiscount       300 non-null    float64
 6   promotionId               300 non-null    float64
 7   cat_id                    300 non-null    float64
 8   stock                     7 non-null      float64
 9   normal_stock              7 non-null      float64
 10  raw_discount              300 non-null    float64
 11  show_discount             300 non-null    float64
 12  brand                     166 non-null    object
 13  is_free_shipping          300 non-null    object
 14  is_pre_order              300 non-null    object
 15  item_price_min            300 non-null    float64
 16  item_price_max            300 non-null    float64
 17  review_rating             300 non-null    float64
 18  total_rating_count        300 non-null    float64
 19  cmt_count                 300 non-null    float64
 20  shop_rating               300 non-null    float64
 21  shop_response_rate        300 non-null    float64
 22  shop_follower_count       300 non-null    float64
 23  is_official_shop          300 non-null    object
 24  is_verified               300 non-null    object
 25  is_preferred_plus_seller  300 non-null    object
 26  tag1                      25900 non-null  object
dtypes: datetime64[ns](1), float64(16), int64(3), object(7)
memory usage: 5.3+ MB

Adding ANCHOR tag

In [15]:
test__real_df['tag2'] = np.where(
    test__real_df['price'].notna(),
    'ANCHOR',
    'NOT-ANCHOR'
)

Adding date column to both TRAIN and TEST

In [16]:
df['date'] = df['capturedAt'].dt.date
test__real_df['date'] = test__real_df['capturedAt'].dt.date

Isolating validation set from train

In [17]:
last_date = df['date'].max()
print(f"Last date in dataset: {last_date}")

# Isolate all data from the last date as validation set
validation_df = df[df['date'] == last_date].copy()
train_df = df[df['date'] < last_date].copy()

print(f"Training set: {len(train_df):,} rows")
print(f"Validation set: {len(validation_df):,} rows")
print(f"Validation set date: {validation_df['date'].unique()}")

# Verify no overlap
assert len(set(train_df['date']) & set(validation_df['date'])) == 0, "Training and validation sets have overlapping dates"
print("✓ No date overlap between training and validation sets")

Last date in dataset: 2025-03-22
Training set: 301,079 rows
Validation set: 2,903 rows
Validation set date: [datetime.date(2025, 3, 22)]
✓ No date overlap between training and validation sets

Adding second tags to really distinguish the final train and validation set

In [18]:
train_df['tag2']= 'TRAIN'
validation_df['tag2']= 'VALIDATION'

In [19]:
train_df.shape

(301079, 29)

In [20]:
validation_df.shape

(2903, 29)

In [21]:
test__real_df.shape

(25900, 29)

Adding date columns

In [22]:
def build_standard_time_features(df):
    df = df.copy()
    df['day_of_week'] = df['capturedAt'].dt.dayofweek
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    df['month'] = df['capturedAt'].dt.month
    df['day_of_year'] = df['capturedAt'].dt.dayofyear
    hour = df['capturedAt'].dt.hour
    df['is_morning'] = ((hour >= 6) & (hour < 12)).astype(int)
    df['is_afternoon'] = ((hour >= 12) & (hour < 18)).astype(int)
    df['is_evening'] = ((hour >= 18) & (hour < 24)).astype(int)
    return df

In [23]:
train_df = build_standard_time_features(train_df)
validation_df = build_standard_time_features(validation_df)
test__real_df = build_standard_time_features(test__real_df)

In [24]:
train_df.shape

(301079, 36)

In [25]:
test__real_df.shape

(25900, 36)

In [26]:
validation_df.shape

(2903, 36)

Adding tags for missing stock and brand

In [27]:
train_df['stock_available'] = train_df['stock'].notna().astype(int)

train_df['brand_missing'] = train_df['brand'].isna().astype(int)

In [28]:
train_df.shape

(301079, 38)

Frequency encoding for brand

In [29]:
train_df['brand'] = train_df['brand'].fillna('unknown')
brand_counts = train_df['brand'].value_counts()

train_df['brand_freq'] = train_df['brand'].map(brand_counts)

In [30]:
train_df.shape

(301079, 39)

Check for missing values in shop_response_rate

In [31]:
# =========================================================
# CHECK WHETHER MISSING shop_response_rate
# IS CONCENTRATED IN SPECIFIC SHOPS
# =========================================================

response_df = train_df.copy()

# missing flag
response_df['shop_response_rate_missing'] = (
    response_df['shop_response_rate'].isna()
)

# =========================================================
# COUNT MISSING PER SHOP
# =========================================================

missing_by_shop = (
    response_df.groupby('shopId')['shop_response_rate_missing']
    .agg(['sum', 'count', 'mean','median'])
    .rename(columns={
        'sum': 'missing_count',
        'count': 'total_rows',
        'mean': 'mean_non_missing',
        'median': 'median_non_missing'  
    })
)

# missing percentage per shop
missing_by_shop['missing_pct'] = (
    missing_by_shop['missing_count']
    / missing_by_shop['total_rows']
)


# =========================================================
# SORT BY HIGHEST MISSING COUNT
# =========================================================

missing_by_shop_sorted = (
    missing_by_shop
    .sort_values(
        by='missing_count',
        ascending=False
    )
)

print(missing_by_shop_sorted.head(20))

            missing_count  total_rows  mean_non_missing  median_non_missing  \
shopId
1007291976           1120        2676          0.418535                 0.0
10044886               40         432          0.092593                 0.0
10046782               16         180          0.088889                 0.0
10016846               12          43          0.279070                 0.0
100251397              10         168          0.059524                 0.0
1005306332              1          64          0.015625                 0.0
1002675141              0         710          0.000000                 0.0
1002883376              0          61          0.000000                 0.0
1002919413              0        2818          0.000000                 0.0
1002936943              0         240          0.000000                 0.0
1002964923              0          41          0.000000                 0.0
1003032082              0          69          0.000000                 0.0
1003061908              0          80          0.000000                 0.0
1003095770              0         596          0.000000                 0.0
1003145950              0        1730          0.000000                 0.0
1003181772              0          20          0.000000                 0.0
1003240246              0          38          0.000000                 0.0
1003473490              0        3540          0.000000                 0.0
1003530925              0         258          0.000000                 0.0
1003613948              0         670          0.000000                 0.0

            missing_pct
shopId
1007291976     0.418535
10044886       0.092593
10046782       0.088889
10016846       0.279070
100251397      0.059524
1005306332     0.015625
1002675141     0.000000
1002883376     0.000000
1002919413     0.000000
1002936943     0.000000
1002964923     0.000000
1003032082     0.000000
1003061908     0.000000
1003095770     0.000000
1003145950     0.000000
1003181772     0.000000
1003240246     0.000000
1003473490     0.000000
1003530925     0.000000
1003613948     0.000000

In [32]:
train_df['shop_response_rate'].describe()

count    299880.000000
mean         78.166910
std          16.472561
min           9.000000
25%          66.000000
50%          82.000000
75%          92.000000
max         100.000000
Name: shop_response_rate, dtype: float64

In [33]:
train_df[train_df['shopId'] == 1007291976]['shop_response_rate'].describe()

count    1556.00000
mean       29.12982
std        17.01117
min        15.00000
25%        15.00000
50%        17.00000
75%        50.00000
max        57.00000
Name: shop_response_rate, dtype: float64

Response rate is mostly empty in one shop only, imputting with median as solution

In [34]:
# =========================================================
# GLOBAL MEDIAN (FALLBACK)
# =========================================================

global_median_response_rate = (
    train_df['shop_response_rate']
    .median()
)

# =========================================================
# SHOP-LEVEL MEDIAN
# =========================================================

shop_median_response_rate = (

    train_df
    .groupby('shopId')['shop_response_rate']
    .median()
)

# =========================================================
# MAP SHOP MEDIAN
# =========================================================

train_df['shop_response_rate_shop_median'] = (
    train_df['shopId']
    .map(shop_median_response_rate)
)

# =========================================================
# FILL MISSING
# 1. shop median
# 2. fallback global median
# =========================================================

train_df['shop_response_rate'] = (

    train_df['shop_response_rate']

    .fillna(
        train_df['shop_response_rate_shop_median']
    )

    .fillna(global_median_response_rate)
)

# =========================================================
# OPTIONAL CLEANUP
# =========================================================

train_df = train_df.drop(
    columns=['shop_response_rate_shop_median']
)

In [35]:
train_df.shape

(301079, 39)

In [36]:
# missing flag
train_df['shop_response_rate_missing'] = (
    train_df['shop_response_rate'].isna()
)

Due to the nature of the problem, we will need to isolate 100 random data set from validation to mimic the anchor set

In [37]:
# =========================================================
# SAMPLE 100 ANCHOR ROWS
# =========================================================

sample_df = validation_df.sample(
    n=100,
    random_state=42
)

# =========================================================
# REMAINING ROWS (NOT IN SAMPLE)
# =========================================================

remaining_df = validation_df.drop(
    sample_df.index
).copy()

# =========================================================
# CHECK
# =========================================================

print("Validation rows :", len(validation_df))
print("Sample rows     :", len(sample_df))
print("Remaining rows  :", len(remaining_df))
print("Total check     :", len(sample_df) + len(remaining_df))

Validation rows : 2903
Sample rows     : 100
Remaining rows  : 2803
Total check     : 2903

In [38]:
sample_df.shape

(100, 36)

In [39]:
train_df.shape

(301079, 40)

Adding brand missing tags, stock_missing tag, shop_response_missing tag, imputting brand_freq and missing shop_response_rate from training data

In [40]:
sample_df['stock_available'] = sample_df['stock'].notna().astype(int)

sample_df['brand_missing'] = sample_df['brand'].isna().astype(int)

In [41]:

sample_df['brand'] = sample_df['brand'].fillna('unknown')

sample_df['brand_freq'] = (
    sample_df['brand']
    .map(brand_counts)
    .fillna(0)
)

# =========================================================
# MAP SHOP-LEVEL MEDIAN FROM TRAIN
# =========================================================

sample_df['shop_response_rate_shop_median'] = (
    sample_df['shopId']
    .map(shop_median_response_rate)
)

# =========================================================
# IMPUTE
# 1. shop median
# 2. global median fallback
# =========================================================

sample_df['shop_response_rate'] = (

    sample_df['shop_response_rate']

    .fillna(
        sample_df['shop_response_rate_shop_median']
    )

    .fillna(global_median_response_rate)
)

# =========================================================
# OPTIONAL CLEANUP
# =========================================================

sample_df = sample_df.drop(
    columns=['shop_response_rate_shop_median']
)

In [42]:
sample_df.shape

(100, 39)

In [43]:
# missing flag
sample_df['shop_response_rate_missing'] = (
    sample_df['shop_response_rate'].isna()
)

In [44]:
train_df.shape

(301079, 40)

In [45]:
sample_df.shape

(100, 40)

Combining train and sample because the derivative features need to read from previous days

In [46]:
import numpy as np
import pandas as pd

# =========================================================
# COMBINE TRAIN + sample
# =========================================================

full_df = pd.concat([train_df, sample_df], axis=0)

# preserve indices
train_idx = train_df.index
sample_idx = sample_df.index

In [47]:
full_df.shape

(301179, 40)

In [48]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 301179 entries, 0 to 304041
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   capturedAt                  301179 non-null  datetime64[ns]
 1   shopId                      301179 non-null  int64
 2   itemId                      301179 non-null  int64
 3   modelId                     301179 non-null  int64
 4   price                       301179 non-null  int64
 5   priceBeforeDiscount         301179 non-null  int64
 6   promotionId                 301179 non-null  int64
 7   cat_id                      301179 non-null  int64
 8   stock                       3700 non-null    float64
 9   normal_stock                3700 non-null    float64
 10  raw_discount                301179 non-null  int64
 11  show_discount               301179 non-null  int64
 12  brand                       301179 non-null  object
 13  is_free_shipping            301179 non-null  object
 14  is_pre_order                301179 non-null  object
 15  item_price_min              301179 non-null  int64
 16  item_price_max              301179 non-null  int64
 17  review_rating               301179 non-null  float64
 18  total_rating_count          301179 non-null  int64
 19  cmt_count                   301179 non-null  int64
 20  shop_rating                 301179 non-null  float64
 21  shop_response_rate          301179 non-null  float64
 22  shop_follower_count         301179 non-null  int64
 23  is_official_shop            301179 non-null  object
 24  is_verified                 301179 non-null  object
 25  is_preferred_plus_seller    301179 non-null  object
 26  tag1                        301179 non-null  object
 27  date                        301179 non-null  object
 28  tag2                        301179 non-null  object
 29  day_of_week                 301179 non-null  int32
 30  is_weekend                  301179 non-null  int32
 31  month                       301179 non-null  int32
 32  day_of_year                 301179 non-null  int32
 33  is_morning                  301179 non-null  int32
 34  is_afternoon                301179 non-null  int32
 35  is_evening                  301179 non-null  int32
 36  stock_available             301179 non-null  int32
 37  brand_missing               301179 non-null  int32
 38  brand_freq                  301179 non-null  int64
 39  shop_response_rate_missing  301179 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(5), int32(9), int64(15), object(9)
memory usage: 81.9+ MB

In [49]:
# =========================================================
# SORT CHRONOLOGICALLY
# VERY IMPORTANT
# =========================================================

full_df = full_df.sort_values(
    ['shopId', 'itemId', 'modelId', 'capturedAt']
)

# =========================================================
# GROUPS
# =========================================================

# fine-grained
model_group = full_df.groupby(
    ['shopId', 'itemId', 'modelId']
)

# broader fallback
item_group = full_df.groupby(
    ['shopId', 'itemId']
)

In [50]:
# =========================================================
# MODEL-LEVEL SAFE LAG FEATURES
# =========================================================

# ---------------------------------------------------------
# PREVIOUS PRICES
# ---------------------------------------------------------

full_df['model_price_last_scrape'] = (
    model_group['price'].shift(1)
)

full_df['model_price_lag_2'] = (
    model_group['price'].shift(2)
)

# ---------------------------------------------------------
# HISTORY INDICATORS
# VERY IMPORTANT
# ---------------------------------------------------------

# has at least 1 previous observation
full_df['model_has_price_history'] = (
    full_df['model_price_last_scrape']
    .notna()
    .astype(int)
)

# has at least 2 previous observations
full_df['model_has_lag_2_history'] = (
    full_df['model_price_lag_2']
    .notna()
    .astype(int)
)

# ---------------------------------------------------------
# SAFE FILLING
# ---------------------------------------------------------

# fill AFTER creating indicators
full_df['model_price_last_scrape'] = (
    full_df['model_price_last_scrape']
    .fillna(0)
)

full_df['model_price_lag_2'] = (
    full_df['model_price_lag_2']
    .fillna(0)
)

# =========================================================
# TIME FEATURES
# =========================================================

full_df['model_days_since_last_scrape'] = (
    full_df['capturedAt']
    - model_group['capturedAt'].shift(1)
).dt.days

# ---------------------------------------------------------
# HISTORY INDICATOR
# ---------------------------------------------------------

full_df['model_has_time_history'] = (
    full_df['model_days_since_last_scrape']
    .notna()
    .astype(int)
)

# ---------------------------------------------------------
# SAFE FILLING
# ---------------------------------------------------------

full_df['model_days_since_last_scrape'] = (
    full_df['model_days_since_last_scrape']
    .fillna(0)
    .astype(int)
)

In [51]:
# =========================================================
# ITEM-LEVEL EXPANDING FEATURES (LEAKAGE SAFE)
# =========================================================

# item grouping
item_group = full_df.groupby(['shopId', 'itemId'])

# =========================================================
# HISTORICAL AVERAGE PRICE
# =========================================================

full_df['item_avg_price_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().mean()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_avg_price_hist_available'] = (
    full_df['item_avg_price_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_avg_price_hist'] = (
    full_df['item_avg_price_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MIN PRICE
# =========================================================

full_df['item_price_min_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().min()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_price_min_hist_available'] = (
    full_df['item_price_min_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_price_min_hist'] = (
    full_df['item_price_min_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MAX PRICE
# =========================================================

full_df['item_price_max_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().max()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_price_max_hist_available'] = (
    full_df['item_price_max_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_price_max_hist'] = (
    full_df['item_price_max_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL VOLATILITY
# =========================================================

full_df['item_price_volatility_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().std()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_price_volatility_hist_available'] = (
    full_df['item_price_volatility_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_price_volatility_hist'] = (
    full_df['item_price_volatility_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# HISTORICAL OBSERVATION COUNT
# VERY USEFUL FEATURE
# =========================================================

full_df['item_hist_observation_count'] = (
    item_group.cumcount()
)

# =========================================================
# OPTIONAL:
# HAS ANY HISTORY
# =========================================================

full_df['item_has_history'] = (
    full_df['item_hist_observation_count'] > 0
).astype(int)

In [52]:
# =========================================================
# MODEL-LEVEL PRICE CHANGE FEATURES (PROPER + SAFE)
# =========================================================

# ---------------------------------------------------------
# PREVIOUS PRICE CHANGE
# ---------------------------------------------------------

full_df['model_prev_price_change'] = (
    full_df['model_price_last_scrape']
    - full_df['model_price_lag_2']
)

# =========================================================
# AVAILABILITY FLAG
# need BOTH lag1 and lag2 to exist
# =========================================================

full_df['model_prev_price_change_available'] = (
    (
        full_df['model_has_price_history'] == 1
    )
    &
    (
        full_df['model_has_lag_2_history'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# first/second occurrences have no meaningful change
# =========================================================

full_df['model_prev_price_change'] = (
    full_df['model_prev_price_change']
    .fillna(0)
)

# =========================================================
# PERCENTAGE CHANGE
# =========================================================

full_df['model_prev_price_change_pct'] = np.where(
    full_df['model_has_lag_2_history'] == 1,
    (
        full_df['model_prev_price_change']
        /
        full_df['model_price_lag_2'].replace(0, 1)
    ) * 100,
    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['model_prev_price_change_pct_available'] = (
    full_df['model_prev_price_change_pct']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['model_prev_price_change_pct'] = (
    full_df['model_prev_price_change_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE CHANGE MAGNITUDE
# often very useful for tree models
# =========================================================

full_df['model_prev_price_change_abs'] = (
    full_df['model_prev_price_change']
    .abs()
)

# =========================================================
# OPTIONAL:
# PRICE DIRECTION
# =========================================================

full_df['model_price_direction'] = np.sign(
    full_df['model_prev_price_change']
)

# values:
# -1 = price decreased
#  0 = unchanged/no history
# +1 = price increased

In [53]:
full_df.shape

(301179, 62)

In [54]:
# =========================================================
# MODEL-LEVEL ROLLING FEATURES (LEAKAGE SAFE)
# =========================================================

# model grouping
model_group = full_df.groupby(
    ['shopId', 'itemId', 'modelId']
)

# =========================================================
# ROLLING 7-OBSERVATION AVERAGE
# =========================================================

full_df['model_price_7d_avg_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).rolling(
            window=7,
            min_periods=1
        ).mean()
    )
    .reset_index(level=[0,1,2], drop=True)
)

# availability flag
full_df['model_price_7d_avg_hist_available'] = (
    full_df['model_price_7d_avg_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['model_price_7d_avg_hist'] = (
    full_df['model_price_7d_avg_hist']
    .fillna(0)
)

# ===========

In [55]:
full_df.shape

(301179, 64)

In [56]:
# =========================================================
# ITEM-LEVEL LAG FEATURES
# =========================================================

item_group = full_df.groupby(['shopId', 'itemId'])

# ---------------------------------------------------------
# LAGS
# ---------------------------------------------------------

full_df['item_price_last_scrape'] = (
    item_group['price'].shift(1)
)

full_df['item_price_lag_2'] = (
    item_group['price'].shift(2)
)

# =========================================================
# HISTORY FLAGS
# =========================================================

full_df['item_has_price_history'] = (
    full_df['item_price_last_scrape']
    .notna()
    .astype(int)
)

full_df['item_has_lag_2_history'] = (
    full_df['item_price_lag_2']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_price_last_scrape'] = (
    full_df['item_price_last_scrape']
    .fillna(0)
)

full_df['item_price_lag_2'] = (
    full_df['item_price_lag_2']
    .fillna(0)
)

In [57]:
full_df.shape

(301179, 68)

In [58]:
# =========================================================
# ITEM-LEVEL PRICE CHANGE FEATURES (PROPER + SAFE)
# =========================================================

# ---------------------------------------------------------
# PREVIOUS PRICE CHANGE
# ---------------------------------------------------------

full_df['item_prev_price_change'] = (
    full_df['item_price_last_scrape']
    - full_df['item_price_lag_2']
)

# =========================================================
# AVAILABILITY FLAG
# need BOTH lag1 and lag2 to exist
# =========================================================

full_df['item_prev_price_change_available'] = (
    (
        full_df['item_has_price_history'] == 1
    )
    &
    (
        full_df['item_has_lag_2_history'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_prev_price_change'] = (
    full_df['item_prev_price_change']
    .fillna(0)
)

# =========================================================
# PERCENTAGE CHANGE
# =========================================================

full_df['item_prev_price_change_pct'] = np.where(
    full_df['item_has_lag_2_history'] == 1,
    (
        full_df['item_prev_price_change']
        /
        full_df['item_price_lag_2'].replace(0, 1)
    ) * 100,
    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['item_prev_price_change_pct_available'] = (
    full_df['item_prev_price_change_pct']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_prev_price_change_pct'] = (
    full_df['item_prev_price_change_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE CHANGE MAGNITUDE
# =========================================================

full_df['item_prev_price_change_abs'] = (
    full_df['item_prev_price_change']
    .abs()
)

# =========================================================
# OPTIONAL:
# PRICE DIRECTION
# =========================================================

full_df['item_price_direction'] = np.sign(
    full_df['item_prev_price_change']
)

# values:
# -1 = price decreased
#  0 = unchanged/no history
# +1 = price increased

In [59]:
# =========================================================
# MODEL-LEVEL EXPANDING FEATURES (SAFE)
# =========================================================

model_group = full_df.groupby(
    ['shopId', 'itemId', 'modelId']
)

# =========================================================
# HISTORICAL AVG PRICE
# =========================================================

full_df['model_avg_price_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().mean()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_avg_price_hist_available'] = (
    full_df['model_avg_price_hist']
    .notna()
    .astype(int)
)

full_df['model_avg_price_hist'] = (
    full_df['model_avg_price_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MIN PRICE
# =========================================================

full_df['model_price_min_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().min()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_price_min_hist_available'] = (
    full_df['model_price_min_hist']
    .notna()
    .astype(int)
)

full_df['model_price_min_hist'] = (
    full_df['model_price_min_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MAX PRICE
# =========================================================

full_df['model_price_max_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().max()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_price_max_hist_available'] = (
    full_df['model_price_max_hist']
    .notna()
    .astype(int)
)

full_df['model_price_max_hist'] = (
    full_df['model_price_max_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL VOLATILITY
# =========================================================

full_df['model_price_volatility_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().std()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_price_volatility_hist_available'] = (
    full_df['model_price_volatility_hist']
    .notna()
    .astype(int)
)

full_df['model_price_volatility_hist'] = (
    full_df['model_price_volatility_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# HISTORY COUNT
# =========================================================

full_df['model_hist_observation_count'] = (
    model_group.cumcount()
)

full_df['model_has_history'] = (
    full_df['model_hist_observation_count'] > 0
).astype(int)

In [60]:
# =========================================================
# MODEL-LEVEL PRICE POSITION FEATURES (SAFE)
# =========================================================

# ---------------------------------------------------------
# POSITION IN HISTORICAL RANGE
# ---------------------------------------------------------

full_df['model_price_position_hist'] = np.where(

    (
        full_df['model_price_max_hist']
        - full_df['model_price_min_hist']
    ) != 0,

    (
        full_df['model_price_last_scrape']
        - full_df['model_price_min_hist']
    )
    /
    (
        full_df['model_price_max_hist']
        - full_df['model_price_min_hist']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# requires:
# - history exists
# - min/max history exists
# =========================================================

full_df['model_price_position_hist_available'] = (
    (
        full_df['model_has_price_history'] == 1
    )
    &
    (
        full_df['model_price_min_hist_available'] == 1
    )
    &
    (
        full_df['model_price_max_hist_available'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# =========================================================

full_df['model_price_position_hist'] = (
    full_df['model_price_position_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# OUTSIDE HISTORICAL RANGE FLAGS
# =========================================================

full_df['model_price_above_hist_max'] = (
    full_df['model_price_last_scrape']
    > full_df['model_price_max_hist']
).astype(int)

full_df['model_price_below_hist_min'] = (
    full_df['model_price_last_scrape']
    < full_df['model_price_min_hist']
).astype(int)

# =========================================================
# =========================================================
# ITEM-LEVEL PRICE POSITION FEATURES (SAFE)
# =========================================================
# =========================================================

# ---------------------------------------------------------
# POSITION IN HISTORICAL RANGE
# ---------------------------------------------------------

full_df['item_price_position_hist'] = np.where(

    (
        full_df['item_price_max_hist']
        - full_df['item_price_min_hist']
    ) != 0,

    (
        full_df['item_price_last_scrape']
        - full_df['item_price_min_hist']
    )
    /
    (
        full_df['item_price_max_hist']
        - full_df['item_price_min_hist']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['item_price_position_hist_available'] = (
    (
        full_df['item_has_price_history'] == 1
    )
    &
    (
        full_df['item_price_min_hist_available'] == 1
    )
    &
    (
        full_df['item_price_max_hist_available'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_price_position_hist'] = (
    full_df['item_price_position_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# OUTSIDE HISTORICAL RANGE FLAGS
# =========================================================

full_df['item_price_above_hist_max'] = (
    full_df['item_price_last_scrape']
    > full_df['item_price_max_hist']
).astype(int)

full_df['item_price_below_hist_min'] = (
    full_df['item_price_last_scrape']
    < full_df['item_price_min_hist']
).astype(int)

In [61]:
# =========================================================
# MODEL-LEVEL TREND FEATURES (SAFE)
# =========================================================

# ---------------------------------------------------------
# TREND PER DAY
# ---------------------------------------------------------

full_df['model_price_trend_per_day'] = np.where(

    (
        full_df['model_prev_price_change_available'] == 1
    )
    &
    (
        full_df['model_has_time_history'] == 1
    )
    &
    (
        full_df['model_days_since_last_scrape'] > 0
    ),

    (
        full_df['model_prev_price_change']
        /
        full_df['model_days_since_last_scrape']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['model_price_trend_per_day_available'] = (
    full_df['model_price_trend_per_day']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['model_price_trend_per_day'] = (
    full_df['model_price_trend_per_day']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE TREND
# =========================================================

full_df['model_price_trend_abs'] = (
    full_df['model_price_trend_per_day']
    .abs()
)

# =========================================================
# OPTIONAL:
# TREND DIRECTION
# =========================================================

full_df['model_price_trend_direction'] = np.sign(
    full_df['model_price_trend_per_day']
)

In [62]:
# =========================================================
# ITEM-LEVEL TIME FEATURES
# =========================================================

item_group = full_df.groupby(['shopId', 'itemId'])

# ---------------------------------------------------------
# DAYS SINCE LAST SCRAPE
# ---------------------------------------------------------

full_df['item_days_since_last_scrape'] = (
    full_df['capturedAt']
    - item_group['capturedAt'].shift(1)
).dt.days

# =========================================================
# HISTORY FLAG
# =========================================================

full_df['item_has_time_history'] = (
    full_df['item_days_since_last_scrape']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_days_since_last_scrape'] = (
    full_df['item_days_since_last_scrape']
    .fillna(0)
    .astype(int)
)

# =========================================================
# OPTIONAL:
# DAYS SINCE FIRST SEEN
# =========================================================

full_df['item_days_since_first_seen'] = (
    full_df['capturedAt']
    - item_group['capturedAt'].transform('min')
).dt.days

In [63]:
# =========================================================
# ITEM-LEVEL TREND FEATURES (SAFE)
# =========================================================

# ---------------------------------------------------------
# TREND PER DAY
# ---------------------------------------------------------

full_df['item_price_trend_per_day'] = np.where(

    (
        full_df['item_prev_price_change_available'] == 1
    )
    &
    (
        full_df['item_has_time_history'] == 1
    )
    &
    (
        full_df['item_days_since_last_scrape'] > 0
    ),

    (
        full_df['item_prev_price_change']
        /
        full_df['item_days_since_last_scrape']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['item_price_trend_per_day_available'] = (
    full_df['item_price_trend_per_day']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_price_trend_per_day'] = (
    full_df['item_price_trend_per_day']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE TREND
# =========================================================

full_df['item_price_trend_abs'] = (
    full_df['item_price_trend_per_day']
    .abs()
)

# =========================================================
# OPTIONAL:
# TREND DIRECTION
# =========================================================

full_df['item_price_trend_direction'] = np.sign(
    full_df['item_price_trend_per_day']
)

In [64]:
full_df.shape

(301179, 103)

In [65]:
# =========================================================
# DISCOUNT FEATURES (SAFE + PRODUCTION GRADE)
# =========================================================

# ---------------------------------------------------------
# ORIGINAL PRICE AVAILABLE
# ---------------------------------------------------------

full_df['price_before_discount_available'] = (
    full_df['priceBeforeDiscount']
    .notna()
    .astype(int)
)

# ---------------------------------------------------------
# SAFE FILL
# assumption:
# missing original price = no discount
# ---------------------------------------------------------

full_df['priceBeforeDiscount'] = (
    full_df['priceBeforeDiscount']
    .fillna(full_df['price'])
)

# =========================================================
# IS ON SALE
# =========================================================

full_df['is_on_sale'] = (
    full_df['price']
    < full_df['priceBeforeDiscount']
).astype(int)

# =========================================================
# RAW DISCOUNT AMOUNT
# =========================================================

full_df['discount_amount'] = (
    full_df['priceBeforeDiscount']
    - full_df['price']
)

# =========================================================
# DISCOUNT DEPTH
# normalized discount intensity
# =========================================================

full_df['discount_depth'] = np.where(

    full_df['priceBeforeDiscount'] > 0,

    (
        full_df['discount_amount']
        /
        full_df['priceBeforeDiscount']
    ),

    np.nan
)

# availability flag
full_df['discount_depth_available'] = (
    full_df['discount_depth']
    .notna()
    .astype(int)
)

# safe fill
full_df['discount_depth'] = (
    full_df['discount_depth']
    .fillna(0)
)

# =========================================================
# EFFECTIVE DISCOUNT %
# if show_discount exists
# =========================================================

full_df['show_discount_available'] = (
    full_df['show_discount']
    .notna()
    .astype(int)
)

full_df['effective_discount_pct'] = (
    full_df['show_discount'] / 100
)

full_df['effective_discount_pct'] = (
    full_df['effective_discount_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# DISCOUNT VS HISTORICAL ITEM AVG
# VERY POWERFUL FEATURE
# =========================================================

full_df['price_vs_item_hist_avg_pct'] = np.where(

    full_df['item_avg_price_hist_available'] == 1,

    (
        (
            full_df['price']
            - full_df['item_avg_price_hist']
        )
        /
        full_df['item_avg_price_hist'].replace(0, 1)
    ) * 100,

    np.nan
)

full_df['price_vs_item_hist_avg_pct_available'] = (
    full_df['price_vs_item_hist_avg_pct']
    .notna()
    .astype(int)
)

full_df['price_vs_item_hist_avg_pct'] = (
    full_df['price_vs_item_hist_avg_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# SHARP DISCOUNT FLAG
# =========================================================

full_df['is_sharp_discount'] = (
    full_df['model_prev_price_change_pct'] < -20
).astype(int)

# =========================================================
# POPULARITY FEATURES
# =========================================================

# ---------------------------------------------------------
# SHOP POPULARITY
# ---------------------------------------------------------

full_df['shop_follower_count_available'] = (
    full_df['shop_follower_count']
    .notna()
    .astype(int)
)

full_df['shop_follower_count'] = (
    full_df['shop_follower_count']
    .fillna(0)
)

full_df['shop_popularity'] = np.log1p(
    full_df['shop_follower_count']
)

# =========================================================
# ITEM POPULARITY
# =========================================================

full_df['total_rating_count_available'] = (
    full_df['total_rating_count']
    .notna()
    .astype(int)
)

full_df['total_rating_count'] = (
    full_df['total_rating_count']
    .fillna(0)
)

full_df['item_popularity'] = np.log1p(
    full_df['total_rating_count']
)

# =========================================================
# REVIEW SCORE
# =========================================================

full_df['review_rating_available'] = (
    full_df['review_rating']
    .notna()
    .astype(int)
)

# fill missing with neutral score
full_df['review_rating'] = (
    full_df['review_rating']
    .fillna(0)
)

full_df['review_score_normalized'] = (
    full_df['review_rating'] / 5.0
)

# =========================================================
# OPTIONAL:
# INTERACTION FEATURES
# VERY STRONG FOR TREE MODELS
# =========================================================

full_df['discount_x_popularity'] = (
    full_df['discount_depth']
    * full_df['item_popularity']
)

full_df['discount_x_review_score'] = (
    full_df['discount_depth']
    * full_df['review_score_normalized']
)

C:\Users\purna\AppData\Local\Temp\ipykernel_25664\514726802.py:156: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['shop_popularity'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\514726802.py:164: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['total_rating_count_available'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\514726802.py:175: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['item_popularity'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\514726802.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['review_rating_available'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\514726802.py:195: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['review_score_normalized'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\514726802.py:205: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['discount_x_popularity'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\514726802.py:210: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['discount_x_review_score'] = (

In [66]:
full_df.shape

(301179, 121)

In [67]:
full_df.head(2)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,price_vs_item_hist_avg_pct_available,is_sharp_discount,shop_follower_count_available,shop_popularity,total_rating_count_available,item_popularity,review_rating_available,review_score_normalized,discount_x_popularity,discount_x_review_score
10660,2025-02-02 01:05:10.076,1000692,24160686617,187291892768,60000000,0,0,100632,NaN,NaN,...,0,0,1,6.843750,1,5.521461,1,0.995984,0.0,0.0
23754,2025-02-07 01:05:15.527,1000692,24160686617,187291892768,60000000,0,0,100632,NaN,NaN,...,1,0,1,6.844815,1,5.525453,1,0.996000,0.0,0.0

In [68]:
for i, col in enumerate(full_df.columns, 1):
    print(f"{i}. {col}")

1. capturedAt
2. shopId
3. itemId
4. modelId
5. price
6. priceBeforeDiscount
7. promotionId
8. cat_id
9. stock
10. normal_stock
11. raw_discount
12. show_discount
13. brand
14. is_free_shipping
15. is_pre_order
16. item_price_min
17. item_price_max
18. review_rating
19. total_rating_count
20. cmt_count
21. shop_rating
22. shop_response_rate
23. shop_follower_count
24. is_official_shop
25. is_verified
26. is_preferred_plus_seller
27. tag1
28. date
29. tag2
30. day_of_week
31. is_weekend
32. month
33. day_of_year
34. is_morning
35. is_afternoon
36. is_evening
37. stock_available
38. brand_missing
39. brand_freq
40. shop_response_rate_missing
41. model_price_last_scrape
42. model_price_lag_2
43. model_has_price_history
44. model_has_lag_2_history
45. model_days_since_last_scrape
46. model_has_time_history
47. item_avg_price_hist
48. item_avg_price_hist_available
49. item_price_min_hist
50. item_price_min_hist_available
51. item_price_max_hist
52. item_price_max_hist_available
53. item_price_volatility_hist
54. item_price_volatility_hist_available
55. item_hist_observation_count
56. item_has_history
57. model_prev_price_change
58. model_prev_price_change_available
59. model_prev_price_change_pct
60. model_prev_price_change_pct_available
61. model_prev_price_change_abs
62. model_price_direction
63. model_price_7d_avg_hist
64. model_price_7d_avg_hist_available
65. item_price_last_scrape
66. item_price_lag_2
67. item_has_price_history
68. item_has_lag_2_history
69. item_prev_price_change
70. item_prev_price_change_available
71. item_prev_price_change_pct
72. item_prev_price_change_pct_available
73. item_prev_price_change_abs
74. item_price_direction
75. model_avg_price_hist
76. model_avg_price_hist_available
77. model_price_min_hist
78. model_price_min_hist_available
79. model_price_max_hist
80. model_price_max_hist_available
81. model_price_volatility_hist
82. model_price_volatility_hist_available
83. model_hist_observation_count
84. model_has_history
85. model_price_position_hist
86. model_price_position_hist_available
87. model_price_above_hist_max
88. model_price_below_hist_min
89. item_price_position_hist
90. item_price_position_hist_available
91. item_price_above_hist_max
92. item_price_below_hist_min
93. model_price_trend_per_day
94. model_price_trend_per_day_available
95. model_price_trend_abs
96. model_price_trend_direction
97. item_days_since_last_scrape
98. item_has_time_history
99. item_days_since_first_seen
100. item_price_trend_per_day
101. item_price_trend_per_day_available
102. item_price_trend_abs
103. item_price_trend_direction
104. price_before_discount_available
105. is_on_sale
106. discount_amount
107. discount_depth
108. discount_depth_available
109. show_discount_available
110. effective_discount_pct
111. price_vs_item_hist_avg_pct
112. price_vs_item_hist_avg_pct_available
113. is_sharp_discount
114. shop_follower_count_available
115. shop_popularity
116. total_rating_count_available
117. item_popularity
118. review_rating_available
119. review_score_normalized
120. discount_x_popularity
121. discount_x_review_score

In [69]:
missing_report = full_df.isna().sum().to_frame('missing_count')
missing_report['missing_pct'] = 100 * missing_report['missing_count'] / len(full_df)
missing_report.sort_values(by='missing_pct', ascending=False).head(20)

                                       missing_count  missing_pct
stock                                         297479    98.771495
normal_stock                                  297479    98.771495
capturedAt                                         0     0.000000
model_price_min_hist_available                     0     0.000000
item_price_position_hist_available                 0     0.000000
item_price_position_hist                           0     0.000000
model_price_below_hist_min                         0     0.000000
model_price_above_hist_max                         0     0.000000
model_price_position_hist_available                0     0.000000
model_price_position_hist                          0     0.000000
model_has_history                                  0     0.000000
model_hist_observation_count                       0     0.000000
model_price_volatility_hist_available              0     0.000000
model_price_volatility_hist                        0     0.000000
model_price_max_hist_available                     0     0.000000
model_price_max_hist                               0     0.000000
model_avg_price_hist_available                     0     0.000000
model_price_min_hist                               0     0.000000
item_price_below_hist_min                          0     0.000000
model_avg_price_hist                               0     0.000000

In [70]:
# =========================================================
# LOG TRANSFORM FEATURES
# =========================================================

import numpy as np

# =========================================================
# HELPER FUNCTION
# for features that can be negative
# =========================================================

def signed_log1p(x):
    return np.sign(x) * np.log1p(np.abs(x))

# =========================================================
# POSITIVE FEATURES
# =========================================================

log_features = [

    # -----------------------------------------------------
    # ITEM HISTORICAL PRICE FEATURES
    # -----------------------------------------------------

    'item_avg_price_hist',
    'item_price_min_hist',
    'item_price_max_hist',
    'item_price_volatility_hist',

    # -----------------------------------------------------
    # MODEL HISTORICAL PRICE FEATURES
    # -----------------------------------------------------

    'model_avg_price_hist',
    'model_price_min_hist',
    'model_price_max_hist',
    'model_price_volatility_hist',

    # -----------------------------------------------------
    # LAG FEATURES
    # -----------------------------------------------------

    'item_price_last_scrape',
    'item_price_lag_2',

    'model_price_last_scrape',
    'model_price_lag_2',

    # -----------------------------------------------------
    # DISCOUNT FEATURES
    # -----------------------------------------------------

    'discount_amount',
    'priceBeforeDiscount',

    # -----------------------------------------------------
    # OBSERVATION / HISTORY FEATURES
    # -----------------------------------------------------

    'item_hist_observation_count',
    'model_hist_observation_count',

    # -----------------------------------------------------
    # TIME FEATURES
    # -----------------------------------------------------

    'item_days_since_first_seen'
]

# =========================================================
# CREATE LOG FEATURES
# =========================================================

for col in log_features:

    if col in full_df.columns:

        full_df[f'{col}_log1p'] = np.log1p(
            full_df[col].clip(lower=0)
        )

# =========================================================
# SIGNED FEATURES
# =========================================================

signed_features = [

    # -----------------------------------------------------
    # PRICE CHANGES
    # -----------------------------------------------------

    'model_prev_price_change',
    'item_prev_price_change',

    # -----------------------------------------------------
    # PERCENTAGE CHANGES
    # -----------------------------------------------------

    'model_prev_price_change_pct',
    'item_prev_price_change_pct',

    # -----------------------------------------------------
    # TREND FEATURES
    # -----------------------------------------------------

    'model_price_trend_per_day',
    'item_price_trend_per_day'
]

# =========================================================
# CREATE SIGNED LOG FEATURES
# =========================================================

for col in signed_features:

    if col in full_df.columns:

        full_df[f'{col}_signed_log1p'] = (
            np.sign(full_df[col])
            *
            np.log1p(np.abs(full_df[col]))
        )

# =========================================================
# OPTIONAL:
# LOG TRANSFORM TARGET
# =========================================================

full_df['price_log1p'] = np.log1p(
    full_df['price']
)

print("Log-transformed features created successfully.")

Log-transformed features created successfully.

C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3949125261.py:129: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['price_log1p'] = np.log1p(

In [71]:
full_df.shape

(301179, 145)

In [72]:
full_df.duplicated().sum()

0

In [73]:
full_df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
capturedAt,301179,NaN,NaN,NaN,2025-02-28 10:24:57.094780928,2025-01-01 22:37:36.424000,2025-02-18 16:03:13.060000,2025-03-03 02:35:54.060999936,2025-03-12 07:31:08.279000064,2025-03-22 04:17:29.207000,NaN
shopId,301179.0,NaN,NaN,NaN,645275882.144711,1000692.0,100291901.0,1002919413.0,1006572327.0,1206969280.0,466450235.57633
itemId,301179.0,NaN,NaN,NaN,19342618773.541195,66326595.0,16547649387.0,22456263718.0,24958046381.0,29960888656.0,8486160647.312671
modelId,301179.0,NaN,NaN,NaN,164936202579.853088,52465307.0,118322901940.0,185360511591.0,223455354284.0,257896972082.0,73657985667.48082
price,301179.0,NaN,NaN,NaN,52712209.682614,100000.0,9900000.0,20900000.0,59900000.0,1660000000.0,91536568.284388
...,...,...,...,...,...,...,...,...,...,...,...
model_prev_price_change_pct_signed_log1p,301179.0,NaN,NaN,NaN,0.001499,-4.493121,0.0,0.0,0.0,6.637348,0.216548
item_prev_price_change_pct_signed_log1p,301179.0,NaN,NaN,NaN,0.003851,-4.493121,0.0,0.0,0.0,6.637348,0.355153
model_price_trend_per_day_signed_log1p,301179.0,NaN,NaN,NaN,0.006569,-19.905462,0.0,0.0,0.0,19.212315,0.734652
item_price_trend_per_day_signed_log1p,301179.0,NaN,NaN,NaN,0.014233,-19.922533,0.0,0.0,0.0,19.337371,1.215343
price_log1p,301179.0,NaN,NaN,NaN,16.984283,11.512935,16.108045,16.85526,17.908187,21.230083,1.270153

In [74]:
[col for col in full_df.columns if 'count' in col]

['priceBeforeDiscount',
 'raw_discount',
 'show_discount',
 'total_rating_count',
 'cmt_count',
 'shop_follower_count',
 'item_hist_observation_count',
 'model_hist_observation_count',
 'price_before_discount_available',
 'discount_amount',
 'discount_depth',
 'discount_depth_available',
 'show_discount_available',
 'effective_discount_pct',
 'is_sharp_discount',
 'shop_follower_count_available',
 'total_rating_count_available',
 'discount_x_popularity',
 'discount_x_review_score',
 'discount_amount_log1p',
 'priceBeforeDiscount_log1p',
 'item_hist_observation_count_log1p',
 'model_hist_observation_count_log1p']

In [75]:
# =========================================================
# ITEM-LEVEL LOG-IQR OUTLIER DETECTION
# ONLY FLAG:
# - ABOVE UPPER BOUND
# - is_on_sale == 0
# =========================================================

import numpy as np
import pandas as pd

# =========================================================
# SANDBOX COPY
# =========================================================

full_df2 = full_df.copy()

# =========================================================
# PARAMETERS
# =========================================================

IQR_MULTIPLIER = 2
MIN_ITEM_COUNT = 5

# =========================================================
# TRAIN DATA ONLY
# =========================================================

train_df2 = full_df2[
    full_df2['tag2'] == 'TRAIN'
].copy()

# =========================================================
# LOG PRICE
# =========================================================

train_df2['log_price'] = np.log1p(
    train_df2['price']
)

full_df2['log_price'] = np.log1p(
    full_df2['price']
)

# =========================================================
# ITEM-LEVEL LOG-IQR STATS
# =========================================================

item_stats = (

    train_df2
    .groupby('itemId')['log_price']
    .agg(
        q1=lambda x: x.quantile(0.25),
        q3=lambda x: x.quantile(0.75),
        median='median',
        count='count'
    )
)

# =========================================================
# IQR
# =========================================================

item_stats['iqr'] = (
    item_stats['q3']
    - item_stats['q1']
)

# =========================================================
# LOWER / UPPER BOUNDS
# =========================================================

item_stats['lower_bound'] = (

    item_stats['q1']
    - IQR_MULTIPLIER * item_stats['iqr']
)

item_stats['upper_bound'] = (

    item_stats['q3']
    + IQR_MULTIPLIER * item_stats['iqr']
)

# =========================================================
# MERGE BACK
# =========================================================

full_df2 = full_df2.merge(

    item_stats[
        [
            'lower_bound',
            'upper_bound',
            'count'
        ]
    ],

    on='itemId',
    how='left'
)

# =========================================================
# OUTLIER FLAG
# ONLY:
# - ABOVE UPPER BOUND
# - NOT ON SALE
# - ENOUGH HISTORY
# =========================================================

full_df2['item_log_iqr_outlier'] = np.where(

    (
        (full_df2['count'] >= MIN_ITEM_COUNT)
        &
        (full_df2['log_price'] > full_df2['upper_bound'])
        &
        (full_df2['is_on_sale'] == 0)
    ),

    1,

    0
)

# =========================================================
# DISTANCE ABOVE UPPER BOUND
# =========================================================

full_df2['item_iqr_distance'] = np.where(

    full_df2['log_price']
    > full_df2['upper_bound'],

    full_df2['log_price']
    - full_df2['upper_bound'],

    0
)

# =========================================================
# SUMMARY
# =========================================================

print("=" * 60)

print(
    f"Detected outliers: "
    f"{full_df2['item_log_iqr_outlier'].sum():,}"
)

print("=" * 60)

# =========================================================
# VIEW EXAMPLES
# =========================================================

outlier_examples = full_df2[
    full_df2['item_log_iqr_outlier'] == 1
].copy()

# =========================================================
# SORT MOST EXTREME
# =========================================================

outlier_examples = outlier_examples.sort_values(
    by='item_iqr_distance',
    ascending=False
)

# =========================================================
# DISPLAY WITH REFERENCE PRICES
# =========================================================

outlier_examples['lower_bound_price'] = np.expm1(
    outlier_examples['lower_bound']
)

outlier_examples['upper_bound_price'] = np.expm1(
    outlier_examples['upper_bound']
)

# =========================================================
# DISPLAY COLUMNS
# =========================================================

display_cols = [

    'capturedAt',

    'shopId',
    'itemId',
    'modelId',

    # current pricing
    'price',
    'priceBeforeDiscount',

    # discount info
    'is_on_sale',
    'discount_amount',
    'discount_depth',
    'effective_discount_pct',
    'is_sharp_discount',

    # log price
    'log_price',

    # historical references
    'item_avg_price_hist',
    'item_price_min_hist',
    'item_price_max_hist',

    # IQR bounds
    'lower_bound_price',
    'upper_bound_price',

    # anomaly strength
    'item_iqr_distance',

    # history count
    'count'
]

# =========================================================
# SHOW TOP OUTLIERS
# =========================================================

display(
    outlier_examples[
        display_cols
    ].head(10)
)

# =========================================================
# SEE TEMP COLUMNS CREATED
# =========================================================

new_cols = sorted(
    list(
        set(full_df2.columns)
        -
        set(full_df.columns)
    )
)

print("\nNEW TEMPORARY COLUMNS:\n")

for col in new_cols:
    print(col)

============================================================
Detected outliers: 4,372
============================================================

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,is_on_sale,discount_amount,discount_depth,effective_discount_pct,is_sharp_discount,log_price,item_avg_price_hist,item_price_min_hist,item_price_max_hist,lower_bound_price,upper_bound_price,item_iqr_distance,count
123300,2025-02-16 17:21:24.209,1001466875,28616868879,49484612877,25000000,0,0,-25000000,0.0,0.00,0,17.034386,3755000.0,2900000.0,20000000.0,2900000.0,2900000.0,2.154165,24
123288,2025-02-16 17:21:24.209,1001466875,28616868879,49484612876,20000000,0,0,-20000000,0.0,0.00,0,16.811243,2900000.0,2900000.0,2900000.0,2900000.0,2900000.0,1.931021,24
183915,2025-03-12 00:45:51.722,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183909,2025-03-10 22:36:37.609,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183910,2025-03-11 04:39:36.798,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183911,2025-03-11 12:43:11.656,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183912,2025-03-11 16:43:07.385,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183913,2025-03-11 18:43:53.378,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183914,2025-03-11 22:36:23.833,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183916,2025-03-12 02:31:30.121,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096

NEW TEMPORARY COLUMNS:

count
item_iqr_distance
item_log_iqr_outlier
log_price
lower_bound
upper_bound

In [76]:
full_df2.shape

(301179, 151)

In [77]:
clean_df = full_df2[full_df2['item_log_iqr_outlier'] == 0]

In [78]:
clean_df.shape

(296807, 151)

In [79]:
301179-296807

4372

In [80]:
# =========================================================
# CONVERT 't' / 'f' STRING FLAGS TO INTEGER
# =========================================================

tf_cols = [

    'is_official_shop',
    'is_verified',
    'is_preferred_plus_seller',

    'is_free_shipping',
    'is_pre_order'
]

for col in tf_cols:

    clean_df[col] = (

        clean_df[col]

        .fillna('f')

        .str.lower()

        .map({
            't': 1,
            'f': 0
        })

        .astype(int)
    )

C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (

In [81]:
[col for col in clean_df.columns]

['capturedAt',
 'shopId',
 'itemId',
 'modelId',
 'price',
 'priceBeforeDiscount',
 'promotionId',
 'cat_id',
 'stock',
 'normal_stock',
 'raw_discount',
 'show_discount',
 'brand',
 'is_free_shipping',
 'is_pre_order',
 'item_price_min',
 'item_price_max',
 'review_rating',
 'total_rating_count',
 'cmt_count',
 'shop_rating',
 'shop_response_rate',
 'shop_follower_count',
 'is_official_shop',
 'is_verified',
 'is_preferred_plus_seller',
 'tag1',
 'date',
 'tag2',
 'day_of_week',
 'is_weekend',
 'month',
 'day_of_year',
 'is_morning',
 'is_afternoon',
 'is_evening',
 'stock_available',
 'brand_missing',
 'brand_freq',
 'shop_response_rate_missing',
 'model_price_last_scrape',
 'model_price_lag_2',
 'model_has_price_history',
 'model_has_lag_2_history',
 'model_days_since_last_scrape',
 'model_has_time_history',
 'item_avg_price_hist',
 'item_avg_price_hist_available',
 'item_price_min_hist',
 'item_price_min_hist_available',
 'item_price_max_hist',
 'item_price_max_hist_available',
 'item_price_volatility_hist',
 'item_price_volatility_hist_available',
 'item_hist_observation_count',
 'item_has_history',
 'model_prev_price_change',
 'model_prev_price_change_available',
 'model_prev_price_change_pct',
 'model_prev_price_change_pct_available',
 'model_prev_price_change_abs',
 'model_price_direction',
 'model_price_7d_avg_hist',
 'model_price_7d_avg_hist_available',
 'item_price_last_scrape',
 'item_price_lag_2',
 'item_has_price_history',
 'item_has_lag_2_history',
 'item_prev_price_change',
 'item_prev_price_change_available',
 'item_prev_price_change_pct',
 'item_prev_price_change_pct_available',
 'item_prev_price_change_abs',
 'item_price_direction',
 'model_avg_price_hist',
 'model_avg_price_hist_available',
 'model_price_min_hist',
 'model_price_min_hist_available',
 'model_price_max_hist',
 'model_price_max_hist_available',
 'model_price_volatility_hist',
 'model_price_volatility_hist_available',
 'model_hist_observation_count',
 'model_has_history',
 'model_price_position_hist',
 'model_price_position_hist_available',
 'model_price_above_hist_max',
 'model_price_below_hist_min',
 'item_price_position_hist',
 'item_price_position_hist_available',
 'item_price_above_hist_max',
 'item_price_below_hist_min',
 'model_price_trend_per_day',
 'model_price_trend_per_day_available',
 'model_price_trend_abs',
 'model_price_trend_direction',
 'item_days_since_last_scrape',
 'item_has_time_history',
 'item_days_since_first_seen',
 'item_price_trend_per_day',
 'item_price_trend_per_day_available',
 'item_price_trend_abs',
 'item_price_trend_direction',
 'price_before_discount_available',
 'is_on_sale',
 'discount_amount',
 'discount_depth',
 'discount_depth_available',
 'show_discount_available',
 'effective_discount_pct',
 'price_vs_item_hist_avg_pct',
 'price_vs_item_hist_avg_pct_available',
 'is_sharp_discount',
 'shop_follower_count_available',
 'shop_popularity',
 'total_rating_count_available',
 'item_popularity',
 'review_rating_available',
 'review_score_normalized',
 'discount_x_popularity',
 'discount_x_review_score',
 'item_avg_price_hist_log1p',
 'item_price_min_hist_log1p',
 'item_price_max_hist_log1p',
 'item_price_volatility_hist_log1p',
 'model_avg_price_hist_log1p',
 'model_price_min_hist_log1p',
 'model_price_max_hist_log1p',
 'model_price_volatility_hist_log1p',
 'item_price_last_scrape_log1p',
 'item_price_lag_2_log1p',
 'model_price_last_scrape_log1p',
 'model_price_lag_2_log1p',
 'discount_amount_log1p',
 'priceBeforeDiscount_log1p',
 'item_hist_observation_count_log1p',
 'model_hist_observation_count_log1p',
 'item_days_since_first_seen_log1p',
 'model_prev_price_change_signed_log1p',
 'item_prev_price_change_signed_log1p',
 'model_prev_price_change_pct_signed_log1p',
 'item_prev_price_change_pct_signed_log1p',
 'model_price_trend_per_day_signed_log1p',
 'item_price_trend_per_day_signed_log1p',
 'price_log1p',
 'log_price',
 'lower_bound',
 'upper_bound',
 'count',
 'item_log_iqr_outlier',
 'item_iqr_distance']

======================================================================
START MODELLING
======================================================================

In [82]:
# =========================================================
# XGBOOST PRICE PREDICTION PIPELINE
# =========================================================

import numpy as np
import pandas as pd

from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

# =========================================================
# TRAIN / TEST SPLIT
# =========================================================

train_df = clean_df[
    clean_df['tag2'] == 'TRAIN'
].copy()

test_df = clean_df[
    clean_df['tag2'] != 'TRAIN'
].copy()

# =========================================================
# FEATURES USED
# =========================================================

FEATURES = [

    # -----------------------------------------------------
    # CATEGORY / BRAND
    # -----------------------------------------------------

    'cat_id',
    'brand_freq',
    'brand_missing',

    # -----------------------------------------------------
    # TEMPORAL
    # -----------------------------------------------------

    'day_of_week',
    'is_weekend',
    'month',
    'day_of_year',

    'is_morning',
    'is_afternoon',
    'is_evening',

    # -----------------------------------------------------
    # SHOP FEATURES
    # -----------------------------------------------------

    'shop_rating',
    'shop_response_rate',

    'shop_popularity',
    'shop_follower_count_available',

    'is_official_shop',
    'is_verified',
    'is_preferred_plus_seller',

    # -----------------------------------------------------
    # ITEM POPULARITY
    # -----------------------------------------------------

    'item_popularity',
    'total_rating_count_available',

    'review_score_normalized',
    'review_rating_available',

    'cmt_count',

    # -----------------------------------------------------
    # SHIPPING / FLAGS
    # -----------------------------------------------------

    'is_free_shipping',
    'is_pre_order',

    # -----------------------------------------------------
    # DISCOUNT FEATURES
    # -----------------------------------------------------

    'is_on_sale',

    'discount_amount_log1p',
    'discount_depth',

    'effective_discount_pct',

    'is_sharp_discount',

    'discount_x_popularity',
    'discount_x_review_score',

    # -----------------------------------------------------
    # ITEM HISTORY
    # -----------------------------------------------------

    'item_has_history',

    'item_avg_price_hist_log1p',
    'item_price_min_hist_log1p',
    'item_price_max_hist_log1p',

    'item_price_volatility_hist_log1p',

    'item_hist_observation_count_log1p',

    # -----------------------------------------------------
    # ITEM LAGS
    # -----------------------------------------------------

    'item_price_last_scrape_log1p',
    'item_price_lag_2_log1p',

    'item_has_price_history',
    'item_has_lag_2_history',

    # -----------------------------------------------------
    # ITEM PRICE CHANGE
    # -----------------------------------------------------

    'item_prev_price_change_signed_log1p',
    'item_prev_price_change_pct_signed_log1p',

    'item_prev_price_change_abs',

    'item_price_direction',

    # -----------------------------------------------------
    # ITEM TREND
    # -----------------------------------------------------

    'item_days_since_last_scrape',

    'item_days_since_first_seen_log1p',

    'item_price_trend_per_day_signed_log1p',

    'item_price_trend_abs',
    'item_price_trend_direction',

    # -----------------------------------------------------
    # ITEM POSITION
    # -----------------------------------------------------

    'item_price_position_hist',

    'item_price_above_hist_max',
    'item_price_below_hist_min',

    # -----------------------------------------------------
    # MODEL HISTORY
    # -----------------------------------------------------

    'model_has_history',

    'model_avg_price_hist_log1p',
    'model_price_min_hist_log1p',
    'model_price_max_hist_log1p',

    'model_price_volatility_hist_log1p',

    'model_hist_observation_count_log1p',

    # -----------------------------------------------------
    # MODEL LAGS
    # -----------------------------------------------------

    'model_price_last_scrape_log1p',
    'model_price_lag_2_log1p',

    'model_has_price_history',
    'model_has_lag_2_history',

    # -----------------------------------------------------
    # MODEL PRICE CHANGE
    # -----------------------------------------------------

    'model_prev_price_change_signed_log1p',
    'model_prev_price_change_pct_signed_log1p',

    'model_prev_price_change_abs',

    'model_price_direction',

    # -----------------------------------------------------
    # MODEL TREND
    # -----------------------------------------------------

    'model_days_since_last_scrape',

    'model_price_trend_per_day_signed_log1p',

    'model_price_trend_abs',
    'model_price_trend_direction',

    # -----------------------------------------------------
    # MODEL POSITION
    # -----------------------------------------------------

    'model_price_position_hist',

    'model_price_above_hist_max',
    'model_price_below_hist_min',

    # -----------------------------------------------------
    # AVAILABILITY TAGS POSITION
    # -----------------------------------------------------


    'stock_available',

    'item_avg_price_hist_available',
    'item_price_min_hist_available',
    'item_price_max_hist_available',
    'item_price_volatility_hist_available',

    'model_avg_price_hist_available',
    'model_price_min_hist_available',
    'model_price_max_hist_available',
    'model_price_volatility_hist_available',

    'item_prev_price_change_available',
    'item_prev_price_change_pct_available',

    'model_prev_price_change_available',
    'model_prev_price_change_pct_available',

    'model_price_7d_avg_hist_available',

    'model_price_position_hist_available',
    'item_price_position_hist_available',

    'discount_depth_available',
    'show_discount_available',

    'price_before_discount_available',

    'price_vs_item_hist_avg_pct_available',

    'price_vs_item_hist_avg_pct'
]

# =========================================================
# TARGET
# =========================================================

TARGET = 'price_log1p'

# =========================================================
# PREPARE X / Y
# =========================================================

X_train = train_df[FEATURES]
y_train = train_df[TARGET]

X_test = test_df[FEATURES]
y_test = test_df[TARGET]

# =========================================================
# XGBOOST MODEL
# =========================================================

model = XGBRegressor(

    n_estimators=500,
    learning_rate=0.03,

    max_depth=8,

    min_child_weight=5,

    subsample=0.8,
    colsample_bytree=0.8,

    reg_alpha=1,
    reg_lambda=1,

    objective='reg:squarederror',

    random_state=42,

    n_jobs=-1
)

# =========================================================
# TRAIN
# =========================================================

model.fit(
    X_train,
    y_train
)

# =========================================================
# PREDICT
# =========================================================

pred_log = model.predict(X_test)

# back-transform
pred_price = np.expm1(pred_log)

actual_price = np.expm1(y_test)

# =========================================================
# EVALUATION
# =========================================================

rmse = np.sqrt(
    mean_squared_error(
        actual_price,
        pred_price
    )
)

mae = mean_absolute_error(
    actual_price,
    pred_price
)

mape = (
    np.abs(
        (actual_price - pred_price)
        /
        actual_price.clip(lower=1)
    ).mean()
) * 100

# =========================================================
# RESULTS
# =========================================================

print("=" * 60)

print(f"FEATURE COUNT: {len(FEATURES)}")

print("=" * 60)

print(f"RMSE : {rmse:,.2f}")
print(f"MAE  : {mae:,.2f}")
print(f"MAPE : {mape:.2f}%")

print("=" * 60)

# =========================================================
# FEATURE IMPORTANCE
# =========================================================

feature_importance = pd.DataFrame({

    'feature': FEATURES,

    'importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='importance',
    ascending=False
)

display(
    feature_importance.head(10)
)

# =========================================================
# PREDICTION SAMPLE
# =========================================================

pred_df = test_df.copy()

pred_df['pred_price'] = pred_price
pred_df['actual_price'] = actual_price

pred_df['abs_error'] = (
    pred_df['actual_price']
    -
    pred_df['pred_price']
).abs()

pred_df['pct_abs_error'] = (
    pred_df['abs_error']/
    pred_df['actual_price']
).abs()

display_cols = [

    'shopId',
    'itemId',
    'modelId',

    'actual_price',
    'pred_price',

    'abs_error',
    'pct_abs_error'
]

display(
    pred_df[
        display_cols
    ].sort_values(
        by='abs_error',
        ascending=False
    ).head(5)
)

============================================================
FEATURE COUNT: 95
============================================================
RMSE : 1,170,620.94
MAE  : 237,091.23
MAPE : 0.32%
============================================================

                              feature  importance
37       item_price_last_scrape_log1p    0.447660
38             item_price_lag_2_log1p    0.249527
59      model_price_last_scrape_log1p    0.104069
39             item_has_price_history    0.081859
31                   item_has_history    0.046509
55         model_price_min_hist_log1p    0.020913
36  item_hist_observation_count_log1p    0.008583
33          item_price_min_hist_log1p    0.006746
32          item_avg_price_hist_log1p    0.005145
54         model_avg_price_hist_log1p    0.003942

,shopId,itemId,modelId,actual_price,pred_price,abs_error,pct_abs_error
51874,10055250,29423577723,223709159272,7.590000e+08,769079424.0,1.007942e+07,0.013280
51050,10055250,21361590976,59208605361,9.490000e+08,944573952.0,4.426048e+06,0.004664
149775,1002919413,26820461772,257553911837,1.779000e+08,175339216.0,2.560784e+06,0.014395
237647,1007168904,24823752002,217925190213,4.100000e+08,408031392.0,1.968608e+06,0.004801
151712,1002919413,28055404484,257553915393,1.779000e+08,177273808.0,6.261920e+05,0.003520

In [83]:
display(
    pred_df[
        display_cols
    ].sort_values(
        by='pct_abs_error',
        ascending=False
    ).head(5)
)

,shopId,itemId,modelId,actual_price,pred_price,abs_error,pct_abs_error
249829,1007174005,22961737666,252347204077,5000000.0,5523112.0,523112.0,0.104622
249803,1007174005,22961737666,252347204052,5000000.0,5426082.5,426082.5,0.085217
149775,1002919413,26820461772,257553911837,177900000.0,175339216.0,2560784.0,0.014395
51874,10055250,29423577723,223709159272,759000000.0,769079424.0,10079424.0,0.013280
251591,1007177881,29759494159,236711175080,64000000.0,63677708.0,322292.0,0.005036

In [84]:
clean_df.shape

(296807, 151)

In [85]:
remaining_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2803 entries, 301355 to 306223
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   capturedAt                2803 non-null   datetime64[ns]
 1   shopId                    2803 non-null   int64
 2   itemId                    2803 non-null   int64
 3   modelId                   2803 non-null   int64
 4   price                     2803 non-null   int64
 5   priceBeforeDiscount       2803 non-null   int64
 6   promotionId               2803 non-null   int64
 7   cat_id                    2803 non-null   int64
 8   stock                     28 non-null     float64
 9   normal_stock              28 non-null     float64
 10  raw_discount              2803 non-null   int64
 11  show_discount             2803 non-null   int64
 12  brand                     1121 non-null   object
 13  is_free_shipping          2803 non-null   object
 14  is_pre_order              2803 non-null   object
 15  item_price_min            2803 non-null   int64
 16  item_price_max            2803 non-null   int64
 17  review_rating             2803 non-null   float64
 18  total_rating_count        2803 non-null   int64
 19  cmt_count                 2803 non-null   int64
 20  shop_rating               2803 non-null   float64
 21  shop_response_rate        2803 non-null   float64
 22  shop_follower_count       2803 non-null   int64
 23  is_official_shop          2803 non-null   object
 24  is_verified               2803 non-null   object
 25  is_preferred_plus_seller  2803 non-null   object
 26  tag1                      2803 non-null   object
 27  date                      2803 non-null   object
 28  tag2                      2803 non-null   object
 29  day_of_week               2803 non-null   int32
 30  is_weekend                2803 non-null   int32
 31  month                     2803 non-null   int32
 32  day_of_year               2803 non-null   int32
 33  is_morning                2803 non-null   int32
 34  is_afternoon              2803 non-null   int32
 35  is_evening                2803 non-null   int32
dtypes: datetime64[ns](1), float64(5), int32(7), int64(14), object(9)
memory usage: 733.6+ KB

In [86]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 301496 to 304041
Data columns (total 40 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   capturedAt                  100 non-null    datetime64[ns]
 1   shopId                      100 non-null    int64
 2   itemId                      100 non-null    int64
 3   modelId                     100 non-null    int64
 4   price                       100 non-null    int64
 5   priceBeforeDiscount         100 non-null    int64
 6   promotionId                 100 non-null    int64
 7   cat_id                      100 non-null    int64
 8   stock                       3 non-null      float64
 9   normal_stock                3 non-null      float64
 10  raw_discount                100 non-null    int64
 11  show_discount               100 non-null    int64
 12  brand                       100 non-null    object
 13  is_free_shipping            100 non-null    object
 14  is_pre_order                100 non-null    object
 15  item_price_min              100 non-null    int64
 16  item_price_max              100 non-null    int64
 17  review_rating               100 non-null    float64
 18  total_rating_count          100 non-null    int64
 19  cmt_count                   100 non-null    int64
 20  shop_rating                 100 non-null    float64
 21  shop_response_rate          100 non-null    float64
 22  shop_follower_count         100 non-null    int64
 23  is_official_shop            100 non-null    object
 24  is_verified                 100 non-null    object
 25  is_preferred_plus_seller    100 non-null    object
 26  tag1                        100 non-null    object
 27  date                        100 non-null    object
 28  tag2                        100 non-null    object
 29  day_of_week                 100 non-null    int32
 30  is_weekend                  100 non-null    int32
 31  month                       100 non-null    int32
 32  day_of_year                 100 non-null    int32
 33  is_morning                  100 non-null    int32
 34  is_afternoon                100 non-null    int32
 35  is_evening                  100 non-null    int32
 36  stock_available             100 non-null    int32
 37  brand_missing               100 non-null    int32
 38  brand_freq                  100 non-null    int64
 39  shop_response_rate_missing  100 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(5), int32(9), int64(15), object(9)
memory usage: 27.8+ KB

In [87]:
remaining_df2 = remaining_df.copy()

# =========================================================
# KEEP ONLY ID COLUMNS
# SET ALL OTHER COLUMNS TO NaN
# =========================================================

keep_cols = [
    'capturedAt',
    'shopId',
    'itemId',
    'modelId',
    'tag1',
    'date',
    'tag2',
    'day_of_week',
    'is_weekend',
    'month',
    'day_of_year',
    'is_morning',
    'is_afternoon',
    'is_evening',

]

cols_to_blank = [
    col for col in remaining_df2.columns
    if col not in keep_cols
]

remaining_df2[cols_to_blank] = np.nan

In [88]:
remaining_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2803 entries, 301355 to 306223
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   capturedAt                2803 non-null   datetime64[ns]
 1   shopId                    2803 non-null   int64
 2   itemId                    2803 non-null   int64
 3   modelId                   2803 non-null   int64
 4   price                     0 non-null      float64
 5   priceBeforeDiscount       0 non-null      float64
 6   promotionId               0 non-null      float64
 7   cat_id                    0 non-null      float64
 8   stock                     0 non-null      float64
 9   normal_stock              0 non-null      float64
 10  raw_discount              0 non-null      float64
 11  show_discount             0 non-null      float64
 12  brand                     0 non-null      float64
 13  is_free_shipping          0 non-null      float64
 14  is_pre_order              0 non-null      float64
 15  item_price_min            0 non-null      float64
 16  item_price_max            0 non-null      float64
 17  review_rating             0 non-null      float64
 18  total_rating_count        0 non-null      float64
 19  cmt_count                 0 non-null      float64
 20  shop_rating               0 non-null      float64
 21  shop_response_rate        0 non-null      float64
 22  shop_follower_count       0 non-null      float64
 23  is_official_shop          0 non-null      float64
 24  is_verified               0 non-null      float64
 25  is_preferred_plus_seller  0 non-null      float64
 26  tag1                      2803 non-null   object
 27  date                      2803 non-null   object
 28  tag2                      2803 non-null   object
 29  day_of_week               2803 non-null   int32
 30  is_weekend                2803 non-null   int32
 31  month                     2803 non-null   int32
 32  day_of_year               2803 non-null   int32
 33  is_morning                2803 non-null   int32
 34  is_afternoon              2803 non-null   int32
 35  is_evening                2803 non-null   int32
dtypes: datetime64[ns](1), float64(22), int32(7), int64(3), object(3)
memory usage: 733.6+ KB

In [89]:
# =========================================================
# EXTEND remaining_df2 TO MATCH clean_df COLUMNS
# NEW COLUMNS WILL BE EMPTY (NaN)
# =========================================================

import numpy as np

# =========================================================
# TARGET COLUMN ORDER
# =========================================================

target_cols = clean_df.columns.tolist()

# =========================================================
# ADD MISSING COLUMNS AS NaN
# =========================================================

missing_cols = [
    col for col in target_cols
    if col not in remaining_df2.columns
]

for col in missing_cols:
    remaining_df2[col] = np.nan

# =========================================================
# REORDER COLUMNS TO MATCH clean_df
# =========================================================

remaining_df2 = remaining_df2[target_cols]

# =========================================================
# CHECK
# =========================================================

print("=" * 60)
print("COLUMN COUNT:", len(remaining_df2.columns))
print("=" * 60)

print(
    remaining_df2.columns.tolist()
)

============================================================
COLUMN COUNT: 151
============================================================
['capturedAt', 'shopId', 'itemId', 'modelId', 'price', 'priceBeforeDiscount', 'promotionId', 'cat_id', 'stock', 'normal_stock', 'raw_discount', 'show_discount', 'brand', 'is_free_shipping', 'is_pre_order', 'item_price_min', 'item_price_max', 'review_rating', 'total_rating_count', 'cmt_count', 'shop_rating', 'shop_response_rate', 'shop_follower_count', 'is_official_shop', 'is_verified', 'is_preferred_plus_seller', 'tag1', 'date', 'tag2', 'day_of_week', 'is_weekend', 'month', 'day_of_year', 'is_morning', 'is_afternoon', 'is_evening', 'stock_available', 'brand_missing', 'brand_freq', 'shop_response_rate_missing', 'model_price_last_scrape', 'model_price_lag_2', 'model_has_price_history', 'model_has_lag_2_history', 'model_days_since_last_scrape', 'model_has_time_history', 'item_avg_price_hist', 'item_avg_price_hist_available', 'item_price_min_hist', 'item_price_min_hist_available', 'item_price_max_hist', 'item_price_max_hist_available', 'item_price_volatility_hist', 'item_price_volatility_hist_available', 'item_hist_observation_count', 'item_has_history', 'model_prev_price_change', 'model_prev_price_change_available', 'model_prev_price_change_pct', 'model_prev_price_change_pct_available', 'model_prev_price_change_abs', 'model_price_direction', 'model_price_7d_avg_hist', 'model_price_7d_avg_hist_available', 'item_price_last_scrape', 'item_price_lag_2', 'item_has_price_history', 'item_has_lag_2_history', 'item_prev_price_change', 'item_prev_price_change_available', 'item_prev_price_change_pct', 'item_prev_price_change_pct_available', 'item_prev_price_change_abs', 'item_price_direction', 'model_avg_price_hist', 'model_avg_price_hist_available', 'model_price_min_hist', 'model_price_min_hist_available', 'model_price_max_hist', 'model_price_max_hist_available', 'model_price_volatility_hist', 'model_price_volatility_hist_available', 'model_hist_observation_count', 'model_has_history', 'model_price_position_hist', 'model_price_position_hist_available', 'model_price_above_hist_max', 'model_price_below_hist_min', 'item_price_position_hist', 'item_price_position_hist_available', 'item_price_above_hist_max', 'item_price_below_hist_min', 'model_price_trend_per_day', 'model_price_trend_per_day_available', 'model_price_trend_abs', 'model_price_trend_direction', 'item_days_since_last_scrape', 'item_has_time_history', 'item_days_since_first_seen', 'item_price_trend_per_day', 'item_price_trend_per_day_available', 'item_price_trend_abs', 'item_price_trend_direction', 'price_before_discount_available', 'is_on_sale', 'discount_amount', 'discount_depth', 'discount_depth_available', 'show_discount_available', 'effective_discount_pct', 'price_vs_item_hist_avg_pct', 'price_vs_item_hist_avg_pct_available', 'is_sharp_discount', 'shop_follower_count_available', 'shop_popularity', 'total_rating_count_available', 'item_popularity', 'review_rating_available', 'review_score_normalized', 'discount_x_popularity', 'discount_x_review_score', 'item_avg_price_hist_log1p', 'item_price_min_hist_log1p', 'item_price_max_hist_log1p', 'item_price_volatility_hist_log1p', 'model_avg_price_hist_log1p', 'model_price_min_hist_log1p', 'model_price_max_hist_log1p', 'model_price_volatility_hist_log1p', 'item_price_last_scrape_log1p', 'item_price_lag_2_log1p', 'model_price_last_scrape_log1p', 'model_price_lag_2_log1p', 'discount_amount_log1p', 'priceBeforeDiscount_log1p', 'item_hist_observation_count_log1p', 'model_hist_observation_count_log1p', 'item_days_since_first_seen_log1p', 'model_prev_price_change_signed_log1p', 'item_prev_price_change_signed_log1p', 'model_prev_price_change_pct_signed_log1p', 'item_prev_price_change_pct_signed_log1p', 'model_price_trend_per_day_signed_log1p', 'item_price_trend_per_day_signed_log1p', 'price_log1p', 'log_price', 'lower_bound', 'upper_bound', 'count', 'item_log_iqr_outlier', 'item_iqr_distance']

C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan

In [90]:
clean_df.shape

(296807, 151)

In [91]:
train_df.shape

(296710, 151)

In [92]:
remaining_df2.shape

(2803, 151)

In [93]:
# =========================================================
# SORT clean_df
# =========================================================

clean_df_sorted = clean_df.sort_values(
    'capturedAt'
)

# =========================================================
# MODEL-LEVEL LATEST LOOKUP
# =========================================================

model_lookup = (

    clean_df_sorted

    .groupby(
        ['shopId', 'itemId', 'modelId'],
        as_index=False
    )

    .last()
)

# =========================================================
# ITEM-LEVEL FALLBACK LOOKUP
# =========================================================

item_lookup = (

    clean_df_sorted

    .groupby(
        ['shopId', 'itemId'],
        as_index=False
    )

    .last()
)

# =========================================================
# EXCLUDE TARGET / ID COLS
# =========================================================

exclude_cols = [

    'capturedAt',
    'shopId',
    'itemId',
    'modelId',

    'price',
    'price_log1p',
    'log_price'
]

fill_cols = [
    col for col in remaining_df2.columns
    if col not in exclude_cols
]

# =========================================================
# START COPY
# =========================================================

filled_df = remaining_df2.copy()

# =========================================================
# FILL FEATURES
# PRIORITY:
# 1. exact modelId
# 2. fallback itemId
# =========================================================

for col in fill_cols:

    # -----------------------------------------------------
    # TEMP COL NAMES
    # -----------------------------------------------------

    model_temp_col = f"__model_{col}"

    item_temp_col = f"__item_{col}"

    # -----------------------------------------------------
    # MODEL LOOKUP
    # -----------------------------------------------------

    model_col = model_lookup[
        [
            'shopId',
            'itemId',
            'modelId',
            col
        ]
    ].rename(
        columns={
            col: model_temp_col
        }
    )

    filled_df = filled_df.merge(

        model_col,

        on=['shopId', 'itemId', 'modelId'],

        how='left'
    )

    # -----------------------------------------------------
    # ITEM LOOKUP
    # -----------------------------------------------------

    item_col = item_lookup[
        [
            'shopId',
            'itemId',
            col
        ]
    ].rename(
        columns={
            col: item_temp_col
        }
    )

    filled_df = filled_df.merge(

        item_col,

        on=['shopId', 'itemId'],

        how='left'
    )

    # -----------------------------------------------------
    # FILL PRIORITY
    # current -> model -> item
    # -----------------------------------------------------

    filled_df[col] = (

        filled_df[col]

        .fillna(
            filled_df[model_temp_col]
        )

        .fillna(
            filled_df[item_temp_col]
        )
    )

    # -----------------------------------------------------
    # DROP TEMP COLS
    # -----------------------------------------------------

    filled_df = filled_df.drop(
        columns=[
            model_temp_col,
            item_temp_col
        ]
    )

# =========================================================
# CHECK
# =========================================================

print("=" * 60)
print("Remaining NaNs")
print("=" * 60)

print(
    filled_df
    .isna()
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

C:\Users\purna\AppData\Local\Temp\ipykernel_25664\3348387990.py:149: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(

============================================================
Remaining NaNs
============================================================
price           2803
log_price       2803
price_log1p     2803
stock           2708
normal_stock    2708
dtype: int64

In [95]:
# =========================================================
# PREPARE FEATURES FOR INFERENCE
# =========================================================

X_infer = filled_df[FEATURES].copy()

# =========================================================
# PREDICT LOG PRICE
# =========================================================

pred_log = model.predict(X_infer)

# =========================================================
# CONVERT BACK TO ORIGINAL PRICE SCALE
# =========================================================

filled_df['predicted_price'] = np.expm1(
    pred_log
)

# =========================================================
# OPTIONAL ROUNDING
# =========================================================

filled_df['predicted_price'] = (
    filled_df['predicted_price']
    .round(0)
)

# =========================================================
# VIEW RESULTS
# =========================================================

display_cols = [

    'capturedAt',
    'shopId',
    'itemId',
    'modelId',

    'predicted_price'
]

display(
    filled_df[display_cols]
    .head(5)
)

# =========================================================
# SUMMARY
# =========================================================

print("=" * 60)

print(
    "Predicted rows:",
    len(filled_df)
)

print("=" * 60)

,capturedAt,shopId,itemId,modelId,predicted_price
0,2025-03-22 00:22:05.726,1009757562,28616508894,246950643806,26695820.0
1,2025-03-22 00:22:05.751,1009757562,27453603008,158705684479,14949626.0
2,2025-03-22 00:22:05.751,1009757562,27453603008,158705684478,14964803.0
3,2025-03-22 00:22:05.752,1009757562,27816883459,99039190766,19883916.0
4,2025-03-22 00:22:05.752,1009757562,27816883459,99039190765,19884412.0

============================================================
Predicted rows: 2803
============================================================

In [96]:
remaining_df.head(5)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,tag1,date,tag2,day_of_week,is_weekend,month,day_of_year,is_morning,is_afternoon,is_evening
301355,2025-03-22 00:22:05.726,1009757562,28616508894,246950643806,26800000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301356,2025-03-22 00:22:05.751,1009757562,27453603008,158705684479,15000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301357,2025-03-22 00:22:05.751,1009757562,27453603008,158705684478,15000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301358,2025-03-22 00:22:05.752,1009757562,27816883459,99039190766,19000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301359,2025-03-22 00:22:05.752,1009757562,27816883459,99039190765,19000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0

In [97]:
# =========================================================
# MERGE USING FULL UNIQUE KEY
# =========================================================

eval_df = filled_df.merge(

    remaining_df[
        [
            'capturedAt',
            'shopId',
            'itemId',
            'modelId',
            'price'
        ]
    ],

    on=[
        'capturedAt',
        'shopId',
        'itemId',
        'modelId'
    ],

    how='left',

    suffixes=('', '_actual')
)

# =========================================================
# CHECK DUPLICATION
# =========================================================

print("filled_df rows :", len(filled_df))
print("eval_df rows   :", len(eval_df))

# should be identical

# =========================================================
# ACTUAL VS PRED
# =========================================================

y_true = eval_df['price_actual']
y_pred = eval_df['predicted_price']

# =========================================================
# METRICS
# =========================================================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

import numpy as np

rmse = np.sqrt(
    mean_squared_error(y_true, y_pred)
)

mae = mean_absolute_error(
    y_true,
    y_pred
)

mape = (
    (
        np.abs(y_true - y_pred)
        /
        y_true.replace(0, np.nan)
    ).mean()
) * 100

# =========================================================
# PRINT
# =========================================================

print("=" * 60)

print(f"RMSE : {rmse:,.2f}")
print(f"MAE  : {mae:,.2f}")
print(f"MAPE : {mape:.2f}%")

print("=" * 60)

filled_df rows : 2803
eval_df rows   : 2803
============================================================
RMSE : 3,437,556.61
MAE  : 428,568.63
MAPE : 1.15%
============================================================

In [99]:
# =========================================================
# EXPORT eval_df TO CSV
# =========================================================

eval_df[['capturedAt','shopId','itemId','modelId','price_actual','predicted_price']].to_csv(
    'eval_df3.csv',
    index=False
)

print("Saved: eval_df2.csv")

Saved: eval_df2.csv

In [100]:
eval_df.shape

(2803, 153)

In [101]:
eval_df[eval_df['itemId'] == 23776838147][['itemId','modelId','price_actual','predicted_price','item_price_last_scrape']].head(20)

,itemId,modelId,price_actual,predicted_price,item_price_last_scrape
1198,23776838147,245295191746,29900000,29877148.0,29900000.0
1199,23776838147,204505904780,128000000,29880284.0,29900000.0
1200,23776838147,204505904784,39900000,39912844.0,39900000.0
1201,23776838147,204505904783,29900000,29870596.0,29900000.0
1202,23776838147,204505904782,29900000,29880284.0,29900000.0
1203,23776838147,204505904779,39900000,39919392.0,39900000.0
1204,23776838147,204505904781,29900000,29923228.0,29900000.0

In [102]:
clean_df[clean_df['itemId'] == 26966858330].head(5)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_prev_price_change_pct_signed_log1p,model_price_trend_per_day_signed_log1p,item_price_trend_per_day_signed_log1p,price_log1p,log_price,lower_bound,upper_bound,count,item_log_iqr_outlier,item_iqr_distance
206863,2025-02-02 14:59:56.322,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206864,2025-02-03 21:11:42.760,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206865,2025-02-05 03:08:00.096,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206866,2025-02-06 22:33:16.342,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206867,2025-02-08 01:25:29.386,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0

In [103]:
# =========================================================
# ANCHOR FEATURES
# =========================================================

X_anchor = test_df[FEATURES].copy()

# =========================================================
# PREDICT ANCHOR
# =========================================================

anchor_pred_log = model.predict(X_anchor)

test_df['anchor_pred_price'] = np.expm1(
    anchor_pred_log
)

In [104]:
# =========================================================
# ANCHOR RATIO
# =========================================================

test_df['anchor_ratio'] = (

    test_df['price']

    /

    test_df['anchor_pred_price']
)

# =========================================================
# GLOBAL DRIFT FACTOR
# =========================================================

drift_factor = (
    test_df['anchor_ratio']
    .median()
)

print("=" * 60)
print("DRIFT FACTOR:", drift_factor)
print("=" * 60)

============================================================
DRIFT FACTOR: 1.0001766101329999
============================================================

In [105]:
# =========================================================
# APPLY DRIFT CORRECTION
# =========================================================

filled_df['predicted_price_adjusted'] = (

    filled_df['predicted_price']

    * drift_factor
)

# optional rounding
filled_df['predicted_price_adjusted'] = (
    filled_df['predicted_price_adjusted']
    .round(0)
)

In [106]:
# =========================================================
# MERGE ACTUAL PRICES
# =========================================================

eval_df_adjusted = filled_df.merge(

    remaining_df[
        [
            'capturedAt',
            'shopId',
            'itemId',
            'modelId',
            'price'
        ]
    ],

    on=[
        'capturedAt',
        'shopId',
        'itemId',
        'modelId'
    ],

    how='left',

    suffixes=('', '_actual')
)

# =========================================================
# TRUE VS PRED
# =========================================================

y_true = eval_df_adjusted['price_actual']

y_pred = eval_df_adjusted[
    'predicted_price_adjusted'
]

# =========================================================
# METRICS
# =========================================================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

import numpy as np

rmse = np.sqrt(
    mean_squared_error(y_true, y_pred)
)

mae = mean_absolute_error(
    y_true,
    y_pred
)

mape = (
    np.abs(y_true - y_pred)
    /
    y_true.replace(0, np.nan)
).mean() * 100

# =========================================================
# PRINT RESULTS
# =========================================================

print("=" * 60)

print("ADJUSTED PREDICTION PERFORMANCE")

print("=" * 60)

print(f"RMSE : {rmse:,.2f}")
print(f"MAE  : {mae:,.2f}")
print(f"MAPE : {mape:.2f}%")

print("=" * 60)

============================================================
ADJUSTED PREDICTION PERFORMANCE
============================================================
RMSE : 3,436,940.89
MAE  : 428,404.43
MAPE : 1.15%
============================================================

In [107]:
# =========================================================
# CHECK ITEM IDs USED IN MULTIPLE SHOPS
# =========================================================

item_shop_counts = (

    clean_df

    .groupby('itemId')['shopId']
    .nunique()

    .reset_index(name='unique_shop_count')
)

# =========================================================
# ITEMS APPEARING IN MULTIPLE SHOPS
# =========================================================

multi_shop_items = item_shop_counts[
    item_shop_counts['unique_shop_count'] > 1
]

print("=" * 60)
print("ITEM IDs USED IN MULTIPLE SHOPS")
print("=" * 60)

print(f"Count: {len(multi_shop_items):,}")

# =========================================================
# VIEW EXAMPLES
# =========================================================

display(
    multi_shop_items
    .sort_values(
        'unique_shop_count',
        ascending=False
    )
    .head(20)
)

============================================================
ITEM IDs USED IN MULTIPLE SHOPS
============================================================
Count: 0

Empty DataFrame
Columns: [itemId, unique_shop_count]
Index: []

In [108]:
test__real_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25900 entries, 0 to 25899
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   capturedAt                25900 non-null  datetime64[ns]
 1   shopId                    25900 non-null  int64
 2   itemId                    25900 non-null  int64
 3   modelId                   25900 non-null  int64
 4   price                     300 non-null    float64
 5   priceBeforeDiscount       300 non-null    float64
 6   promotionId               300 non-null    float64
 7   cat_id                    300 non-null    float64
 8   stock                     7 non-null      float64
 9   normal_stock              7 non-null      float64
 10  raw_discount              300 non-null    float64
 11  show_discount             300 non-null    float64
 12  brand                     166 non-null    object
 13  is_free_shipping          300 non-null    object
 14  is_pre_order              300 non-null    object
 15  item_price_min            300 non-null    float64
 16  item_price_max            300 non-null    float64
 17  review_rating             300 non-null    float64
 18  total_rating_count        300 non-null    float64
 19  cmt_count                 300 non-null    float64
 20  shop_rating               300 non-null    float64
 21  shop_response_rate        300 non-null    float64
 22  shop_follower_count       300 non-null    float64
 23  is_official_shop          300 non-null    object
 24  is_verified               300 non-null    object
 25  is_preferred_plus_seller  300 non-null    object
 26  tag1                      25900 non-null  object
 27  tag2                      25900 non-null  object
 28  date                      25900 non-null  object
 29  day_of_week               25900 non-null  int32
 30  is_weekend                25900 non-null  int32
 31  month                     25900 non-null  int32
 32  day_of_year               25900 non-null  int32
 33  is_morning                25900 non-null  int32
 34  is_afternoon              25900 non-null  int32
 35  is_evening                25900 non-null  int32
dtypes: datetime64[ns](1), float64(16), int32(7), int64(3), object(9)
memory usage: 6.4+ MB

In [ ]:
# =========================================================
# MULTI-DAY INFERENCE PIPELINE
# WITH COLUMN EXPANSION
# =========================================================

import numpy as np
import pandas as pd

# =========================================================
# COPY
# =========================================================

infer_df = test__real_df.copy()

# =========================================================
# ADD ANCHOR FLAG
# =========================================================

infer_df['is_anchor'] = (
    infer_df['price'].notna()
).astype(int)

# =========================================================
# ADD ANCHOR FLAG TO CLEAN_DF
# =========================================================

clean_df['is_anchor'] = 0

# =========================================================
# ADD MISSING COLS TO infer_df
# =========================================================

for col in clean_df.columns:

    if col not in infer_df.columns:

        infer_df[col] = np.nan

# =========================================================
# MATCH EXACT COLUMN ORDER
# =========================================================

infer_df = infer_df[
    clean_df.columns
]

# =========================================================
# CONCAT
# =========================================================

combined_df = pd.concat(

    [
        clean_df,
        infer_df
    ],

    ignore_index=True
)

# =========================================================
# MARK FUTURE ROWS
# =========================================================

combined_df['is_future'] = 0

combined_df.loc[
    combined_df.index[-len(infer_df):],
    'is_future'
] = 1

# =========================================================
# SORT AGAIN
# =========================================================

combined_df = combined_df.sort_values(
    'capturedAt'
)

# =========================================================
# EXCLUDE NON-FILLABLE
# =========================================================

exclude_cols = [

    'capturedAt',

    'price',
    'price_log1p',
    'log_price',

    'tag1',
    'tag2',

    'is_anchor',
    'is_future'
]

fill_cols = [

    col for col in combined_df.columns
    if col not in exclude_cols
]

# =========================================================
# FORWARD FILL
# PRIORITY:
# 1. EXACT (shopId,itemId,modelId)
# =========================================================

combined_df[fill_cols] = (

    combined_df

    .groupby(
        ['shopId', 'itemId', 'modelId']
    )[fill_cols]

    .ffill()
)

# =========================================================
# FALLBACK:
# itemId
# =========================================================

combined_df[fill_cols] = (

    combined_df

    .groupby(
        ['itemId']
    )[fill_cols]

    .ffill()
)

# =========================================================
# EXTRACT FUTURE
# =========================================================

filled_future_df = combined_df[
    combined_df['is_future'] == 1
].copy()

# =========================================================
# FIX BOOLEAN STRING COLUMNS
# =========================================================

bool_cols = [

    'is_official_shop',
    'is_verified',
    'is_preferred_plus_seller',

    'is_free_shipping',
    'is_pre_order'
]

for col in bool_cols:

    filled_future_df[col] = (

        filled_future_df[col]

        .replace({
            't': 1,
            'f': 0,
            True: 1,
            False: 0
        })

        .fillna(0)

        .astype(np.int8)
    )


# =========================================================
# PREDICT
# =========================================================

X_future = filled_future_df[
    FEATURES
]

pred_log = model.predict(
    X_future
)

filled_future_df['predicted_price'] = np.expm1(
    pred_log
)

# =========================================================
# DAILY MARKET SHIFT
# =========================================================

anchor_df = filled_future_df[
    filled_future_df['is_anchor'] == 1
].copy()

anchor_df['shift_ratio'] = (

    anchor_df['price']
    /
    anchor_df['predicted_price']
)

# =========================================================
# DAILY SHIFT TABLE
# =========================================================

daily_shift = (

    anchor_df

    .groupby('date')['shift_ratio']

    .median()

    .reset_index()
)

daily_shift = daily_shift.rename(
    columns={
        'shift_ratio': 'daily_market_shift'
    }
)

# =========================================================
# MERGE SHIFT BACK
# =========================================================

filled_future_df = filled_future_df.merge(

    daily_shift,

    on='date',

    how='left'
)

# =========================================================
# DEFAULT SHIFT
# =========================================================

filled_future_df['daily_market_shift'] = (

    filled_future_df['daily_market_shift']

    .fillna(1.0)
)

# =========================================================
# ADJUSTED PRICE
# =========================================================

filled_future_df['predicted_price_adjusted'] = (

    filled_future_df['predicted_price']
    *
    filled_future_df['daily_market_shift']
)

# =========================================================
# KEEP TRUE ANCHOR PRICE
# =========================================================

filled_future_df.loc[
    filled_future_df['is_anchor'] == 1,
    'predicted_price_adjusted'
] = filled_future_df['price']

# =========================================================
# FINAL OUTPUT
# =========================================================

submission_df = filled_future_df[

    [
        'capturedAt',
        'shopId',
        'itemId',
        'modelId',

        'predicted_price_adjusted'
    ]

].copy()

submission_df = submission_df.rename(
    columns={
        'predicted_price_adjusted': 'predicted_price'
    }
)

# =========================================================
# CHECK
# =========================================================

print("=" * 60)
print("INFERENCE COMPLETE")
print("=" * 60)

print(f"Rows predicted: {len(submission_df):,}")

print("=" * 60)

display(
    submission_df.head()
)

C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['is_anchor'] = 0
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:65: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_df['is_future'] = 0
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_25664\2153198516.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({

============================================================
INFERENCE COMPLETE
============================================================
Rows predicted: 25,900
============================================================

,capturedAt,shopId,itemId,modelId,predicted_price
0,2025-03-22 04:27:05.325,1009757562,27904817781,241162534605,7.558387e+06
1,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,7.564105e+06
2,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,7.564105e+06
3,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,7.564105e+06
4,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,7.564105e+06

In [111]:
# =========================================================
# VIEW DAILY MARKET SHIFTS
# =========================================================

daily_shift_view = daily_shift.copy()

# optional:
daily_shift_view['pct_shift'] = (

    (daily_shift_view['daily_market_shift'] - 1)
    * 100
)

# =========================================================
# DISPLAY
# =========================================================

display(
    daily_shift_view.sort_values('date')
)

         date  daily_market_shift  pct_shift
0  2025-03-22            0.999863  -0.013699
1  2025-03-23            1.000008   0.000775
2  2025-03-24            0.999966  -0.003449

In [112]:
# =========================================================
# DAILY ANCHOR DIAGNOSTICS
# =========================================================

anchor_df['pct_error_before_adjustment'] = (

    (
        anchor_df['predicted_price']
        -
        anchor_df['price']
    ).abs()

    /

    anchor_df['price'].clip(lower=1)

) * 100

daily_anchor_diag = (

    anchor_df

    .groupby('date')

    .agg(

        anchor_count=(
            'price',
            'count'
        ),

        median_market_shift=(
            'shift_ratio',
            'median'
        ),

        mean_market_shift=(
            'shift_ratio',
            'mean'
        ),

        mean_anchor_mape=(
            'pct_error_before_adjustment',
            'mean'
        )
    )

    .reset_index()
)

display(
    daily_anchor_diag
)

,date,anchor_count,median_market_shift,mean_market_shift,mean_anchor_mape
0,2025-03-22,100,0.999863,1.002092,1.192806
1,2025-03-23,100,1.000008,1.026622,1.114418
2,2025-03-24,100,0.999966,1.007983,0.937544

In [113]:
model.save_model(
    'xgboost_global_model.json'
)

In [114]:
submission_df = filled_future_df.copy()

submission_df['final_price'] = np.where(

    submission_df['is_anchor'] == 1,

    submission_df['price'],  # actual known anchor

    submission_df['predicted_price_adjusted']  # inferred
)

In [115]:
submission_df.to_csv(
    'final_submission_approach_1.csv',
    index=False
)