Importing necessary libraries and fixing random seed

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8')
sns.set_context('talk')
RANDOM_SEED = 42

Importing TRAIN data

In [2]:
data_path = 'ecommerce_price_prediction-train.csv'
df = pd.read_csv(data_path, parse_dates=['capturedAt'], low_memory=False)
print(f'Read {len(df):,} rows and {df.shape[1]} columns from {data_path}')
df.tail()

Read 306,226 rows and 26 columns from ecommerce_price_prediction-train.csv

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
306221,2025-03-22 04:27:05.302,1009757562,26058443824,246415388990,16500000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306222,2025-03-22 04:27:05.302,1009757562,26058443824,207734010381,15900000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306223,2025-03-22 04:27:05.302,1009757562,26058443824,207734010380,29100000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306224,2025-03-22 04:27:05.302,1009757562,26058443824,207734010380,29100000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f
306225,2025-03-22 04:27:05.302,1009757562,26058443824,246415388993,28400000,0,0,100001,NaN,NaN,...,38500000,4.972816,515,473,4.973416,96.0,3927,f,f,f

Adding TRAIN tag to the train dataset so that it wont get mixed later

In [3]:
df['tag1']='TRAIN'

In [4]:
df.shape

(306226, 27)

In [5]:
df.duplicated().sum()

2244

In [6]:
duplicate_rows = df[
    df.duplicated(keep=False)
]

duplicate_rows.head(5)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller,tag1
3722,2025-01-06 08:00:19.394,1000050896,19691496580,186929387166,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,50.0,1,f,f,f,TRAIN
3723,2025-01-06 08:00:19.394,1000050896,19691496580,186929387166,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,50.0,1,f,f,f,TRAIN
10658,2025-02-02 01:05:09.437,1000050896,21791490000,148309242735,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,57.0,1,f,f,f,TRAIN
10659,2025-02-02 01:05:09.437,1000050896,21791490000,148309242735,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,57.0,1,f,f,f,TRAIN
10681,2025-02-02 01:05:10.221,1000050896,19691496580,186929387166,1100000,0,0,100630,NaN,NaN,...,5.0,1,1,5.0,57.0,1,f,f,f,TRAIN

In [7]:
df = df.drop_duplicates()

In [8]:
df.shape

(303982, 27)

Importing TEST data

In [9]:
test_data_path = 'ecommerce_price_prediction-test-3-days.csv'
test__real_df = pd.read_csv(test_data_path, parse_dates=['capturedAt'], low_memory=False)
print(f'Read {len(test__real_df):,} rows and {test__real_df.shape[1]} columns from {test_data_path}')
test__real_df.head()

Read 25,900 rows and 26 columns from ecommerce_price_prediction-test-3-days.csv

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
0,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-03-22 04:27:05.325,1009757562,27904817781,241162534604,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Adding TEST tag so that it wont get mixed with train data

In [10]:
test__real_df['tag1']='TEST'
test__real_df.shape

(25900, 27)

Checking TRAIN data info

In [11]:
print('Shape:', df.shape)
print('\nColumns:')
print(df.columns.tolist())

df.info()

Shape: (303982, 27)

Columns:
['capturedAt', 'shopId', 'itemId', 'modelId', 'price', 'priceBeforeDiscount', 'promotionId', 'cat_id', 'stock', 'normal_stock', 'raw_discount', 'show_discount', 'brand', 'is_free_shipping', 'is_pre_order', 'item_price_min', 'item_price_max', 'review_rating', 'total_rating_count', 'cmt_count', 'shop_rating', 'shop_response_rate', 'shop_follower_count', 'is_official_shop', 'is_verified', 'is_preferred_plus_seller', 'tag1']
<class 'pandas.core.frame.DataFrame'>
Index: 303982 entries, 0 to 306223
Data columns (total 27 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   capturedAt                303982 non-null  datetime64[ns]
 1   shopId                    303982 non-null  int64
 2   itemId                    303982 non-null  int64
 3   modelId                   303982 non-null  int64
 4   price                     303982 non-null  int64
 5   priceBeforeDiscount       303982 non-null  int64
 6   promotionId               303982 non-null  int64
 7   cat_id                    303982 non-null  int64
 8   stock                     3728 non-null    float64
 9   normal_stock              3728 non-null    float64
 10  raw_discount              303982 non-null  int64
 11  show_discount             303982 non-null  int64
 12  brand                     199832 non-null  object
 13  is_free_shipping          303982 non-null  object
 14  is_pre_order              303982 non-null  object
 15  item_price_min            303982 non-null  int64
 16  item_price_max            303982 non-null  int64
 17  review_rating             303982 non-null  float64
 18  total_rating_count        303982 non-null  int64
 19  cmt_count                 303982 non-null  int64
 20  shop_rating               303982 non-null  float64
 21  shop_response_rate        302783 non-null  float64
 22  shop_follower_count       303982 non-null  int64
 23  is_official_shop          303982 non-null  object
 24  is_verified               303982 non-null  object
 25  is_preferred_plus_seller  303982 non-null  object
 26  tag1                      303982 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(14), object(7)
memory usage: 64.9+ MB

Checking TRAIN data missing numbers

In [12]:
missing_report = df.isna().sum().to_frame('missing_count')
missing_report['missing_pct'] = 100 * missing_report['missing_count'] / len(df)
missing_report.sort_values(by='missing_pct', ascending=False).head(20)

                          missing_count  missing_pct
stock                            300254    98.773612
normal_stock                     300254    98.773612
brand                            104150    34.261897
shop_response_rate                 1199     0.394431
capturedAt                            0     0.000000
item_price_min                        0     0.000000
is_preferred_plus_seller              0     0.000000
is_verified                           0     0.000000
is_official_shop                      0     0.000000
shop_follower_count                   0     0.000000
shop_rating                           0     0.000000
cmt_count                             0     0.000000
total_rating_count                    0     0.000000
review_rating                         0     0.000000
item_price_max                        0     0.000000
is_free_shipping                      0     0.000000
is_pre_order                          0     0.000000
shopId                                0     0.000000
show_discount                         0     0.000000
raw_discount                          0     0.000000

Checking TEST data info

In [13]:
print('Shape:', test__real_df.shape)
print('\nColumns:')
print(test__real_df.columns.tolist())

test__real_df.info()

Shape: (25900, 27)

Columns:
['capturedAt', 'shopId', 'itemId', 'modelId', 'price', 'priceBeforeDiscount', 'promotionId', 'cat_id', 'stock', 'normal_stock', 'raw_discount', 'show_discount', 'brand', 'is_free_shipping', 'is_pre_order', 'item_price_min', 'item_price_max', 'review_rating', 'total_rating_count', 'cmt_count', 'shop_rating', 'shop_response_rate', 'shop_follower_count', 'is_official_shop', 'is_verified', 'is_preferred_plus_seller', 'tag1']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25900 entries, 0 to 25899
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   capturedAt                25900 non-null  datetime64[ns]
 1   shopId                    25900 non-null  int64
 2   itemId                    25900 non-null  int64
 3   modelId                   25900 non-null  int64
 4   price                     300 non-null    float64
 5   priceBeforeDiscount       300 non-null    float64
 6   promotionId               300 non-null    float64
 7   cat_id                    300 non-null    float64
 8   stock                     7 non-null      float64
 9   normal_stock              7 non-null      float64
 10  raw_discount              300 non-null    float64
 11  show_discount             300 non-null    float64
 12  brand                     166 non-null    object
 13  is_free_shipping          300 non-null    object
 14  is_pre_order              300 non-null    object
 15  item_price_min            300 non-null    float64
 16  item_price_max            300 non-null    float64
 17  review_rating             300 non-null    float64
 18  total_rating_count        300 non-null    float64
 19  cmt_count                 300 non-null    float64
 20  shop_rating               300 non-null    float64
 21  shop_response_rate        300 non-null    float64
 22  shop_follower_count       300 non-null    float64
 23  is_official_shop          300 non-null    object
 24  is_verified               300 non-null    object
 25  is_preferred_plus_seller  300 non-null    object
 26  tag1                      25900 non-null  object
dtypes: datetime64[ns](1), float64(16), int64(3), object(7)
memory usage: 5.3+ MB

Adding ANCHOR tag

In [14]:
test__real_df['tag2'] = np.where(
    test__real_df['price'].notna(),
    'ANCHOR',
    'NOT-ANCHOR'
)

Adding date column to both TRAIN and TEST

In [15]:
df['date'] = df['capturedAt'].dt.date
test__real_df['date'] = test__real_df['capturedAt'].dt.date

Isolating validation set from train

In [16]:
last_date = df['date'].max()
print(f"Last date in dataset: {last_date}")

# Isolate all data from the last date as validation set
validation_df = df[df['date'] == last_date].copy()
train_df = df[df['date'] < last_date].copy()

print(f"Training set: {len(train_df):,} rows")
print(f"Validation set: {len(validation_df):,} rows")
print(f"Validation set date: {validation_df['date'].unique()}")

# Verify no overlap
assert len(set(train_df['date']) & set(validation_df['date'])) == 0, "Training and validation sets have overlapping dates"
print("✓ No date overlap between training and validation sets")

Last date in dataset: 2025-03-22
Training set: 301,079 rows
Validation set: 2,903 rows
Validation set date: [datetime.date(2025, 3, 22)]
✓ No date overlap between training and validation sets

Adding second tags to really distinguish the final train and validation set

In [17]:
train_df['tag2']= 'TRAIN'
validation_df['tag2']= 'VALIDATION'

In [18]:
train_df.shape

(301079, 29)

In [19]:
validation_df.shape

(2903, 29)

In [20]:
test__real_df.shape

(25900, 29)

Adding date columns

In [21]:
def build_standard_time_features(df):
    df = df.copy()
    df['day_of_week'] = df['capturedAt'].dt.dayofweek
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    df['month'] = df['capturedAt'].dt.month
    df['day_of_year'] = df['capturedAt'].dt.dayofyear
    hour = df['capturedAt'].dt.hour
    df['is_morning'] = ((hour >= 6) & (hour < 12)).astype(int)
    df['is_afternoon'] = ((hour >= 12) & (hour < 18)).astype(int)
    df['is_evening'] = ((hour >= 18) & (hour < 24)).astype(int)
    return df

In [22]:
train_df = build_standard_time_features(train_df)
validation_df = build_standard_time_features(validation_df)
test__real_df = build_standard_time_features(test__real_df)

In [23]:
train_df.shape

(301079, 36)

In [24]:
test__real_df.shape

(25900, 36)

In [25]:
validation_df.shape

(2903, 36)

Adding tags for missing stock and brand

In [26]:
train_df['stock_available'] = train_df['stock'].notna().astype(int)

train_df['brand_missing'] = train_df['brand'].isna().astype(int)

In [27]:
train_df.shape

(301079, 38)

Frequency encoding for brand

In [28]:
train_df['brand'] = train_df['brand'].fillna('unknown')
brand_counts = train_df['brand'].value_counts()

train_df['brand_freq'] = train_df['brand'].map(brand_counts)

In [29]:
train_df.shape

(301079, 39)

Check for missing values in shop_response_rate

In [30]:
# =========================================================
# CHECK WHETHER MISSING shop_response_rate
# IS CONCENTRATED IN SPECIFIC SHOPS
# =========================================================

response_df = train_df.copy()

# missing flag
response_df['shop_response_rate_missing'] = (
    response_df['shop_response_rate'].isna()
)

# =========================================================
# COUNT MISSING PER SHOP
# =========================================================

missing_by_shop = (
    response_df.groupby('shopId')['shop_response_rate_missing']
    .agg(['sum', 'count', 'mean','median'])
    .rename(columns={
        'sum': 'missing_count',
        'count': 'total_rows',
        'mean': 'mean_non_missing',
        'median': 'median_non_missing'  
    })
)

# missing percentage per shop
missing_by_shop['missing_pct'] = (
    missing_by_shop['missing_count']
    / missing_by_shop['total_rows']
)


# =========================================================
# SORT BY HIGHEST MISSING COUNT
# =========================================================

missing_by_shop_sorted = (
    missing_by_shop
    .sort_values(
        by='missing_count',
        ascending=False
    )
)

print(missing_by_shop_sorted.head(20))

            missing_count  total_rows  mean_non_missing  median_non_missing  \
shopId
1007291976           1120        2676          0.418535                 0.0
10044886               40         432          0.092593                 0.0
10046782               16         180          0.088889                 0.0
10016846               12          43          0.279070                 0.0
100251397              10         168          0.059524                 0.0
1005306332              1          64          0.015625                 0.0
1002675141              0         710          0.000000                 0.0
1002883376              0          61          0.000000                 0.0
1002919413              0        2818          0.000000                 0.0
1002936943              0         240          0.000000                 0.0
1002964923              0          41          0.000000                 0.0
1003032082              0          69          0.000000                 0.0
1003061908              0          80          0.000000                 0.0
1003095770              0         596          0.000000                 0.0
1003145950              0        1730          0.000000                 0.0
1003181772              0          20          0.000000                 0.0
1003240246              0          38          0.000000                 0.0
1003473490              0        3540          0.000000                 0.0
1003530925              0         258          0.000000                 0.0
1003613948              0         670          0.000000                 0.0

            missing_pct
shopId
1007291976     0.418535
10044886       0.092593
10046782       0.088889
10016846       0.279070
100251397      0.059524
1005306332     0.015625
1002675141     0.000000
1002883376     0.000000
1002919413     0.000000
1002936943     0.000000
1002964923     0.000000
1003032082     0.000000
1003061908     0.000000
1003095770     0.000000
1003145950     0.000000
1003181772     0.000000
1003240246     0.000000
1003473490     0.000000
1003530925     0.000000
1003613948     0.000000

In [31]:
train_df['shop_response_rate'].describe()

count    299880.000000
mean         78.166910
std          16.472561
min           9.000000
25%          66.000000
50%          82.000000
75%          92.000000
max         100.000000
Name: shop_response_rate, dtype: float64

In [32]:
train_df[train_df['shopId'] == 1007291976]['shop_response_rate'].describe()

count    1556.00000
mean       29.12982
std        17.01117
min        15.00000
25%        15.00000
50%        17.00000
75%        50.00000
max        57.00000
Name: shop_response_rate, dtype: float64

Response rate is mostly empty in one shop only, imputting with median as solution

In [33]:
# =========================================================
# GLOBAL MEDIAN (FALLBACK)
# =========================================================

global_median_response_rate = (
    train_df['shop_response_rate']
    .median()
)

# =========================================================
# SHOP-LEVEL MEDIAN
# =========================================================

shop_median_response_rate = (

    train_df
    .groupby('shopId')['shop_response_rate']
    .median()
)

# =========================================================
# MAP SHOP MEDIAN
# =========================================================

train_df['shop_response_rate_shop_median'] = (
    train_df['shopId']
    .map(shop_median_response_rate)
)

# =========================================================
# FILL MISSING
# 1. shop median
# 2. fallback global median
# =========================================================

train_df['shop_response_rate'] = (

    train_df['shop_response_rate']

    .fillna(
        train_df['shop_response_rate_shop_median']
    )

    .fillna(global_median_response_rate)
)

# =========================================================
# OPTIONAL CLEANUP
# =========================================================

train_df = train_df.drop(
    columns=['shop_response_rate_shop_median']
)

In [34]:
train_df.shape

(301079, 39)

In [35]:
# missing flag
train_df['shop_response_rate_missing'] = (
    train_df['shop_response_rate'].isna()
)

Due to the nature of the problem, we will need to isolate 100 random data set from validation to mimic the anchor set

In [36]:
# =========================================================
# SAMPLE 100 ANCHOR ROWS
# =========================================================

sample_df = validation_df.sample(
    n=100,
    random_state=42
)

# =========================================================
# REMAINING ROWS (NOT IN SAMPLE)
# =========================================================

remaining_df = validation_df.drop(
    sample_df.index
).copy()

# =========================================================
# CHECK
# =========================================================

print("Validation rows :", len(validation_df))
print("Sample rows     :", len(sample_df))
print("Remaining rows  :", len(remaining_df))
print("Total check     :", len(sample_df) + len(remaining_df))

Validation rows : 2903
Sample rows     : 100
Remaining rows  : 2803
Total check     : 2903

In [37]:
sample_df.shape

(100, 36)

In [38]:
train_df.shape

(301079, 40)

Adding brand missing tags, stock_missing tag, shop_response_missing tag, imputting brand_freq and missing shop_response_rate from training data

In [39]:
sample_df['stock_available'] = sample_df['stock'].notna().astype(int)

sample_df['brand_missing'] = sample_df['brand'].isna().astype(int)

In [40]:

sample_df['brand'] = sample_df['brand'].fillna('unknown')

sample_df['brand_freq'] = (
    sample_df['brand']
    .map(brand_counts)
    .fillna(0)
)

# =========================================================
# MAP SHOP-LEVEL MEDIAN FROM TRAIN
# =========================================================

sample_df['shop_response_rate_shop_median'] = (
    sample_df['shopId']
    .map(shop_median_response_rate)
)

# =========================================================
# IMPUTE
# 1. shop median
# 2. global median fallback
# =========================================================

sample_df['shop_response_rate'] = (

    sample_df['shop_response_rate']

    .fillna(
        sample_df['shop_response_rate_shop_median']
    )

    .fillna(global_median_response_rate)
)

# =========================================================
# OPTIONAL CLEANUP
# =========================================================

sample_df = sample_df.drop(
    columns=['shop_response_rate_shop_median']
)

In [41]:
sample_df.shape

(100, 39)

In [42]:
# missing flag
sample_df['shop_response_rate_missing'] = (
    sample_df['shop_response_rate'].isna()
)

Combining train and sample because the derivative features need to read from previous days

In [43]:
import numpy as np
import pandas as pd

# =========================================================
# COMBINE TRAIN + sample
# =========================================================

full_df = pd.concat([train_df, sample_df], axis=0)

# preserve indices
train_idx = train_df.index
sample_idx = sample_df.index

In [44]:
full_df.shape

(301179, 40)

In [45]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 301179 entries, 0 to 304041
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   capturedAt                  301179 non-null  datetime64[ns]
 1   shopId                      301179 non-null  int64
 2   itemId                      301179 non-null  int64
 3   modelId                     301179 non-null  int64
 4   price                       301179 non-null  int64
 5   priceBeforeDiscount         301179 non-null  int64
 6   promotionId                 301179 non-null  int64
 7   cat_id                      301179 non-null  int64
 8   stock                       3700 non-null    float64
 9   normal_stock                3700 non-null    float64
 10  raw_discount                301179 non-null  int64
 11  show_discount               301179 non-null  int64
 12  brand                       301179 non-null  object
 13  is_free_shipping            301179 non-null  object
 14  is_pre_order                301179 non-null  object
 15  item_price_min              301179 non-null  int64
 16  item_price_max              301179 non-null  int64
 17  review_rating               301179 non-null  float64
 18  total_rating_count          301179 non-null  int64
 19  cmt_count                   301179 non-null  int64
 20  shop_rating                 301179 non-null  float64
 21  shop_response_rate          301179 non-null  float64
 22  shop_follower_count         301179 non-null  int64
 23  is_official_shop            301179 non-null  object
 24  is_verified                 301179 non-null  object
 25  is_preferred_plus_seller    301179 non-null  object
 26  tag1                        301179 non-null  object
 27  date                        301179 non-null  object
 28  tag2                        301179 non-null  object
 29  day_of_week                 301179 non-null  int32
 30  is_weekend                  301179 non-null  int32
 31  month                       301179 non-null  int32
 32  day_of_year                 301179 non-null  int32
 33  is_morning                  301179 non-null  int32
 34  is_afternoon                301179 non-null  int32
 35  is_evening                  301179 non-null  int32
 36  stock_available             301179 non-null  int32
 37  brand_missing               301179 non-null  int32
 38  brand_freq                  301179 non-null  int64
 39  shop_response_rate_missing  301179 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(5), int32(9), int64(15), object(9)
memory usage: 81.9+ MB

In [46]:
# =========================================================
# SORT CHRONOLOGICALLY
# VERY IMPORTANT
# =========================================================

full_df = full_df.sort_values(
    ['shopId', 'itemId', 'modelId', 'capturedAt']
)

# =========================================================
# GROUPS
# =========================================================

# fine-grained
model_group = full_df.groupby(
    ['shopId', 'itemId', 'modelId']
)

# broader fallback
item_group = full_df.groupby(
    ['shopId', 'itemId']
)

In [47]:
# =========================================================
# MODEL-LEVEL SAFE LAG FEATURES
# =========================================================

# ---------------------------------------------------------
# PREVIOUS PRICES
# ---------------------------------------------------------

full_df['model_price_last_scrape'] = (
    model_group['price'].shift(1)
)

full_df['model_price_lag_2'] = (
    model_group['price'].shift(2)
)

# ---------------------------------------------------------
# HISTORY INDICATORS
# VERY IMPORTANT
# ---------------------------------------------------------

# has at least 1 previous observation
full_df['model_has_price_history'] = (
    full_df['model_price_last_scrape']
    .notna()
    .astype(int)
)

# has at least 2 previous observations
full_df['model_has_lag_2_history'] = (
    full_df['model_price_lag_2']
    .notna()
    .astype(int)
)

# ---------------------------------------------------------
# SAFE FILLING
# ---------------------------------------------------------

# fill AFTER creating indicators
full_df['model_price_last_scrape'] = (
    full_df['model_price_last_scrape']
    .fillna(0)
)

full_df['model_price_lag_2'] = (
    full_df['model_price_lag_2']
    .fillna(0)
)

# =========================================================
# TIME FEATURES
# =========================================================

full_df['model_days_since_last_scrape'] = (
    full_df['capturedAt']
    - model_group['capturedAt'].shift(1)
).dt.days

# ---------------------------------------------------------
# HISTORY INDICATOR
# ---------------------------------------------------------

full_df['model_has_time_history'] = (
    full_df['model_days_since_last_scrape']
    .notna()
    .astype(int)
)

# ---------------------------------------------------------
# SAFE FILLING
# ---------------------------------------------------------

full_df['model_days_since_last_scrape'] = (
    full_df['model_days_since_last_scrape']
    .fillna(0)
    .astype(int)
)

In [48]:
# =========================================================
# ITEM-LEVEL EXPANDING FEATURES (LEAKAGE SAFE)
# =========================================================

# item grouping
item_group = full_df.groupby(['shopId', 'itemId'])

# =========================================================
# HISTORICAL AVERAGE PRICE
# =========================================================

full_df['item_avg_price_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().mean()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_avg_price_hist_available'] = (
    full_df['item_avg_price_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_avg_price_hist'] = (
    full_df['item_avg_price_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MIN PRICE
# =========================================================

full_df['item_price_min_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().min()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_price_min_hist_available'] = (
    full_df['item_price_min_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_price_min_hist'] = (
    full_df['item_price_min_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MAX PRICE
# =========================================================

full_df['item_price_max_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().max()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_price_max_hist_available'] = (
    full_df['item_price_max_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_price_max_hist'] = (
    full_df['item_price_max_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL VOLATILITY
# =========================================================

full_df['item_price_volatility_hist'] = (
    item_group['price']
    .apply(
        lambda x: x.shift(1).expanding().std()
    )
    .reset_index(level=[0,1], drop=True)
)

# availability flag
full_df['item_price_volatility_hist_available'] = (
    full_df['item_price_volatility_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['item_price_volatility_hist'] = (
    full_df['item_price_volatility_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# HISTORICAL OBSERVATION COUNT
# VERY USEFUL FEATURE
# =========================================================

full_df['item_hist_observation_count'] = (
    item_group.cumcount()
)

# =========================================================
# OPTIONAL:
# HAS ANY HISTORY
# =========================================================

full_df['item_has_history'] = (
    full_df['item_hist_observation_count'] > 0
).astype(int)

In [49]:
# =========================================================
# MODEL-LEVEL PRICE CHANGE FEATURES (PROPER + SAFE)
# =========================================================

# ---------------------------------------------------------
# PREVIOUS PRICE CHANGE
# ---------------------------------------------------------

full_df['model_prev_price_change'] = (
    full_df['model_price_last_scrape']
    - full_df['model_price_lag_2']
)

# =========================================================
# AVAILABILITY FLAG
# need BOTH lag1 and lag2 to exist
# =========================================================

full_df['model_prev_price_change_available'] = (
    (
        full_df['model_has_price_history'] == 1
    )
    &
    (
        full_df['model_has_lag_2_history'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# first/second occurrences have no meaningful change
# =========================================================

full_df['model_prev_price_change'] = (
    full_df['model_prev_price_change']
    .fillna(0)
)

# =========================================================
# PERCENTAGE CHANGE
# =========================================================

full_df['model_prev_price_change_pct'] = np.where(
    full_df['model_has_lag_2_history'] == 1,
    (
        full_df['model_prev_price_change']
        /
        full_df['model_price_lag_2'].replace(0, 1)
    ) * 100,
    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['model_prev_price_change_pct_available'] = (
    full_df['model_prev_price_change_pct']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['model_prev_price_change_pct'] = (
    full_df['model_prev_price_change_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE CHANGE MAGNITUDE
# often very useful for tree models
# =========================================================

full_df['model_prev_price_change_abs'] = (
    full_df['model_prev_price_change']
    .abs()
)

# =========================================================
# OPTIONAL:
# PRICE DIRECTION
# =========================================================

full_df['model_price_direction'] = np.sign(
    full_df['model_prev_price_change']
)

# values:
# -1 = price decreased
#  0 = unchanged/no history
# +1 = price increased

In [50]:
full_df.shape

(301179, 62)

In [51]:
# =========================================================
# MODEL-LEVEL ROLLING FEATURES (LEAKAGE SAFE)
# =========================================================

# model grouping
model_group = full_df.groupby(
    ['shopId', 'itemId', 'modelId']
)

# =========================================================
# ROLLING 7-OBSERVATION AVERAGE
# =========================================================

full_df['model_price_7d_avg_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).rolling(
            window=7,
            min_periods=1
        ).mean()
    )
    .reset_index(level=[0,1,2], drop=True)
)

# availability flag
full_df['model_price_7d_avg_hist_available'] = (
    full_df['model_price_7d_avg_hist']
    .notna()
    .astype(int)
)

# safe fill
full_df['model_price_7d_avg_hist'] = (
    full_df['model_price_7d_avg_hist']
    .fillna(0)
)

# ===========

In [52]:
full_df.shape

(301179, 64)

In [53]:
# =========================================================
# ITEM-LEVEL LAG FEATURES
# =========================================================

item_group = full_df.groupby(['shopId', 'itemId'])

# ---------------------------------------------------------
# LAGS
# ---------------------------------------------------------

full_df['item_price_last_scrape'] = (
    item_group['price'].shift(1)
)

full_df['item_price_lag_2'] = (
    item_group['price'].shift(2)
)

# =========================================================
# HISTORY FLAGS
# =========================================================

full_df['item_has_price_history'] = (
    full_df['item_price_last_scrape']
    .notna()
    .astype(int)
)

full_df['item_has_lag_2_history'] = (
    full_df['item_price_lag_2']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_price_last_scrape'] = (
    full_df['item_price_last_scrape']
    .fillna(0)
)

full_df['item_price_lag_2'] = (
    full_df['item_price_lag_2']
    .fillna(0)
)

In [54]:
full_df.shape

(301179, 68)

In [55]:
# =========================================================
# ITEM-LEVEL PRICE CHANGE FEATURES (PROPER + SAFE)
# =========================================================

# ---------------------------------------------------------
# PREVIOUS PRICE CHANGE
# ---------------------------------------------------------

full_df['item_prev_price_change'] = (
    full_df['item_price_last_scrape']
    - full_df['item_price_lag_2']
)

# =========================================================
# AVAILABILITY FLAG
# need BOTH lag1 and lag2 to exist
# =========================================================

full_df['item_prev_price_change_available'] = (
    (
        full_df['item_has_price_history'] == 1
    )
    &
    (
        full_df['item_has_lag_2_history'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_prev_price_change'] = (
    full_df['item_prev_price_change']
    .fillna(0)
)

# =========================================================
# PERCENTAGE CHANGE
# =========================================================

full_df['item_prev_price_change_pct'] = np.where(
    full_df['item_has_lag_2_history'] == 1,
    (
        full_df['item_prev_price_change']
        /
        full_df['item_price_lag_2'].replace(0, 1)
    ) * 100,
    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['item_prev_price_change_pct_available'] = (
    full_df['item_prev_price_change_pct']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_prev_price_change_pct'] = (
    full_df['item_prev_price_change_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE CHANGE MAGNITUDE
# =========================================================

full_df['item_prev_price_change_abs'] = (
    full_df['item_prev_price_change']
    .abs()
)

# =========================================================
# OPTIONAL:
# PRICE DIRECTION
# =========================================================

full_df['item_price_direction'] = np.sign(
    full_df['item_prev_price_change']
)

# values:
# -1 = price decreased
#  0 = unchanged/no history
# +1 = price increased

In [56]:
# =========================================================
# MODEL-LEVEL EXPANDING FEATURES (SAFE)
# =========================================================

model_group = full_df.groupby(
    ['shopId', 'itemId', 'modelId']
)

# =========================================================
# HISTORICAL AVG PRICE
# =========================================================

full_df['model_avg_price_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().mean()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_avg_price_hist_available'] = (
    full_df['model_avg_price_hist']
    .notna()
    .astype(int)
)

full_df['model_avg_price_hist'] = (
    full_df['model_avg_price_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MIN PRICE
# =========================================================

full_df['model_price_min_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().min()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_price_min_hist_available'] = (
    full_df['model_price_min_hist']
    .notna()
    .astype(int)
)

full_df['model_price_min_hist'] = (
    full_df['model_price_min_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL MAX PRICE
# =========================================================

full_df['model_price_max_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().max()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_price_max_hist_available'] = (
    full_df['model_price_max_hist']
    .notna()
    .astype(int)
)

full_df['model_price_max_hist'] = (
    full_df['model_price_max_hist']
    .fillna(0)
)

# =========================================================
# HISTORICAL VOLATILITY
# =========================================================

full_df['model_price_volatility_hist'] = (
    model_group['price']
    .apply(
        lambda x: x.shift(1).expanding().std()
    )
    .reset_index(level=[0,1,2], drop=True)
)

full_df['model_price_volatility_hist_available'] = (
    full_df['model_price_volatility_hist']
    .notna()
    .astype(int)
)

full_df['model_price_volatility_hist'] = (
    full_df['model_price_volatility_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# HISTORY COUNT
# =========================================================

full_df['model_hist_observation_count'] = (
    model_group.cumcount()
)

full_df['model_has_history'] = (
    full_df['model_hist_observation_count'] > 0
).astype(int)

In [57]:
# =========================================================
# MODEL-LEVEL PRICE POSITION FEATURES (SAFE)
# =========================================================

# ---------------------------------------------------------
# POSITION IN HISTORICAL RANGE
# ---------------------------------------------------------

full_df['model_price_position_hist'] = np.where(

    (
        full_df['model_price_max_hist']
        - full_df['model_price_min_hist']
    ) != 0,

    (
        full_df['model_price_last_scrape']
        - full_df['model_price_min_hist']
    )
    /
    (
        full_df['model_price_max_hist']
        - full_df['model_price_min_hist']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# requires:
# - history exists
# - min/max history exists
# =========================================================

full_df['model_price_position_hist_available'] = (
    (
        full_df['model_has_price_history'] == 1
    )
    &
    (
        full_df['model_price_min_hist_available'] == 1
    )
    &
    (
        full_df['model_price_max_hist_available'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# =========================================================

full_df['model_price_position_hist'] = (
    full_df['model_price_position_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# OUTSIDE HISTORICAL RANGE FLAGS
# =========================================================

full_df['model_price_above_hist_max'] = (
    full_df['model_price_last_scrape']
    > full_df['model_price_max_hist']
).astype(int)

full_df['model_price_below_hist_min'] = (
    full_df['model_price_last_scrape']
    < full_df['model_price_min_hist']
).astype(int)

# =========================================================
# =========================================================
# ITEM-LEVEL PRICE POSITION FEATURES (SAFE)
# =========================================================
# =========================================================

# ---------------------------------------------------------
# POSITION IN HISTORICAL RANGE
# ---------------------------------------------------------

full_df['item_price_position_hist'] = np.where(

    (
        full_df['item_price_max_hist']
        - full_df['item_price_min_hist']
    ) != 0,

    (
        full_df['item_price_last_scrape']
        - full_df['item_price_min_hist']
    )
    /
    (
        full_df['item_price_max_hist']
        - full_df['item_price_min_hist']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['item_price_position_hist_available'] = (
    (
        full_df['item_has_price_history'] == 1
    )
    &
    (
        full_df['item_price_min_hist_available'] == 1
    )
    &
    (
        full_df['item_price_max_hist_available'] == 1
    )
).astype(int)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_price_position_hist'] = (
    full_df['item_price_position_hist']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# OUTSIDE HISTORICAL RANGE FLAGS
# =========================================================

full_df['item_price_above_hist_max'] = (
    full_df['item_price_last_scrape']
    > full_df['item_price_max_hist']
).astype(int)

full_df['item_price_below_hist_min'] = (
    full_df['item_price_last_scrape']
    < full_df['item_price_min_hist']
).astype(int)

In [58]:
# =========================================================
# MODEL-LEVEL TREND FEATURES (SAFE)
# =========================================================

# ---------------------------------------------------------
# TREND PER DAY
# ---------------------------------------------------------

full_df['model_price_trend_per_day'] = np.where(

    (
        full_df['model_prev_price_change_available'] == 1
    )
    &
    (
        full_df['model_has_time_history'] == 1
    )
    &
    (
        full_df['model_days_since_last_scrape'] > 0
    ),

    (
        full_df['model_prev_price_change']
        /
        full_df['model_days_since_last_scrape']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['model_price_trend_per_day_available'] = (
    full_df['model_price_trend_per_day']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['model_price_trend_per_day'] = (
    full_df['model_price_trend_per_day']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE TREND
# =========================================================

full_df['model_price_trend_abs'] = (
    full_df['model_price_trend_per_day']
    .abs()
)

# =========================================================
# OPTIONAL:
# TREND DIRECTION
# =========================================================

full_df['model_price_trend_direction'] = np.sign(
    full_df['model_price_trend_per_day']
)

In [59]:
# =========================================================
# ITEM-LEVEL TIME FEATURES
# =========================================================

item_group = full_df.groupby(['shopId', 'itemId'])

# ---------------------------------------------------------
# DAYS SINCE LAST SCRAPE
# ---------------------------------------------------------

full_df['item_days_since_last_scrape'] = (
    full_df['capturedAt']
    - item_group['capturedAt'].shift(1)
).dt.days

# =========================================================
# HISTORY FLAG
# =========================================================

full_df['item_has_time_history'] = (
    full_df['item_days_since_last_scrape']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_days_since_last_scrape'] = (
    full_df['item_days_since_last_scrape']
    .fillna(0)
    .astype(int)
)

# =========================================================
# OPTIONAL:
# DAYS SINCE FIRST SEEN
# =========================================================

full_df['item_days_since_first_seen'] = (
    full_df['capturedAt']
    - item_group['capturedAt'].transform('min')
).dt.days

In [60]:
# =========================================================
# ITEM-LEVEL TREND FEATURES (SAFE)
# =========================================================

# ---------------------------------------------------------
# TREND PER DAY
# ---------------------------------------------------------

full_df['item_price_trend_per_day'] = np.where(

    (
        full_df['item_prev_price_change_available'] == 1
    )
    &
    (
        full_df['item_has_time_history'] == 1
    )
    &
    (
        full_df['item_days_since_last_scrape'] > 0
    ),

    (
        full_df['item_prev_price_change']
        /
        full_df['item_days_since_last_scrape']
    ),

    np.nan
)

# =========================================================
# AVAILABILITY FLAG
# =========================================================

full_df['item_price_trend_per_day_available'] = (
    full_df['item_price_trend_per_day']
    .notna()
    .astype(int)
)

# =========================================================
# SAFE FILL
# =========================================================

full_df['item_price_trend_per_day'] = (
    full_df['item_price_trend_per_day']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# ABSOLUTE TREND
# =========================================================

full_df['item_price_trend_abs'] = (
    full_df['item_price_trend_per_day']
    .abs()
)

# =========================================================
# OPTIONAL:
# TREND DIRECTION
# =========================================================

full_df['item_price_trend_direction'] = np.sign(
    full_df['item_price_trend_per_day']
)

In [61]:
full_df.shape

(301179, 103)

In [62]:
# =========================================================
# DISCOUNT FEATURES (SAFE + PRODUCTION GRADE)
# =========================================================

# ---------------------------------------------------------
# ORIGINAL PRICE AVAILABLE
# ---------------------------------------------------------

full_df['price_before_discount_available'] = (
    full_df['priceBeforeDiscount']
    .notna()
    .astype(int)
)

# ---------------------------------------------------------
# SAFE FILL
# assumption:
# missing original price = no discount
# ---------------------------------------------------------

full_df['priceBeforeDiscount'] = (
    full_df['priceBeforeDiscount']
    .fillna(full_df['price'])
)

# =========================================================
# IS ON SALE
# =========================================================

full_df['is_on_sale'] = (
    full_df['price']
    < full_df['priceBeforeDiscount']
).astype(int)

# =========================================================
# RAW DISCOUNT AMOUNT
# =========================================================

full_df['discount_amount'] = (
    full_df['priceBeforeDiscount']
    - full_df['price']
)

# =========================================================
# DISCOUNT DEPTH
# normalized discount intensity
# =========================================================

full_df['discount_depth'] = np.where(

    full_df['priceBeforeDiscount'] > 0,

    (
        full_df['discount_amount']
        /
        full_df['priceBeforeDiscount']
    ),

    np.nan
)

# availability flag
full_df['discount_depth_available'] = (
    full_df['discount_depth']
    .notna()
    .astype(int)
)

# safe fill
full_df['discount_depth'] = (
    full_df['discount_depth']
    .fillna(0)
)

# =========================================================
# EFFECTIVE DISCOUNT %
# if show_discount exists
# =========================================================

full_df['show_discount_available'] = (
    full_df['show_discount']
    .notna()
    .astype(int)
)

full_df['effective_discount_pct'] = (
    full_df['show_discount'] / 100
)

full_df['effective_discount_pct'] = (
    full_df['effective_discount_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# DISCOUNT VS HISTORICAL ITEM AVG
# VERY POWERFUL FEATURE
# =========================================================

full_df['price_vs_item_hist_avg_pct'] = np.where(

    full_df['item_avg_price_hist_available'] == 1,

    (
        (
            full_df['price']
            - full_df['item_avg_price_hist']
        )
        /
        full_df['item_avg_price_hist'].replace(0, 1)
    ) * 100,

    np.nan
)

full_df['price_vs_item_hist_avg_pct_available'] = (
    full_df['price_vs_item_hist_avg_pct']
    .notna()
    .astype(int)
)

full_df['price_vs_item_hist_avg_pct'] = (
    full_df['price_vs_item_hist_avg_pct']
    .fillna(0)
)

# =========================================================
# OPTIONAL:
# SHARP DISCOUNT FLAG
# =========================================================

full_df['is_sharp_discount'] = (
    full_df['model_prev_price_change_pct'] < -20
).astype(int)

# =========================================================
# POPULARITY FEATURES
# =========================================================

# ---------------------------------------------------------
# SHOP POPULARITY
# ---------------------------------------------------------

full_df['shop_follower_count_available'] = (
    full_df['shop_follower_count']
    .notna()
    .astype(int)
)

full_df['shop_follower_count'] = (
    full_df['shop_follower_count']
    .fillna(0)
)

full_df['shop_popularity'] = np.log1p(
    full_df['shop_follower_count']
)

# =========================================================
# ITEM POPULARITY
# =========================================================

full_df['total_rating_count_available'] = (
    full_df['total_rating_count']
    .notna()
    .astype(int)
)

full_df['total_rating_count'] = (
    full_df['total_rating_count']
    .fillna(0)
)

full_df['item_popularity'] = np.log1p(
    full_df['total_rating_count']
)

# =========================================================
# REVIEW SCORE
# =========================================================

full_df['review_rating_available'] = (
    full_df['review_rating']
    .notna()
    .astype(int)
)

# fill missing with neutral score
full_df['review_rating'] = (
    full_df['review_rating']
    .fillna(0)
)

full_df['review_score_normalized'] = (
    full_df['review_rating'] / 5.0
)

# =========================================================
# OPTIONAL:
# INTERACTION FEATURES
# VERY STRONG FOR TREE MODELS
# =========================================================

full_df['discount_x_popularity'] = (
    full_df['discount_depth']
    * full_df['item_popularity']
)

full_df['discount_x_review_score'] = (
    full_df['discount_depth']
    * full_df['review_score_normalized']
)

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\514726802.py:156: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['shop_popularity'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\514726802.py:164: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['total_rating_count_available'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\514726802.py:175: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['item_popularity'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\514726802.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['review_rating_available'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\514726802.py:195: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['review_score_normalized'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\514726802.py:205: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['discount_x_popularity'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\514726802.py:210: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['discount_x_review_score'] = (

In [63]:
full_df.shape

(301179, 121)

In [64]:
full_df.head(2)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,price_vs_item_hist_avg_pct_available,is_sharp_discount,shop_follower_count_available,shop_popularity,total_rating_count_available,item_popularity,review_rating_available,review_score_normalized,discount_x_popularity,discount_x_review_score
10660,2025-02-02 01:05:10.076,1000692,24160686617,187291892768,60000000,0,0,100632,NaN,NaN,...,0,0,1,6.843750,1,5.521461,1,0.995984,0.0,0.0
23754,2025-02-07 01:05:15.527,1000692,24160686617,187291892768,60000000,0,0,100632,NaN,NaN,...,1,0,1,6.844815,1,5.525453,1,0.996000,0.0,0.0

In [65]:
for i, col in enumerate(full_df.columns, 1):
    print(f"{i}. {col}")

1. capturedAt
2. shopId
3. itemId
4. modelId
5. price
6. priceBeforeDiscount
7. promotionId
8. cat_id
9. stock
10. normal_stock
11. raw_discount
12. show_discount
13. brand
14. is_free_shipping
15. is_pre_order
16. item_price_min
17. item_price_max
18. review_rating
19. total_rating_count
20. cmt_count
21. shop_rating
22. shop_response_rate
23. shop_follower_count
24. is_official_shop
25. is_verified
26. is_preferred_plus_seller
27. tag1
28. date
29. tag2
30. day_of_week
31. is_weekend
32. month
33. day_of_year
34. is_morning
35. is_afternoon
36. is_evening
37. stock_available
38. brand_missing
39. brand_freq
40. shop_response_rate_missing
41. model_price_last_scrape
42. model_price_lag_2
43. model_has_price_history
44. model_has_lag_2_history
45. model_days_since_last_scrape
46. model_has_time_history
47. item_avg_price_hist
48. item_avg_price_hist_available
49. item_price_min_hist
50. item_price_min_hist_available
51. item_price_max_hist
52. item_price_max_hist_available
53. item_price_volatility_hist
54. item_price_volatility_hist_available
55. item_hist_observation_count
56. item_has_history
57. model_prev_price_change
58. model_prev_price_change_available
59. model_prev_price_change_pct
60. model_prev_price_change_pct_available
61. model_prev_price_change_abs
62. model_price_direction
63. model_price_7d_avg_hist
64. model_price_7d_avg_hist_available
65. item_price_last_scrape
66. item_price_lag_2
67. item_has_price_history
68. item_has_lag_2_history
69. item_prev_price_change
70. item_prev_price_change_available
71. item_prev_price_change_pct
72. item_prev_price_change_pct_available
73. item_prev_price_change_abs
74. item_price_direction
75. model_avg_price_hist
76. model_avg_price_hist_available
77. model_price_min_hist
78. model_price_min_hist_available
79. model_price_max_hist
80. model_price_max_hist_available
81. model_price_volatility_hist
82. model_price_volatility_hist_available
83. model_hist_observation_count
84. model_has_history
85. model_price_position_hist
86. model_price_position_hist_available
87. model_price_above_hist_max
88. model_price_below_hist_min
89. item_price_position_hist
90. item_price_position_hist_available
91. item_price_above_hist_max
92. item_price_below_hist_min
93. model_price_trend_per_day
94. model_price_trend_per_day_available
95. model_price_trend_abs
96. model_price_trend_direction
97. item_days_since_last_scrape
98. item_has_time_history
99. item_days_since_first_seen
100. item_price_trend_per_day
101. item_price_trend_per_day_available
102. item_price_trend_abs
103. item_price_trend_direction
104. price_before_discount_available
105. is_on_sale
106. discount_amount
107. discount_depth
108. discount_depth_available
109. show_discount_available
110. effective_discount_pct
111. price_vs_item_hist_avg_pct
112. price_vs_item_hist_avg_pct_available
113. is_sharp_discount
114. shop_follower_count_available
115. shop_popularity
116. total_rating_count_available
117. item_popularity
118. review_rating_available
119. review_score_normalized
120. discount_x_popularity
121. discount_x_review_score

In [66]:
missing_report = full_df.isna().sum().to_frame('missing_count')
missing_report['missing_pct'] = 100 * missing_report['missing_count'] / len(full_df)
missing_report.sort_values(by='missing_pct', ascending=False).head(20)

                                       missing_count  missing_pct
stock                                         297479    98.771495
normal_stock                                  297479    98.771495
capturedAt                                         0     0.000000
model_price_min_hist_available                     0     0.000000
item_price_position_hist_available                 0     0.000000
item_price_position_hist                           0     0.000000
model_price_below_hist_min                         0     0.000000
model_price_above_hist_max                         0     0.000000
model_price_position_hist_available                0     0.000000
model_price_position_hist                          0     0.000000
model_has_history                                  0     0.000000
model_hist_observation_count                       0     0.000000
model_price_volatility_hist_available              0     0.000000
model_price_volatility_hist                        0     0.000000
model_price_max_hist_available                     0     0.000000
model_price_max_hist                               0     0.000000
model_avg_price_hist_available                     0     0.000000
model_price_min_hist                               0     0.000000
item_price_below_hist_min                          0     0.000000
model_avg_price_hist                               0     0.000000

In [67]:
# =========================================================
# LOG TRANSFORM FEATURES
# =========================================================

import numpy as np

# =========================================================
# HELPER FUNCTION
# for features that can be negative
# =========================================================

def signed_log1p(x):
    return np.sign(x) * np.log1p(np.abs(x))

# =========================================================
# POSITIVE FEATURES
# =========================================================

log_features = [

    # -----------------------------------------------------
    # ITEM HISTORICAL PRICE FEATURES
    # -----------------------------------------------------

    'item_avg_price_hist',
    'item_price_min_hist',
    'item_price_max_hist',
    'item_price_volatility_hist',

    # -----------------------------------------------------
    # MODEL HISTORICAL PRICE FEATURES
    # -----------------------------------------------------

    'model_avg_price_hist',
    'model_price_min_hist',
    'model_price_max_hist',
    'model_price_volatility_hist',

    # -----------------------------------------------------
    # LAG FEATURES
    # -----------------------------------------------------

    'item_price_last_scrape',
    'item_price_lag_2',

    'model_price_last_scrape',
    'model_price_lag_2',

    # -----------------------------------------------------
    # DISCOUNT FEATURES
    # -----------------------------------------------------

    'discount_amount',
    'priceBeforeDiscount',

    # -----------------------------------------------------
    # OBSERVATION / HISTORY FEATURES
    # -----------------------------------------------------

    'item_hist_observation_count',
    'model_hist_observation_count',

    # -----------------------------------------------------
    # TIME FEATURES
    # -----------------------------------------------------

    'item_days_since_first_seen'
]

# =========================================================
# CREATE LOG FEATURES
# =========================================================

for col in log_features:

    if col in full_df.columns:

        full_df[f'{col}_log1p'] = np.log1p(
            full_df[col].clip(lower=0)
        )

# =========================================================
# SIGNED FEATURES
# =========================================================

signed_features = [

    # -----------------------------------------------------
    # PRICE CHANGES
    # -----------------------------------------------------

    'model_prev_price_change',
    'item_prev_price_change',

    # -----------------------------------------------------
    # PERCENTAGE CHANGES
    # -----------------------------------------------------

    'model_prev_price_change_pct',
    'item_prev_price_change_pct',

    # -----------------------------------------------------
    # TREND FEATURES
    # -----------------------------------------------------

    'model_price_trend_per_day',
    'item_price_trend_per_day'
]

# =========================================================
# CREATE SIGNED LOG FEATURES
# =========================================================

for col in signed_features:

    if col in full_df.columns:

        full_df[f'{col}_signed_log1p'] = (
            np.sign(full_df[col])
            *
            np.log1p(np.abs(full_df[col]))
        )

# =========================================================
# OPTIONAL:
# LOG TRANSFORM TARGET
# =========================================================

full_df['price_log1p'] = np.log1p(
    full_df['price']
)

print("Log-transformed features created successfully.")

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:78: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_log1p'] = np.log1p(

Log-transformed features created successfully.

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:118: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df[f'{col}_signed_log1p'] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3949125261.py:129: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  full_df['price_log1p'] = np.log1p(

In [68]:
full_df.shape

(301179, 145)

In [69]:
full_df.duplicated().sum()

0

In [70]:
full_df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
capturedAt,301179,NaN,NaN,NaN,2025-02-28 10:24:57.094780928,2025-01-01 22:37:36.424000,2025-02-18 16:03:13.060000,2025-03-03 02:35:54.060999936,2025-03-12 07:31:08.279000064,2025-03-22 04:17:29.207000,NaN
shopId,301179.0,NaN,NaN,NaN,645275882.144711,1000692.0,100291901.0,1002919413.0,1006572327.0,1206969280.0,466450235.57633
itemId,301179.0,NaN,NaN,NaN,19342618773.541195,66326595.0,16547649387.0,22456263718.0,24958046381.0,29960888656.0,8486160647.312671
modelId,301179.0,NaN,NaN,NaN,164936202579.853088,52465307.0,118322901940.0,185360511591.0,223455354284.0,257896972082.0,73657985667.48082
price,301179.0,NaN,NaN,NaN,52712209.682614,100000.0,9900000.0,20900000.0,59900000.0,1660000000.0,91536568.284388
...,...,...,...,...,...,...,...,...,...,...,...
model_prev_price_change_pct_signed_log1p,301179.0,NaN,NaN,NaN,0.001499,-4.493121,0.0,0.0,0.0,6.637348,0.216548
item_prev_price_change_pct_signed_log1p,301179.0,NaN,NaN,NaN,0.003851,-4.493121,0.0,0.0,0.0,6.637348,0.355153
model_price_trend_per_day_signed_log1p,301179.0,NaN,NaN,NaN,0.006569,-19.905462,0.0,0.0,0.0,19.212315,0.734652
item_price_trend_per_day_signed_log1p,301179.0,NaN,NaN,NaN,0.014233,-19.922533,0.0,0.0,0.0,19.337371,1.215343
price_log1p,301179.0,NaN,NaN,NaN,16.984283,11.512935,16.108045,16.85526,17.908187,21.230083,1.270153

In [71]:
[col for col in full_df.columns if 'count' in col]

['priceBeforeDiscount',
 'raw_discount',
 'show_discount',
 'total_rating_count',
 'cmt_count',
 'shop_follower_count',
 'item_hist_observation_count',
 'model_hist_observation_count',
 'price_before_discount_available',
 'discount_amount',
 'discount_depth',
 'discount_depth_available',
 'show_discount_available',
 'effective_discount_pct',
 'is_sharp_discount',
 'shop_follower_count_available',
 'total_rating_count_available',
 'discount_x_popularity',
 'discount_x_review_score',
 'discount_amount_log1p',
 'priceBeforeDiscount_log1p',
 'item_hist_observation_count_log1p',
 'model_hist_observation_count_log1p']

In [72]:
# =========================================================
# ITEM-LEVEL LOG-IQR OUTLIER DETECTION
# ONLY FLAG:
# - ABOVE UPPER BOUND
# - is_on_sale == 0
# =========================================================

import numpy as np
import pandas as pd

# =========================================================
# SANDBOX COPY
# =========================================================

full_df2 = full_df.copy()

# =========================================================
# PARAMETERS
# =========================================================

IQR_MULTIPLIER = 2
MIN_ITEM_COUNT = 5

# =========================================================
# TRAIN DATA ONLY
# =========================================================

train_df2 = full_df2[
    full_df2['tag2'] == 'TRAIN'
].copy()

# =========================================================
# LOG PRICE
# =========================================================

train_df2['log_price'] = np.log1p(
    train_df2['price']
)

full_df2['log_price'] = np.log1p(
    full_df2['price']
)

# =========================================================
# ITEM-LEVEL LOG-IQR STATS
# =========================================================

item_stats = (

    train_df2
    .groupby('itemId')['log_price']
    .agg(
        q1=lambda x: x.quantile(0.25),
        q3=lambda x: x.quantile(0.75),
        median='median',
        count='count'
    )
)

# =========================================================
# IQR
# =========================================================

item_stats['iqr'] = (
    item_stats['q3']
    - item_stats['q1']
)

# =========================================================
# LOWER / UPPER BOUNDS
# =========================================================

item_stats['lower_bound'] = (

    item_stats['q1']
    - IQR_MULTIPLIER * item_stats['iqr']
)

item_stats['upper_bound'] = (

    item_stats['q3']
    + IQR_MULTIPLIER * item_stats['iqr']
)

# =========================================================
# MERGE BACK
# =========================================================

full_df2 = full_df2.merge(

    item_stats[
        [
            'lower_bound',
            'upper_bound',
            'count'
        ]
    ],

    on='itemId',
    how='left'
)

# =========================================================
# OUTLIER FLAG
# ONLY:
# - ABOVE UPPER BOUND
# - NOT ON SALE
# - ENOUGH HISTORY
# =========================================================

full_df2['item_log_iqr_outlier'] = np.where(

    (
        (full_df2['count'] >= MIN_ITEM_COUNT)
        &
        (full_df2['log_price'] > full_df2['upper_bound'])
        &
        (full_df2['is_on_sale'] == 0)
    ),

    1,

    0
)

# =========================================================
# DISTANCE ABOVE UPPER BOUND
# =========================================================

full_df2['item_iqr_distance'] = np.where(

    full_df2['log_price']
    > full_df2['upper_bound'],

    full_df2['log_price']
    - full_df2['upper_bound'],

    0
)

# =========================================================
# SUMMARY
# =========================================================

print("=" * 60)

print(
    f"Detected outliers: "
    f"{full_df2['item_log_iqr_outlier'].sum():,}"
)

print("=" * 60)

# =========================================================
# VIEW EXAMPLES
# =========================================================

outlier_examples = full_df2[
    full_df2['item_log_iqr_outlier'] == 1
].copy()

# =========================================================
# SORT MOST EXTREME
# =========================================================

outlier_examples = outlier_examples.sort_values(
    by='item_iqr_distance',
    ascending=False
)

# =========================================================
# DISPLAY WITH REFERENCE PRICES
# =========================================================

outlier_examples['lower_bound_price'] = np.expm1(
    outlier_examples['lower_bound']
)

outlier_examples['upper_bound_price'] = np.expm1(
    outlier_examples['upper_bound']
)

# =========================================================
# DISPLAY COLUMNS
# =========================================================

display_cols = [

    'capturedAt',

    'shopId',
    'itemId',
    'modelId',

    # current pricing
    'price',
    'priceBeforeDiscount',

    # discount info
    'is_on_sale',
    'discount_amount',
    'discount_depth',
    'effective_discount_pct',
    'is_sharp_discount',

    # log price
    'log_price',

    # historical references
    'item_avg_price_hist',
    'item_price_min_hist',
    'item_price_max_hist',

    # IQR bounds
    'lower_bound_price',
    'upper_bound_price',

    # anomaly strength
    'item_iqr_distance',

    # history count
    'count'
]

# =========================================================
# SHOW TOP OUTLIERS
# =========================================================

display(
    outlier_examples[
        display_cols
    ].head(10)
)

# =========================================================
# SEE TEMP COLUMNS CREATED
# =========================================================

new_cols = sorted(
    list(
        set(full_df2.columns)
        -
        set(full_df.columns)
    )
)

print("\nNEW TEMPORARY COLUMNS:\n")

for col in new_cols:
    print(col)

============================================================
Detected outliers: 4,372
============================================================

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,is_on_sale,discount_amount,discount_depth,effective_discount_pct,is_sharp_discount,log_price,item_avg_price_hist,item_price_min_hist,item_price_max_hist,lower_bound_price,upper_bound_price,item_iqr_distance,count
123300,2025-02-16 17:21:24.209,1001466875,28616868879,49484612877,25000000,0,0,-25000000,0.0,0.00,0,17.034386,3755000.0,2900000.0,20000000.0,2900000.0,2900000.0,2.154165,24
123288,2025-02-16 17:21:24.209,1001466875,28616868879,49484612876,20000000,0,0,-20000000,0.0,0.00,0,16.811243,2900000.0,2900000.0,2900000.0,2900000.0,2900000.0,1.931021,24
183915,2025-03-12 00:45:51.722,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183909,2025-03-10 22:36:37.609,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183910,2025-03-11 04:39:36.798,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183911,2025-03-11 12:43:11.656,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183912,2025-03-11 16:43:07.385,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183913,2025-03-11 18:43:53.378,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183914,2025-03-11 22:36:23.833,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096
183916,2025-03-12 02:31:30.121,1005099271,22046650830,118121438221,49900000,0,0,-49900000,0.0,0.72,0,17.725532,49900000.0,49900000.0,49900000.0,13900000.0,13900000.0,1.278132,1096

NEW TEMPORARY COLUMNS:

count
item_iqr_distance
item_log_iqr_outlier
log_price
lower_bound
upper_bound

In [73]:
full_df2.shape

(301179, 151)

In [74]:
clean_df = full_df2[full_df2['item_log_iqr_outlier'] == 0]

In [75]:
clean_df.shape

(296807, 151)

In [76]:
301179-296807

4372

In [77]:
# =========================================================
# CONVERT 't' / 'f' STRING FLAGS TO INTEGER
# =========================================================

tf_cols = [

    'is_official_shop',
    'is_verified',
    'is_preferred_plus_seller',

    'is_free_shipping',
    'is_pre_order'
]

for col in tf_cols:

    clean_df[col] = (

        clean_df[col]

        .fillna('f')

        .str.lower()

        .map({
            't': 1,
            'f': 0
        })

        .astype(int)
    )

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2424913825.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df[col] = (

In [78]:
[col for col in clean_df.columns]

['capturedAt',
 'shopId',
 'itemId',
 'modelId',
 'price',
 'priceBeforeDiscount',
 'promotionId',
 'cat_id',
 'stock',
 'normal_stock',
 'raw_discount',
 'show_discount',
 'brand',
 'is_free_shipping',
 'is_pre_order',
 'item_price_min',
 'item_price_max',
 'review_rating',
 'total_rating_count',
 'cmt_count',
 'shop_rating',
 'shop_response_rate',
 'shop_follower_count',
 'is_official_shop',
 'is_verified',
 'is_preferred_plus_seller',
 'tag1',
 'date',
 'tag2',
 'day_of_week',
 'is_weekend',
 'month',
 'day_of_year',
 'is_morning',
 'is_afternoon',
 'is_evening',
 'stock_available',
 'brand_missing',
 'brand_freq',
 'shop_response_rate_missing',
 'model_price_last_scrape',
 'model_price_lag_2',
 'model_has_price_history',
 'model_has_lag_2_history',
 'model_days_since_last_scrape',
 'model_has_time_history',
 'item_avg_price_hist',
 'item_avg_price_hist_available',
 'item_price_min_hist',
 'item_price_min_hist_available',
 'item_price_max_hist',
 'item_price_max_hist_available',
 'item_price_volatility_hist',
 'item_price_volatility_hist_available',
 'item_hist_observation_count',
 'item_has_history',
 'model_prev_price_change',
 'model_prev_price_change_available',
 'model_prev_price_change_pct',
 'model_prev_price_change_pct_available',
 'model_prev_price_change_abs',
 'model_price_direction',
 'model_price_7d_avg_hist',
 'model_price_7d_avg_hist_available',
 'item_price_last_scrape',
 'item_price_lag_2',
 'item_has_price_history',
 'item_has_lag_2_history',
 'item_prev_price_change',
 'item_prev_price_change_available',
 'item_prev_price_change_pct',
 'item_prev_price_change_pct_available',
 'item_prev_price_change_abs',
 'item_price_direction',
 'model_avg_price_hist',
 'model_avg_price_hist_available',
 'model_price_min_hist',
 'model_price_min_hist_available',
 'model_price_max_hist',
 'model_price_max_hist_available',
 'model_price_volatility_hist',
 'model_price_volatility_hist_available',
 'model_hist_observation_count',
 'model_has_history',
 'model_price_position_hist',
 'model_price_position_hist_available',
 'model_price_above_hist_max',
 'model_price_below_hist_min',
 'item_price_position_hist',
 'item_price_position_hist_available',
 'item_price_above_hist_max',
 'item_price_below_hist_min',
 'model_price_trend_per_day',
 'model_price_trend_per_day_available',
 'model_price_trend_abs',
 'model_price_trend_direction',
 'item_days_since_last_scrape',
 'item_has_time_history',
 'item_days_since_first_seen',
 'item_price_trend_per_day',
 'item_price_trend_per_day_available',
 'item_price_trend_abs',
 'item_price_trend_direction',
 'price_before_discount_available',
 'is_on_sale',
 'discount_amount',
 'discount_depth',
 'discount_depth_available',
 'show_discount_available',
 'effective_discount_pct',
 'price_vs_item_hist_avg_pct',
 'price_vs_item_hist_avg_pct_available',
 'is_sharp_discount',
 'shop_follower_count_available',
 'shop_popularity',
 'total_rating_count_available',
 'item_popularity',
 'review_rating_available',
 'review_score_normalized',
 'discount_x_popularity',
 'discount_x_review_score',
 'item_avg_price_hist_log1p',
 'item_price_min_hist_log1p',
 'item_price_max_hist_log1p',
 'item_price_volatility_hist_log1p',
 'model_avg_price_hist_log1p',
 'model_price_min_hist_log1p',
 'model_price_max_hist_log1p',
 'model_price_volatility_hist_log1p',
 'item_price_last_scrape_log1p',
 'item_price_lag_2_log1p',
 'model_price_last_scrape_log1p',
 'model_price_lag_2_log1p',
 'discount_amount_log1p',
 'priceBeforeDiscount_log1p',
 'item_hist_observation_count_log1p',
 'model_hist_observation_count_log1p',
 'item_days_since_first_seen_log1p',
 'model_prev_price_change_signed_log1p',
 'item_prev_price_change_signed_log1p',
 'model_prev_price_change_pct_signed_log1p',
 'item_prev_price_change_pct_signed_log1p',
 'model_price_trend_per_day_signed_log1p',
 'item_price_trend_per_day_signed_log1p',
 'price_log1p',
 'log_price',
 'lower_bound',
 'upper_bound',
 'count',
 'item_log_iqr_outlier',
 'item_iqr_distance']

======================================================================
START MODELLING
======================================================================

In [79]:
# =========================================================
# APPROACH 2
# ENTITY-CONDITIONED XGBOOST MODEL
#
# KEY DIFFERENCE VS APPROACH 1:
# - include shopId / itemId / modelId
# - categorical handling enabled
# =========================================================

import numpy as np
import pandas as pd

from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

# =========================================================
# TRAIN / TEST SPLIT
# =========================================================

train_df = clean_df[
    clean_df['tag2'] == 'TRAIN'
].copy()

test_df = clean_df[
    clean_df['tag2'] != 'TRAIN'
].copy()


# =========================================================
# ENTITY IDS AS CATEGORICAL
# =========================================================
#
# VERY IMPORTANT:
# IDs are NOT numeric quantities.
# They are categorical identities.
#
# XGBoost can now handle this directly.
# =========================================================

cat_id_cols = [

    'shopId',
    'itemId',
    'modelId'
]

for col in cat_id_cols:

    train_df[col] = (
        train_df[col]
        .astype('category')
    )

    test_df[col] = (
        test_df[col]
        .astype('category')
    )

# =========================================================
# FEATURES
# =========================================================

FEATURES = [

    # -----------------------------------------------------
    # ENTITY IDS
    # -----------------------------------------------------

    'shopId',
    'itemId',
    'modelId',

    # -----------------------------------------------------
    # CATEGORY / BRAND
    # -----------------------------------------------------

    'cat_id',
    'brand_freq',
    'brand_missing',

    # -----------------------------------------------------
    # TEMPORAL
    # -----------------------------------------------------

    'day_of_week',
    'is_weekend',
    'month',
    'day_of_year',

    'is_morning',
    'is_afternoon',
    'is_evening',

    # -----------------------------------------------------
    # SHOP FEATURES
    # -----------------------------------------------------

    'shop_rating',
    'shop_response_rate',

    'shop_popularity',
    'shop_follower_count_available',

    'is_official_shop',
    'is_verified',
    'is_preferred_plus_seller',

    # -----------------------------------------------------
    # ITEM POPULARITY
    # -----------------------------------------------------

    'item_popularity',
    'total_rating_count_available',

    'review_score_normalized',
    'review_rating_available',

    'cmt_count',

    # -----------------------------------------------------
    # SHIPPING / FLAGS
    # -----------------------------------------------------

    'is_free_shipping',
    'is_pre_order',

    # -----------------------------------------------------
    # DISCOUNT FEATURES
    # -----------------------------------------------------

    'is_on_sale',

    'discount_amount_log1p',
    'discount_depth',

    'effective_discount_pct',

    'is_sharp_discount',

    'discount_x_popularity',
    'discount_x_review_score',

    # -----------------------------------------------------
    # ITEM HISTORY
    # -----------------------------------------------------

    'item_has_history',

    'item_avg_price_hist_log1p',
    'item_price_min_hist_log1p',
    'item_price_max_hist_log1p',

    'item_price_volatility_hist_log1p',

    'item_hist_observation_count_log1p',

    # -----------------------------------------------------
    # ITEM LAGS
    # -----------------------------------------------------

    'item_price_last_scrape_log1p',
    'item_price_lag_2_log1p',

    'item_has_price_history',
    'item_has_lag_2_history',

    # -----------------------------------------------------
    # ITEM PRICE CHANGE
    # -----------------------------------------------------

    'item_prev_price_change_signed_log1p',
    'item_prev_price_change_pct_signed_log1p',

    'item_prev_price_change_abs',

    'item_price_direction',

    # -----------------------------------------------------
    # ITEM TREND
    # -----------------------------------------------------

    'item_days_since_last_scrape',

    'item_days_since_first_seen_log1p',

    'item_price_trend_per_day_signed_log1p',

    'item_price_trend_abs',
    'item_price_trend_direction',

    # -----------------------------------------------------
    # ITEM POSITION
    # -----------------------------------------------------

    'item_price_position_hist',

    'item_price_above_hist_max',
    'item_price_below_hist_min',

    # -----------------------------------------------------
    # MODEL HISTORY
    # -----------------------------------------------------

    'model_has_history',

    'model_avg_price_hist_log1p',
    'model_price_min_hist_log1p',
    'model_price_max_hist_log1p',

    'model_price_volatility_hist_log1p',

    'model_hist_observation_count_log1p',

    # -----------------------------------------------------
    # MODEL LAGS
    # -----------------------------------------------------

    'model_price_last_scrape_log1p',
    'model_price_lag_2_log1p',

    'model_has_price_history',
    'model_has_lag_2_history',

    # -----------------------------------------------------
    # MODEL PRICE CHANGE
    # -----------------------------------------------------

    'model_prev_price_change_signed_log1p',
    'model_prev_price_change_pct_signed_log1p',

    'model_prev_price_change_abs',

    'model_price_direction',

    # -----------------------------------------------------
    # MODEL TREND
    # -----------------------------------------------------

    'model_days_since_last_scrape',

    'model_price_trend_per_day_signed_log1p',

    'model_price_trend_abs',
    'model_price_trend_direction',

    # -----------------------------------------------------
    # MODEL POSITION
    # -----------------------------------------------------

    'model_price_position_hist',

    'model_price_above_hist_max',
    'model_price_below_hist_min',

    # -----------------------------------------------------
    # AVAILABILITY FLAGS
    # -----------------------------------------------------

    'stock_available',

    'item_avg_price_hist_available',
    'item_price_min_hist_available',
    'item_price_max_hist_available',
    'item_price_volatility_hist_available',

    'model_avg_price_hist_available',
    'model_price_min_hist_available',
    'model_price_max_hist_available',
    'model_price_volatility_hist_available',

    'item_prev_price_change_available',
    'item_prev_price_change_pct_available',

    'model_prev_price_change_available',
    'model_prev_price_change_pct_available',

    'model_price_7d_avg_hist_available',

    'model_price_position_hist_available',
    'item_price_position_hist_available',

    'discount_depth_available',
    'show_discount_available',

    'price_before_discount_available',

    'price_vs_item_hist_avg_pct_available',

    'price_vs_item_hist_avg_pct'
]

# =========================================================
# TARGET
# =========================================================

TARGET = 'price_log1p'

# =========================================================
# PREPARE X / Y
# =========================================================

X_train = train_df[FEATURES]
y_train = train_df[TARGET]

X_test = test_df[FEATURES]
y_test = test_df[TARGET]

# =========================================================
# XGBOOST MODEL
# =========================================================
#
# enable_categorical=True is critical
# for entity IDs
# =========================================================

model = XGBRegressor(

    n_estimators=500,

    learning_rate=0.03,

    max_depth=10,

    min_child_weight=5,

    subsample=0.8,
    colsample_bytree=0.8,

    reg_alpha=1,
    reg_lambda=1,

    objective='reg:squarederror',

    tree_method='hist',

    enable_categorical=True,

    random_state=42,

    n_jobs=-1
)

# =========================================================
# TRAIN
# =========================================================

model.fit(
    X_train,
    y_train
)

# =========================================================
# PREDICT
# =========================================================

pred_log = model.predict(X_test)

pred_price = np.expm1(pred_log)

actual_price = np.expm1(y_test)

# =========================================================
# EVALUATION
# =========================================================

rmse = np.sqrt(
    mean_squared_error(
        actual_price,
        pred_price
    )
)

mae = mean_absolute_error(
    actual_price,
    pred_price
)

mape = (
    np.abs(
        (actual_price - pred_price)
        /
        actual_price.clip(lower=1)
    ).mean()
) * 100

# =========================================================
# RESULTS
# =========================================================

print("=" * 60)

print("APPROACH 2 — ENTITY-CONDITIONED MODEL")

print("=" * 60)

print(f"FEATURE COUNT: {len(FEATURES)}")

print("=" * 60)

print(f"RMSE : {rmse:,.2f}")
print(f"MAE  : {mae:,.2f}")
print(f"MAPE : {mape:.2f}%")

print("=" * 60)

# =========================================================
# FEATURE IMPORTANCE
# =========================================================

feature_importance = pd.DataFrame({

    'feature': FEATURES,

    'importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='importance',
    ascending=False
)

display(
    feature_importance.head(20)
)

# =========================================================
# PREDICTION SAMPLE
# =========================================================

pred_df = test_df.copy()

pred_df['pred_price'] = pred_price
pred_df['actual_price'] = actual_price

pred_df['abs_error'] = (
    pred_df['actual_price']
    -
    pred_df['pred_price']
).abs()

pred_df['pct_abs_error'] = (
    pred_df['abs_error']
    /
    pred_df['actual_price']
).abs()

display_cols = [

    'shopId',
    'itemId',
    'modelId',

    'actual_price',
    'pred_price',

    'abs_error',
    'pct_abs_error'
]

display(
    pred_df[
        display_cols
    ]
    .sort_values(
        by='abs_error',
        ascending=False
    )
    .head(10)
)

============================================================
APPROACH 2 — ENTITY-CONDITIONED MODEL
============================================================
FEATURE COUNT: 98
============================================================
RMSE : 44,809,105.90
MAE  : 7,737,374.66
MAPE : 30.98%
============================================================

                          feature  importance
40   item_price_last_scrape_log1p    0.522950
41         item_price_lag_2_log1p    0.253791
62  model_price_last_scrape_log1p    0.057952
34               item_has_history    0.048060
1                          itemId    0.041050
57     model_avg_price_hist_log1p    0.022578
2                         modelId    0.021411
68    model_prev_price_change_abs    0.008826
58     model_price_min_hist_log1p    0.005838
35      item_avg_price_hist_log1p    0.003843
0                          shopId    0.002928
59     model_price_max_hist_log1p    0.001413
36      item_price_min_hist_log1p    0.001360
56              model_has_history    0.000652
28          discount_amount_log1p    0.000536
43         item_has_lag_2_history    0.000399
29                 discount_depth    0.000366
5                   brand_missing    0.000354
63        model_price_lag_2_log1p    0.000319
30         effective_discount_pct    0.000296

,shopId,itemId,modelId,actual_price,pred_price,abs_error,pct_abs_error
51050,10055250,21361590976,59208605361,9.490000e+08,550104064.0,3.988959e+08,0.420333
51874,10055250,29423577723,223709159272,7.590000e+08,579346944.0,1.796531e+08,0.236697
237647,1007168904,24823752002,217925190213,4.100000e+08,354885376.0,5.511462e+07,0.134426
183133,1005099271,21892030953,167813748693,6.800000e+07,59814880.0,8.185120e+06,0.120369
149775,1002919413,26820461772,257553911837,1.779000e+08,172092224.0,5.807776e+06,0.032646
151712,1002919413,28055404484,257553915393,1.779000e+08,172779600.0,5.120400e+06,0.028782
50801,10055250,19262129512,213179841270,1.990000e+08,194750672.0,4.249328e+06,0.021353
220930,1005700927,23279342490,221994645834,4.900000e+06,8241995.5,3.341995e+06,0.682040
163398,1005099271,14697728192,99387637905,3.000000e+05,3593121.0,3.293121e+06,10.977070
158996,1003613948,26911541454,246612875059,1.000000e+06,4279215.5,3.279216e+06,3.279216

In [80]:
clean_df[clean_df['modelId'] == 59208605361][['price', 'item_price_last_scrape', 'item_has_price_history', 'model_has_price_history', 'model_price_last_scrape']]

,price,item_price_last_scrape,item_has_price_history,model_has_price_history,model_price_last_scrape
50911,949000000,0.0,0,0,0.0
50912,949000000,949000000.0,1,1,949000000.0
50913,949000000,949000000.0,1,1,949000000.0
50914,949000000,949000000.0,1,1,949000000.0
50915,949000000,949000000.0,1,1,949000000.0
...,...,...,...,...,...
51046,949000000,949000000.0,1,1,949000000.0
51047,949000000,949000000.0,1,1,949000000.0
51048,949000000,949000000.0,1,1,949000000.0
51049,949000000,949000000.0,1,1,949000000.0
51050,949000000,949000000.0,1,1,949000000.0

===========================

TRYING CATBOOST

============================

In [93]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp311-cp311-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from catboost) (3.7.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from catboost) (1.11.1)
Requirement already satisfied: plotly in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from catboost) (6.1.0)
Requirement already satisfied: six in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2023.3)
Requirement already satisfied: tzdata>=2022.7 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->catboost) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->catboost) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\purna\appdata\local\programs\python\python311\lib\site-packages (from plotly->catboost) (1.39.1)
Downloading catboost-1.2.10-cp311-cp311-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
    --------------------------------------- 1.3/100.2 MB 8.4 MB/s eta 0:00:12
   - -------------------------------------- 2.9/100.2 MB 8.4 MB/s eta 0:00:12
   - -------------------------------------- 4.5/100.2 MB 7.7 MB/s eta 0:00:13
   -- ------------------------------------- 6.6/100.2 MB 8.0 MB/s eta 0:00:12
   --- ------------------------------------ 8.1/100.2 MB 8.3 MB/s eta 0:00:12
   ---- ----------------------------------- 10.2/100.2 MB 8.3 MB/s eta 0:00:11
   ---- ----------------------------------- 12.1/100.2 MB 8.5 MB/s eta 0:00:11
   ----- ---------------------------------- 13.9/100.2 MB 8.6 MB/s eta 0:00:11
   ------ --------------------------------- 15.7/100.2 MB 8.5 MB/s eta 0:00:10
   ------- -------------------------------- 17.8/100.2 MB 8.6 MB/s eta 0:00:10
   ------- -------------------------------- 19.9/100.2 MB 8.7 MB/s eta 0:00:10
   -------- ------------------------------- 21.8/100.2 MB 8.6 MB/s eta 0:00:10
   --------- ------------------------------ 24.4/100.2 MB 8.7 MB/s eta 0:00:09
   ---------- ----------------------------- 27.3/100.2 MB 8.8 MB/s eta 0:00:09
   ----------- ---------------------------- 29.4/100.2 MB 8.7 MB/s eta 0:00:09
   ------------ --------------------------- 31.5/100.2 MB 8.8 MB/s eta 0:00:08
   ------------- -------------------------- 33.3/100.2 MB 8.8 MB/s eta 0:00:08
   -------------- ------------------------- 35.4/100.2 MB 8.8 MB/s eta 0:00:08
   -------------- ------------------------- 37.2/100.2 MB 8.8 MB/s eta 0:00:08
   --------------- ------------------------ 39.1/100.2 MB 8.8 MB/s eta 0:00:07
   ---------------- ----------------------- 40.9/100.2 MB 8.8 MB/s eta 0:00:07
   ----------------- ---------------------- 43.3/100.2 MB 8.9 MB/s eta 0:00:07
   ----------------- ---------------------- 45.1/100.2 MB 8.9 MB/s eta 0:00:07
   ------------------ --------------------- 47.2/100.2 MB 8.9 MB/s eta 0:00:06
   ------------------- -------------------- 49.3/100.2 MB 8.9 MB/s eta 0:00:06
   -------------------- ------------------- 51.1/100.2 MB 8.9 MB/s eta 0:00:06
   --------------------- ------------------ 53.0/100.2 MB 8.9 MB/s eta 0:00:06
   --------------------- ------------------ 55.1/100.2 MB 9.0 MB/s eta 0:00:06
   ---------------------- ----------------- 57.4/100.2 MB 9.0 MB/s eta 0:00:05
   ----------------------- ---------------- 59.2/100.2 MB 9.0 MB/s eta 0:00:05
   ------------------------ --------------- 61.1/100.2 MB 9.0 MB/s eta 0:00:05
   ------------------------- -------------- 63.2/100.2 MB 9.0 MB/s eta 0:00:05
   -------------------------- ------------- 66.1/100.2 MB 8.9 MB/s eta 0:00:04
   -------------------------- ------------- 67.1/100.2 MB 8.9 MB/s eta 0:00:04
   ---------------------------- ----------- 70.3/100.2 MB 8.6 MB/s eta 0:00:04
   ----------------------------- ---------- 72.9/100.2 MB 8.7 MB/s eta 0:00:04
   ------------------------------ --------- 76.3/100.2 MB 8.7 MB/s eta 0:00:03
   ------------------------------- -------- 78.4/100.2 MB 8.7 MB/s eta 0:00:03
   -------------------------------- ------- 81.3/100.2 MB 8.7 MB/s eta 0:00:03
   --------------------------------- ------ 84.7/100.2 MB 8.7 MB/s eta 0:00:02
   ---------------------------------- ----- 86.5/100.2 MB 8.7 MB/s eta 0:00:02
   ----------------------------------- ---- 89.1/100.2 MB 8.6 MB/s eta 0:00:02
   ------------------------------------ --- 91.8/100.2 MB 8.6 MB/s eta 0:00:01
   ------------------------------------- -- 94.6/100.2 MB 8.6 MB/s eta 0:00:01
   -------------------------------------- - 97.0/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  99.4/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 6.0 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [81]:
# =========================================================
# APPROACH 2
# CATBOOST ENTITY-CONDITIONED MODEL
# =========================================================

import numpy as np
import pandas as pd

from catboost import CatBoostRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

# =========================================================
# TRAIN / TEST SPLIT
# =========================================================

train_df = clean_df[
    clean_df['tag2'] == 'TRAIN'
].copy()

test_df = clean_df[
    clean_df['tag2'] != 'TRAIN'
].copy()


# =========================================================
# FEATURES
# =========================================================

FEATURES = [

    # -----------------------------------------------------
    # ENTITY IDS
    # -----------------------------------------------------

    'shopId',
    'itemId',
    'modelId',

    # -----------------------------------------------------
    # CATEGORY / BRAND
    # -----------------------------------------------------

    'cat_id',
    'brand_freq',
    'brand_missing',

    # -----------------------------------------------------
    # TEMPORAL
    # -----------------------------------------------------

    'day_of_week',
    'is_weekend',
    'month',
    'day_of_year',

    'is_morning',
    'is_afternoon',
    'is_evening',

    # -----------------------------------------------------
    # SHOP FEATURES
    # -----------------------------------------------------

    'shop_rating',
    'shop_response_rate',

    'shop_popularity',
    'shop_follower_count_available',

    'is_official_shop',
    'is_verified',
    'is_preferred_plus_seller',

    # -----------------------------------------------------
    # ITEM POPULARITY
    # -----------------------------------------------------

    'item_popularity',
    'total_rating_count_available',

    'review_score_normalized',
    'review_rating_available',

    'cmt_count',

    # -----------------------------------------------------
    # SHIPPING / FLAGS
    # -----------------------------------------------------

    'is_free_shipping',
    'is_pre_order',

    # -----------------------------------------------------
    # DISCOUNT FEATURES
    # -----------------------------------------------------

    'is_on_sale',

    'discount_amount_log1p',
    'discount_depth',

    'effective_discount_pct',

    'is_sharp_discount',

    'discount_x_popularity',
    'discount_x_review_score',

    # -----------------------------------------------------
    # ITEM HISTORY
    # -----------------------------------------------------

    'item_has_history',

    'item_avg_price_hist_log1p',
    'item_price_min_hist_log1p',
    'item_price_max_hist_log1p',

    'item_price_volatility_hist_log1p',

    'item_hist_observation_count_log1p',

    # -----------------------------------------------------
    # ITEM LAGS
    # -----------------------------------------------------

    'item_price_last_scrape_log1p',
    'item_price_lag_2_log1p',

    'item_has_price_history',
    'item_has_lag_2_history',

    # -----------------------------------------------------
    # ITEM PRICE CHANGE
    # -----------------------------------------------------

    'item_prev_price_change_signed_log1p',
    'item_prev_price_change_pct_signed_log1p',

    'item_prev_price_change_abs',

    'item_price_direction',

    # -----------------------------------------------------
    # ITEM TREND
    # -----------------------------------------------------

    'item_days_since_last_scrape',

    'item_days_since_first_seen_log1p',

    'item_price_trend_per_day_signed_log1p',

    'item_price_trend_abs',
    'item_price_trend_direction',

    # -----------------------------------------------------
    # ITEM POSITION
    # -----------------------------------------------------

    'item_price_position_hist',

    'item_price_above_hist_max',
    'item_price_below_hist_min',

    # -----------------------------------------------------
    # MODEL HISTORY
    # -----------------------------------------------------

    'model_has_history',

    'model_avg_price_hist_log1p',
    'model_price_min_hist_log1p',
    'model_price_max_hist_log1p',

    'model_price_volatility_hist_log1p',

    'model_hist_observation_count_log1p',

    # -----------------------------------------------------
    # MODEL LAGS
    # -----------------------------------------------------

    'model_price_last_scrape_log1p',
    'model_price_lag_2_log1p',

    'model_has_price_history',
    'model_has_lag_2_history',

    # -----------------------------------------------------
    # MODEL PRICE CHANGE
    # -----------------------------------------------------

    'model_prev_price_change_signed_log1p',
    'model_prev_price_change_pct_signed_log1p',

    'model_prev_price_change_abs',

    'model_price_direction',

    # -----------------------------------------------------
    # MODEL TREND
    # -----------------------------------------------------

    'model_days_since_last_scrape',

    'model_price_trend_per_day_signed_log1p',

    'model_price_trend_abs',
    'model_price_trend_direction',

    # -----------------------------------------------------
    # MODEL POSITION
    # -----------------------------------------------------

    'model_price_position_hist',

    'model_price_above_hist_max',
    'model_price_below_hist_min',

    # -----------------------------------------------------
    # AVAILABILITY FLAGS
    # -----------------------------------------------------

    'stock_available',

    'item_avg_price_hist_available',
    'item_price_min_hist_available',
    'item_price_max_hist_available',
    'item_price_volatility_hist_available',

    'model_avg_price_hist_available',
    'model_price_min_hist_available',
    'model_price_max_hist_available',
    'model_price_volatility_hist_available',

    'item_prev_price_change_available',
    'item_prev_price_change_pct_available',

    'model_prev_price_change_available',
    'model_prev_price_change_pct_available',

    'model_price_7d_avg_hist_available',

    'model_price_position_hist_available',
    'item_price_position_hist_available',

    'discount_depth_available',
    'show_discount_available',

    'price_before_discount_available',

    'price_vs_item_hist_avg_pct_available',

    'price_vs_item_hist_avg_pct'
]

# =========================================================
# CATEGORICAL FEATURES
# =========================================================

CAT_FEATURES = [

    'shopId',
    'itemId',
    'modelId'
]

# =========================================================
# TARGET
# =========================================================

TARGET = 'price_log1p'

# =========================================================
# PREPARE X / Y
# =========================================================

X_train = train_df[FEATURES]
y_train = train_df[TARGET]

X_test = test_df[FEATURES]
y_test = test_df[TARGET]

# =========================================================
# CONVERT CATEGORICAL COLS TO STRING
# =========================================================
#
# CatBoost handles string categories very well
# =========================================================

for col in CAT_FEATURES:

    X_train[col] = X_train[col].astype(str)
    X_test[col] = X_test[col].astype(str)

# =========================================================
# CATBOOST MODEL
# =========================================================

model = CatBoostRegressor(

    iterations=1000,

    learning_rate=0.03,

    depth=8,

    loss_function='RMSE',

    eval_metric='RMSE',

    random_seed=42,

    verbose=100
)

# =========================================================
# TRAIN
# =========================================================

model.fit(

    X_train,
    y_train,

    cat_features=CAT_FEATURES
)

# =========================================================
# PREDICT
# =========================================================

pred_log = model.predict(X_test)

pred_price = np.expm1(pred_log)

actual_price = np.expm1(y_test)

# =========================================================
# EVALUATION
# =========================================================

rmse = np.sqrt(
    mean_squared_error(
        actual_price,
        pred_price
    )
)

mae = mean_absolute_error(
    actual_price,
    pred_price
)

mape = (
    np.abs(
        (actual_price - pred_price)
        /
        actual_price.clip(lower=1)
    ).mean()
) * 100

# =========================================================
# RESULTS
# =========================================================

print("=" * 60)

print("CATBOOST ENTITY-CONDITIONED MODEL")

print("=" * 60)

print(f"FEATURE COUNT: {len(FEATURES)}")

print("=" * 60)

print(f"RMSE : {rmse:,.2f}")
print(f"MAE  : {mae:,.2f}")
print(f"MAPE : {mape:.2f}%")

print("=" * 60)

# =========================================================
# FEATURE IMPORTANCE
# =========================================================

feature_importance = pd.DataFrame({

    'feature': FEATURES,

    'importance': model.get_feature_importance()
})

feature_importance = feature_importance.sort_values(
    by='importance',
    ascending=False
)

display(
    feature_importance.head(20)
)

# =========================================================
# PREDICTION SAMPLE
# =========================================================

pred_df = test_df.copy()

pred_df['pred_price'] = pred_price
pred_df['actual_price'] = actual_price

pred_df['abs_error'] = (
    pred_df['actual_price']
    -
    pred_df['pred_price']
).abs()

pred_df['pct_abs_error'] = (
    pred_df['abs_error']
    /
    pred_df['actual_price']
).abs()

display_cols = [

    'shopId',
    'itemId',
    'modelId',

    'actual_price',
    'pred_price',

    'abs_error',
    'pct_abs_error'
]

display(
    pred_df[
        display_cols
    ]
    .sort_values(
        by='abs_error',
        ascending=False
    )
    .head(10)
)

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3578438038.py:298: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype(str)
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3578438038.py:299: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = X_test[col].astype(str)
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3578438038.py:298: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype(str)
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3578438038.py:299: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = X_test[col].astype(str)
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3578438038.py:298: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col] = X_train[col].astype(str)
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3578438038.py:299: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col] = X_test[col].astype(str)

0:	learn: 1.2354742	total: 474ms	remaining: 7m 54s
100:	learn: 0.1121312	total: 50.7s	remaining: 7m 31s
200:	learn: 0.0628004	total: 2m 36s	remaining: 10m 20s
300:	learn: 0.0519379	total: 4m 21s	remaining: 10m 7s
400:	learn: 0.0452399	total: 6m 14s	remaining: 9m 19s
500:	learn: 0.0407798	total: 7m 18s	remaining: 7m 17s
600:	learn: 0.0378256	total: 7m 50s	remaining: 5m 12s
700:	learn: 0.0345210	total: 8m 17s	remaining: 3m 32s
800:	learn: 0.0316461	total: 8m 45s	remaining: 2m 10s
900:	learn: 0.0293109	total: 9m 13s	remaining: 1m
999:	learn: 0.0275198	total: 9m 57s	remaining: 0us
============================================================
CATBOOST ENTITY-CONDITIONED MODEL
============================================================
FEATURE COUNT: 98
============================================================
RMSE : 2,835,104.63
MAE  : 502,094.57
MAPE : 0.64%
============================================================

                                 feature  importance
40          item_price_last_scrape_log1p   38.609495
41                item_price_lag_2_log1p   10.711625
59            model_price_max_hist_log1p    7.784619
62         model_price_last_scrape_log1p    6.690715
57            model_avg_price_hist_log1p    5.325866
35             item_avg_price_hist_log1p    4.472132
37             item_price_max_hist_log1p    3.230000
63               model_price_lag_2_log1p    3.200509
58            model_price_min_hist_log1p    3.052513
0                                 shopId    2.586797
36             item_price_min_hist_log1p    2.473491
42                item_has_price_history    1.799519
96  price_vs_item_hist_avg_pct_available    1.392023
34                      item_has_history    1.331387
39     item_hist_observation_count_log1p    1.124004
1                                 itemId    0.976108
87  item_prev_price_change_pct_available    0.890336
92    item_price_position_hist_available    0.623373
97            price_vs_item_hist_avg_pct    0.507309
78         item_avg_price_hist_available    0.505797

,shopId,itemId,modelId,actual_price,pred_price,abs_error,pct_abs_error
51050,10055250,21361590976,59208605361,9.490000e+08,9.763306e+08,2.733057e+07,0.028799
50801,10055250,19262129512,213179841270,1.990000e+08,2.029066e+08,3.906639e+06,0.019631
51874,10055250,29423577723,223709159272,7.590000e+08,7.567594e+08,2.240628e+06,0.002952
149775,1002919413,26820461772,257553911837,1.779000e+08,1.756800e+08,2.220021e+06,0.012479
228724,1006721226,27618664408,168561971999,1.999000e+08,2.012667e+08,1.366721e+06,0.006837
237647,1007168904,24823752002,217925190213,4.100000e+08,4.113491e+08,1.349146e+06,0.003291
61180,10058821,673005544,143786762152,8.450000e+07,8.337036e+07,1.129644e+06,0.013369
251591,1007177881,29759494159,236711175080,6.400000e+07,6.480406e+07,8.040582e+05,0.012563
64302,10058821,9788009241,85482961372,5.900000e+07,5.959882e+07,5.988208e+05,0.010150
98379,100525141,26053517837,237419113613,3.330000e+07,3.287771e+07,4.222862e+05,0.012681

In [82]:
remaining_df2 = remaining_df.copy()

# =========================================================
# KEEP ONLY ID COLUMNS
# SET ALL OTHER COLUMNS TO NaN
# =========================================================

keep_cols = [
    'capturedAt',
    'shopId',
    'itemId',
    'modelId',
    'tag1',
    'date',
    'tag2',
    'day_of_week',
    'is_weekend',
    'month',
    'day_of_year',
    'is_morning',
    'is_afternoon',
    'is_evening',

]

cols_to_blank = [
    col for col in remaining_df2.columns
    if col not in keep_cols
]

remaining_df2[cols_to_blank] = np.nan

In [83]:
remaining_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2803 entries, 301355 to 306223
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   capturedAt                2803 non-null   datetime64[ns]
 1   shopId                    2803 non-null   int64
 2   itemId                    2803 non-null   int64
 3   modelId                   2803 non-null   int64
 4   price                     0 non-null      float64
 5   priceBeforeDiscount       0 non-null      float64
 6   promotionId               0 non-null      float64
 7   cat_id                    0 non-null      float64
 8   stock                     0 non-null      float64
 9   normal_stock              0 non-null      float64
 10  raw_discount              0 non-null      float64
 11  show_discount             0 non-null      float64
 12  brand                     0 non-null      float64
 13  is_free_shipping          0 non-null      float64
 14  is_pre_order              0 non-null      float64
 15  item_price_min            0 non-null      float64
 16  item_price_max            0 non-null      float64
 17  review_rating             0 non-null      float64
 18  total_rating_count        0 non-null      float64
 19  cmt_count                 0 non-null      float64
 20  shop_rating               0 non-null      float64
 21  shop_response_rate        0 non-null      float64
 22  shop_follower_count       0 non-null      float64
 23  is_official_shop          0 non-null      float64
 24  is_verified               0 non-null      float64
 25  is_preferred_plus_seller  0 non-null      float64
 26  tag1                      2803 non-null   object
 27  date                      2803 non-null   object
 28  tag2                      2803 non-null   object
 29  day_of_week               2803 non-null   int32
 30  is_weekend                2803 non-null   int32
 31  month                     2803 non-null   int32
 32  day_of_year               2803 non-null   int32
 33  is_morning                2803 non-null   int32
 34  is_afternoon              2803 non-null   int32
 35  is_evening                2803 non-null   int32
dtypes: datetime64[ns](1), float64(22), int32(7), int64(3), object(3)
memory usage: 733.6+ KB

In [84]:
# =========================================================
# EXTEND remaining_df2 TO MATCH clean_df COLUMNS
# NEW COLUMNS WILL BE EMPTY (NaN)
# =========================================================

import numpy as np

# =========================================================
# TARGET COLUMN ORDER
# =========================================================

target_cols = clean_df.columns.tolist()

# =========================================================
# ADD MISSING COLUMNS AS NaN
# =========================================================

missing_cols = [
    col for col in target_cols
    if col not in remaining_df2.columns
]

for col in missing_cols:
    remaining_df2[col] = np.nan

# =========================================================
# REORDER COLUMNS TO MATCH clean_df
# =========================================================

remaining_df2 = remaining_df2[target_cols]

# =========================================================
# CHECK
# =========================================================

print("=" * 60)
print("COLUMN COUNT:", len(remaining_df2.columns))
print("=" * 60)

print(
    remaining_df2.columns.tolist()
)

============================================================
COLUMN COUNT: 151
============================================================
['capturedAt', 'shopId', 'itemId', 'modelId', 'price', 'priceBeforeDiscount', 'promotionId', 'cat_id', 'stock', 'normal_stock', 'raw_discount', 'show_discount', 'brand', 'is_free_shipping', 'is_pre_order', 'item_price_min', 'item_price_max', 'review_rating', 'total_rating_count', 'cmt_count', 'shop_rating', 'shop_response_rate', 'shop_follower_count', 'is_official_shop', 'is_verified', 'is_preferred_plus_seller', 'tag1', 'date', 'tag2', 'day_of_week', 'is_weekend', 'month', 'day_of_year', 'is_morning', 'is_afternoon', 'is_evening', 'stock_available', 'brand_missing', 'brand_freq', 'shop_response_rate_missing', 'model_price_last_scrape', 'model_price_lag_2', 'model_has_price_history', 'model_has_lag_2_history', 'model_days_since_last_scrape', 'model_has_time_history', 'item_avg_price_hist', 'item_avg_price_hist_available', 'item_price_min_hist', 'item_price_min_hist_available', 'item_price_max_hist', 'item_price_max_hist_available', 'item_price_volatility_hist', 'item_price_volatility_hist_available', 'item_hist_observation_count', 'item_has_history', 'model_prev_price_change', 'model_prev_price_change_available', 'model_prev_price_change_pct', 'model_prev_price_change_pct_available', 'model_prev_price_change_abs', 'model_price_direction', 'model_price_7d_avg_hist', 'model_price_7d_avg_hist_available', 'item_price_last_scrape', 'item_price_lag_2', 'item_has_price_history', 'item_has_lag_2_history', 'item_prev_price_change', 'item_prev_price_change_available', 'item_prev_price_change_pct', 'item_prev_price_change_pct_available', 'item_prev_price_change_abs', 'item_price_direction', 'model_avg_price_hist', 'model_avg_price_hist_available', 'model_price_min_hist', 'model_price_min_hist_available', 'model_price_max_hist', 'model_price_max_hist_available', 'model_price_volatility_hist', 'model_price_volatility_hist_available', 'model_hist_observation_count', 'model_has_history', 'model_price_position_hist', 'model_price_position_hist_available', 'model_price_above_hist_max', 'model_price_below_hist_min', 'item_price_position_hist', 'item_price_position_hist_available', 'item_price_above_hist_max', 'item_price_below_hist_min', 'model_price_trend_per_day', 'model_price_trend_per_day_available', 'model_price_trend_abs', 'model_price_trend_direction', 'item_days_since_last_scrape', 'item_has_time_history', 'item_days_since_first_seen', 'item_price_trend_per_day', 'item_price_trend_per_day_available', 'item_price_trend_abs', 'item_price_trend_direction', 'price_before_discount_available', 'is_on_sale', 'discount_amount', 'discount_depth', 'discount_depth_available', 'show_discount_available', 'effective_discount_pct', 'price_vs_item_hist_avg_pct', 'price_vs_item_hist_avg_pct_available', 'is_sharp_discount', 'shop_follower_count_available', 'shop_popularity', 'total_rating_count_available', 'item_popularity', 'review_rating_available', 'review_score_normalized', 'discount_x_popularity', 'discount_x_review_score', 'item_avg_price_hist_log1p', 'item_price_min_hist_log1p', 'item_price_max_hist_log1p', 'item_price_volatility_hist_log1p', 'model_avg_price_hist_log1p', 'model_price_min_hist_log1p', 'model_price_max_hist_log1p', 'model_price_volatility_hist_log1p', 'item_price_last_scrape_log1p', 'item_price_lag_2_log1p', 'model_price_last_scrape_log1p', 'model_price_lag_2_log1p', 'discount_amount_log1p', 'priceBeforeDiscount_log1p', 'item_hist_observation_count_log1p', 'model_hist_observation_count_log1p', 'item_days_since_first_seen_log1p', 'model_prev_price_change_signed_log1p', 'item_prev_price_change_signed_log1p', 'model_prev_price_change_pct_signed_log1p', 'item_prev_price_change_pct_signed_log1p', 'model_price_trend_per_day_signed_log1p', 'item_price_trend_per_day_signed_log1p', 'price_log1p', 'log_price', 'lower_bound', 'upper_bound', 'count', 'item_log_iqr_outlier', 'item_iqr_distance']

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\4008566487.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  remaining_df2[col] = np.nan

In [142]:
clean_df.shape

(296807, 151)

In [143]:
train_df.shape

(296710, 151)

In [144]:
remaining_df2.shape

(2803, 151)

In [85]:
# =========================================================
# SORT clean_df
# =========================================================

clean_df_sorted = clean_df.sort_values(
    'capturedAt'
)

# =========================================================
# MODEL-LEVEL LATEST LOOKUP
# =========================================================

model_lookup = (

    clean_df_sorted

    .groupby(
        ['shopId', 'itemId', 'modelId'],
        as_index=False
    )

    .last()
)

# =========================================================
# ITEM-LEVEL FALLBACK LOOKUP
# =========================================================

item_lookup = (

    clean_df_sorted

    .groupby(
        ['shopId', 'itemId'],
        as_index=False
    )

    .last()
)

# =========================================================
# EXCLUDE TARGET / ID COLS
# =========================================================

exclude_cols = [

    'capturedAt',
    'shopId',
    'itemId',
    'modelId',

    'price',
    'price_log1p',
    'log_price'
]

fill_cols = [
    col for col in remaining_df2.columns
    if col not in exclude_cols
]

# =========================================================
# START COPY
# =========================================================

filled_df = remaining_df2.copy()

# =========================================================
# FILL FEATURES
# PRIORITY:
# 1. exact modelId
# 2. fallback itemId
# =========================================================

for col in fill_cols:

    # -----------------------------------------------------
    # TEMP COL NAMES
    # -----------------------------------------------------

    model_temp_col = f"__model_{col}"

    item_temp_col = f"__item_{col}"

    # -----------------------------------------------------
    # MODEL LOOKUP
    # -----------------------------------------------------

    model_col = model_lookup[
        [
            'shopId',
            'itemId',
            'modelId',
            col
        ]
    ].rename(
        columns={
            col: model_temp_col
        }
    )

    filled_df = filled_df.merge(

        model_col,

        on=['shopId', 'itemId', 'modelId'],

        how='left'
    )

    # -----------------------------------------------------
    # ITEM LOOKUP
    # -----------------------------------------------------

    item_col = item_lookup[
        [
            'shopId',
            'itemId',
            col
        ]
    ].rename(
        columns={
            col: item_temp_col
        }
    )

    filled_df = filled_df.merge(

        item_col,

        on=['shopId', 'itemId'],

        how='left'
    )

    # -----------------------------------------------------
    # FILL PRIORITY
    # current -> model -> item
    # -----------------------------------------------------

    filled_df[col] = (

        filled_df[col]

        .fillna(
            filled_df[model_temp_col]
        )

        .fillna(
            filled_df[item_temp_col]
        )
    )

    # -----------------------------------------------------
    # DROP TEMP COLS
    # -----------------------------------------------------

    filled_df = filled_df.drop(
        columns=[
            model_temp_col,
            item_temp_col
        ]
    )

# =========================================================
# CHECK
# =========================================================

print("=" * 60)
print("Remaining NaNs")
print("=" * 60)

print(
    filled_df
    .isna()
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\3348387990.py:149: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(

============================================================
Remaining NaNs
============================================================
price           2803
log_price       2803
price_log1p     2803
stock           2708
normal_stock    2708
dtype: int64

In [86]:
# # =========================================================
# # SORT clean_df
# # =========================================================

# clean_df_sorted = clean_df.sort_values(
#     'capturedAt'
# )

# # =========================================================
# # GET LATEST ROW PER
# # (shopId, itemId, modelId)
# # =========================================================

# latest_lookup = (

#     clean_df_sorted

#     .groupby(
#         ['shopId', 'itemId', 'modelId'],
#         as_index=False
#     )

#     .last()
# )

# # =========================================================
# # EXCLUDE TARGET / ID COLS
# # =========================================================

# exclude_cols = [

#     'capturedAt',
#     'shopId',
#     'itemId',
#     'modelId',

#     'price',
#     'price_log1p',
#     'log_price'
# ]

# fill_cols = [
#     col for col in remaining_df2.columns
#     if col not in exclude_cols
# ]

# # =========================================================
# # START COPY
# # =========================================================

# filled_df = remaining_df2.copy()

# # =========================================================
# # FILL FEATURES ONE-BY-ONE
# # =========================================================

# for col in fill_cols:

#     temp_hist_col = f"__temp_hist_{col}"

#     lookup_col = latest_lookup[
#         [
#             'shopId',
#             'itemId',
#             'modelId',
#             col
#         ]
#     ].rename(
#         columns={
#             col: temp_hist_col
#         }
#     )

#     filled_df = filled_df.merge(

#         lookup_col,

#         on=['shopId', 'itemId', 'modelId'],

#         how='left'
#     )

#     filled_df[col] = filled_df[col].fillna(
#         filled_df[temp_hist_col]
#     )

#     filled_df = filled_df.drop(
#         columns=[temp_hist_col]
#     )

# # =========================================================
# # CHECK
# # =========================================================

# print("=" * 60)
# print("Remaining NaNs")
# print("=" * 60)

# print(
#     filled_df
#     .isna()
#     .sum()
#     .sort_values(ascending=False)
#     .head(5)
# )

In [87]:
# =========================================================
# PREPARE FEATURES FOR INFERENCE
# =========================================================

X_infer = filled_df[FEATURES].copy()

# =========================================================
# PREDICT LOG PRICE
# =========================================================

pred_log = model.predict(X_infer)

# =========================================================
# CONVERT BACK TO ORIGINAL PRICE SCALE
# =========================================================

filled_df['predicted_price'] = np.expm1(
    pred_log
)

# =========================================================
# OPTIONAL ROUNDING
# =========================================================

filled_df['predicted_price'] = (
    filled_df['predicted_price']
    .round(0)
)

# =========================================================
# VIEW RESULTS
# =========================================================

display_cols = [

    'capturedAt',
    'shopId',
    'itemId',
    'modelId',

    'predicted_price'
]

display(
    filled_df[display_cols]
    .head(5)
)

# =========================================================
# SUMMARY
# =========================================================

print("=" * 60)

print(
    "Predicted rows:",
    len(filled_df)
)

print("=" * 60)

,capturedAt,shopId,itemId,modelId,predicted_price
0,2025-03-22 00:22:05.726,1009757562,28616508894,246950643806,26869983.0
1,2025-03-22 00:22:05.751,1009757562,27453603008,158705684479,15091283.0
2,2025-03-22 00:22:05.751,1009757562,27453603008,158705684478,15063358.0
3,2025-03-22 00:22:05.752,1009757562,27816883459,99039190766,19905520.0
4,2025-03-22 00:22:05.752,1009757562,27816883459,99039190765,19905520.0

============================================================
Predicted rows: 2803
============================================================

In [107]:
remaining_df.head(5)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,tag1,date,tag2,day_of_week,is_weekend,month,day_of_year,is_morning,is_afternoon,is_evening
301355,2025-03-22 00:22:05.726,1009757562,28616508894,246950643806,26800000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301356,2025-03-22 00:22:05.751,1009757562,27453603008,158705684479,15000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301357,2025-03-22 00:22:05.751,1009757562,27453603008,158705684478,15000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301358,2025-03-22 00:22:05.752,1009757562,27816883459,99039190766,19000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0
301359,2025-03-22 00:22:05.752,1009757562,27816883459,99039190765,19000000,0,0,100001,NaN,NaN,...,TRAIN,2025-03-22,VALIDATION,5,1,3,81,0,0,0

In [88]:
# =========================================================
# MERGE USING FULL UNIQUE KEY
# =========================================================

eval_df = filled_df.merge(

    remaining_df[
        [
            'capturedAt',
            'shopId',
            'itemId',
            'modelId',
            'price'
        ]
    ],

    on=[
        'capturedAt',
        'shopId',
        'itemId',
        'modelId'
    ],

    how='left',

    suffixes=('', '_actual')
)

# =========================================================
# CHECK DUPLICATION
# =========================================================

print("filled_df rows :", len(filled_df))
print("eval_df rows   :", len(eval_df))

# should be identical

# =========================================================
# ACTUAL VS PRED
# =========================================================

y_true = eval_df['price_actual']
y_pred = eval_df['predicted_price']

# =========================================================
# METRICS
# =========================================================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

import numpy as np

rmse = np.sqrt(
    mean_squared_error(y_true, y_pred)
)

mae = mean_absolute_error(
    y_true,
    y_pred
)

mape = (
    (
        np.abs(y_true - y_pred)
        /
        y_true.replace(0, np.nan)
    ).mean()
) * 100

# =========================================================
# PRINT
# =========================================================

print("=" * 60)

print(f"RMSE : {rmse:,.2f}")
print(f"MAE  : {mae:,.2f}")
print(f"MAPE : {mape:.2f}%")

print("=" * 60)

filled_df rows : 2803
eval_df rows   : 2803
============================================================
RMSE : 3,818,395.50
MAE  : 588,057.35
MAPE : 1.49%
============================================================

In [89]:
# =========================================================
# EXPORT eval_df TO CSV
# =========================================================

eval_df[['capturedAt','shopId','itemId','modelId','price_actual','predicted_price']].to_csv(
    'eval_catboost_df2.csv',
    index=False
)

print("Saved: eval_catboost_df2.csv")

Saved: eval_catboost_df2.csv

In [122]:
eval_df.shape

(2803, 153)

In [150]:
eval_df[eval_df['itemId'] == 23776838147][['itemId','modelId','price_actual','predicted_price','item_price_last_scrape']].head(20)

,itemId,modelId,price_actual,predicted_price,item_price_last_scrape
1198,23776838147,245295191746,29900000,29877148.0,29900000.0
1199,23776838147,204505904780,128000000,29880284.0,29900000.0
1200,23776838147,204505904784,39900000,39912844.0,39900000.0
1201,23776838147,204505904783,29900000,29870596.0,29900000.0
1202,23776838147,204505904782,29900000,29880284.0,29900000.0
1203,23776838147,204505904779,39900000,39919392.0,39900000.0
1204,23776838147,204505904781,29900000,29923228.0,29900000.0

In [128]:
clean_df[clean_df['itemId'] == 26966858330].head(5)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_prev_price_change_pct_signed_log1p,model_price_trend_per_day_signed_log1p,item_price_trend_per_day_signed_log1p,price_log1p,log_price,lower_bound,upper_bound,count,item_log_iqr_outlier,item_iqr_distance
206863,2025-02-02 14:59:56.322,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206864,2025-02-03 21:11:42.760,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206865,2025-02-05 03:08:00.096,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206866,2025-02-06 22:33:16.342,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0
206867,2025-02-08 01:25:29.386,1005099271,26966858330,195535146534,1400000,5000000,547575120805888,100017,NaN,NaN,...,0.0,0.0,0.0,14.151984,14.151984,13.884921,14.552577,891,0,0.0

In [90]:
# =========================================================
# ANCHOR FEATURES
# =========================================================

X_anchor = test_df[FEATURES].copy()

# =========================================================
# PREDICT ANCHOR
# =========================================================

anchor_pred_log = model.predict(X_anchor)

test_df['anchor_pred_price'] = np.expm1(
    anchor_pred_log
)

In [92]:
# =========================================================
# ANCHOR RATIO
# =========================================================

test_df['anchor_ratio'] = (

    test_df['price']

    /

    test_df['anchor_pred_price']
)

# =========================================================
# MODEL-LEVEL DRIFT
# =========================================================

model_drift = (

    test_df

    .groupby('modelId')['anchor_ratio']

    .median()

    .reset_index()

    .rename(columns={
        'anchor_ratio': 'model_drift_factor'
    })
)

# =========================================================
# ITEM-LEVEL DRIFT
# =========================================================

item_drift = (

    test_df

    .groupby('itemId')['anchor_ratio']

    .median()

    .reset_index()

    .rename(columns={
        'anchor_ratio': 'item_drift_factor'
    })
)

# =========================================================
# SHOP-LEVEL DRIFT
# =========================================================

shop_drift = (

    test_df

    .groupby('shopId')['anchor_ratio']

    .median()

    .reset_index()

    .rename(columns={
        'anchor_ratio': 'shop_drift_factor'
    })
)

# =========================================================
# GLOBAL DRIFT
# =========================================================

global_drift = (
    test_df['anchor_ratio']
    .median()
)

In [93]:
# =========================================================
# MERGE DRIFT FACTORS
# =========================================================

filled_df = filled_df.merge(

    model_drift,

    on='modelId',

    how='left'
)

filled_df = filled_df.merge(

    item_drift,

    on='itemId',

    how='left'
)

filled_df = filled_df.merge(

    shop_drift,

    on='shopId',

    how='left'
)

# =========================================================
# HIERARCHICAL FALLBACK
# model -> item -> shop -> global
# =========================================================

filled_df['final_drift_factor'] = (

    filled_df['model_drift_factor']

    .fillna(
        filled_df['item_drift_factor']
    )

    .fillna(
        filled_df['shop_drift_factor']
    )

    .fillna(
        global_drift
    )
)

# =========================================================
# APPLY DRIFT CORRECTION
# =========================================================

filled_df['predicted_price_adjusted'] = (

    filled_df['predicted_price']

    *

    filled_df['final_drift_factor']
)

# =========================================================
# OPTIONAL ROUNDING
# =========================================================

filled_df['predicted_price_adjusted'] = (

    filled_df['predicted_price_adjusted']

    .round(0)
)

In [94]:
# =========================================================
# MERGE ACTUAL PRICES
# =========================================================

eval_df_adjusted = filled_df.merge(

    remaining_df[
        [
            'capturedAt',
            'shopId',
            'itemId',
            'modelId',
            'price'
        ]
    ],

    on=[
        'capturedAt',
        'shopId',
        'itemId',
        'modelId'
    ],

    how='left',

    suffixes=('', '_actual')
)

# =========================================================
# TRUE VS PRED
# =========================================================

y_true = eval_df_adjusted['price_actual']

y_pred = eval_df_adjusted[
    'predicted_price_adjusted'
]

# =========================================================
# METRICS
# =========================================================

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

import numpy as np

rmse = np.sqrt(
    mean_squared_error(y_true, y_pred)
)

mae = mean_absolute_error(
    y_true,
    y_pred
)

mape = (
    np.abs(y_true - y_pred)
    /
    y_true.replace(0, np.nan)
).mean() * 100

# =========================================================
# PRINT RESULTS
# =========================================================

print("=" * 60)

print("ADJUSTED PREDICTION PERFORMANCE")

print("=" * 60)

print(f"RMSE : {rmse:,.2f}")
print(f"MAE  : {mae:,.2f}")
print(f"MAPE : {mape:.2f}%")

print("=" * 60)

============================================================
ADJUSTED PREDICTION PERFORMANCE
============================================================
RMSE : 4,066,977.24
MAE  : 615,944.42
MAPE : 1.51%
============================================================

In [95]:
# =========================================================
# MULTI-DAY INFERENCE PIPELINE
# ENTITY-LEVEL DRIFT CALIBRATION
# =========================================================

import numpy as np
import pandas as pd

# =========================================================
# COPY
# =========================================================

infer_df = test__real_df.copy()

# =========================================================
# ADD ANCHOR FLAG
# =========================================================

infer_df['is_anchor'] = (
    infer_df['price'].notna()
).astype(int)

# =========================================================
# ADD ANCHOR FLAG TO CLEAN_DF
# =========================================================

clean_df['is_anchor'] = 0

# =========================================================
# ADD MISSING COLS TO infer_df
# =========================================================

for col in clean_df.columns:

    if col not in infer_df.columns:

        infer_df[col] = np.nan

# =========================================================
# MATCH EXACT COLUMN ORDER
# =========================================================

infer_df = infer_df[
    clean_df.columns
]

# =========================================================
# CONCAT
# =========================================================

combined_df = pd.concat(

    [
        clean_df,
        infer_df
    ],

    ignore_index=True
)

# =========================================================
# MARK FUTURE ROWS
# =========================================================

combined_df['is_future'] = 0

combined_df.loc[
    combined_df.index[-len(infer_df):],
    'is_future'
] = 1

# =========================================================
# SORT AGAIN
# =========================================================

combined_df = combined_df.sort_values(
    'capturedAt'
)

# =========================================================
# EXCLUDE NON-FILLABLE
# =========================================================

exclude_cols = [

    'capturedAt',

    'price',
    'price_log1p',
    'log_price',

    'tag1',
    'tag2',

    'is_anchor',
    'is_future'
]

fill_cols = [

    col for col in combined_df.columns
    if col not in exclude_cols
]

# =========================================================
# FORWARD FILL
# PRIORITY:
# 1. EXACT (shopId,itemId,modelId)
# =========================================================

combined_df[fill_cols] = (

    combined_df

    .groupby(
        ['shopId', 'itemId', 'modelId']
    )[fill_cols]

    .ffill()
)

# =========================================================
# FALLBACK:
# itemId
# =========================================================

combined_df[fill_cols] = (

    combined_df

    .groupby(
        ['itemId']
    )[fill_cols]

    .ffill()
)

# =========================================================
# EXTRACT FUTURE
# =========================================================

filled_future_df = combined_df[
    combined_df['is_future'] == 1
].copy()

# =========================================================
# FIX BOOLEAN STRING COLUMNS
# =========================================================

bool_cols = [

    'is_official_shop',
    'is_verified',
    'is_preferred_plus_seller',

    'is_free_shipping',
    'is_pre_order'
]

for col in bool_cols:

    filled_future_df[col] = (

        filled_future_df[col]

        .replace({
            't': 1,
            'f': 0,
            True: 1,
            False: 0
        })

        .fillna(0)

        .astype(np.int8)
    )

# =========================================================
# PREDICT
# =========================================================

X_future = filled_future_df[
    FEATURES
]

pred_log = model.predict(
    X_future
)

filled_future_df['predicted_price'] = np.expm1(
    pred_log
)

# =========================================================
# ANCHOR DF
# =========================================================

anchor_df = filled_future_df[
    filled_future_df['is_anchor'] == 1
].copy()

anchor_df['shift_ratio'] = (

    anchor_df['price']

    /

    anchor_df['predicted_price']
)

# =========================================================
# MODEL-LEVEL DRIFT
# =========================================================

model_drift = (

    anchor_df

    .groupby(
        ['date', 'modelId']
    )['shift_ratio']

    .median()

    .reset_index()

    .rename(
        columns={
            'shift_ratio': 'model_drift_factor'
        }
    )
)

# =========================================================
# ITEM-LEVEL DRIFT
# =========================================================

item_drift = (

    anchor_df

    .groupby(
        ['date', 'itemId']
    )['shift_ratio']

    .median()

    .reset_index()

    .rename(
        columns={
            'shift_ratio': 'item_drift_factor'
        }
    )
)

# =========================================================
# SHOP-LEVEL DRIFT
# =========================================================

shop_drift = (

    anchor_df

    .groupby(
        ['date', 'shopId']
    )['shift_ratio']

    .median()

    .reset_index()

    .rename(
        columns={
            'shift_ratio': 'shop_drift_factor'
        }
    )
)

# =========================================================
# GLOBAL DAILY DRIFT
# =========================================================

global_drift = (

    anchor_df

    .groupby('date')['shift_ratio']

    .median()

    .reset_index()

    .rename(
        columns={
            'shift_ratio': 'global_drift_factor'
        }
    )
)

# =========================================================
# MERGE DRIFT FACTORS
# =========================================================

filled_future_df = filled_future_df.merge(

    model_drift,

    on=['date', 'modelId'],

    how='left'
)

filled_future_df = filled_future_df.merge(

    item_drift,

    on=['date', 'itemId'],

    how='left'
)

filled_future_df = filled_future_df.merge(

    shop_drift,

    on=['date', 'shopId'],

    how='left'
)

filled_future_df = filled_future_df.merge(

    global_drift,

    on='date',

    how='left'
)

# =========================================================
# HIERARCHICAL DRIFT FALLBACK
# model -> item -> shop -> global
# =========================================================

filled_future_df['final_drift_factor'] = (

    filled_future_df['model_drift_factor']

    .fillna(
        filled_future_df['item_drift_factor']
    )

    .fillna(
        filled_future_df['shop_drift_factor']
    )

    .fillna(
        filled_future_df['global_drift_factor']
    )

    .fillna(1.0)
)

# =========================================================
# APPLY DRIFT
# =========================================================

filled_future_df['predicted_price_adjusted'] = (

    filled_future_df['predicted_price']

    *

    filled_future_df['final_drift_factor']
)

# =========================================================
# OPTIONAL ROUNDING
# =========================================================

filled_future_df['predicted_price_adjusted'] = (

    filled_future_df['predicted_price_adjusted']

    .round(0)
)

# =========================================================
# KEEP TRUE ANCHOR PRICE
# =========================================================

filled_future_df.loc[
    filled_future_df['is_anchor'] == 1,
    'predicted_price_adjusted'
] = filled_future_df['price']

# =========================================================
# FINAL OUTPUT
# =========================================================

submission_df = filled_future_df[

    [
        'capturedAt',
        'shopId',
        'itemId',
        'modelId',

        'predicted_price_adjusted'
    ]

].copy()

submission_df = submission_df.rename(
    columns={
        'predicted_price_adjusted': 'predicted_price'
    }
)

# =========================================================
# CHECK
# =========================================================

print("=" * 60)
print("INFERENCE COMPLETE")
print("=" * 60)

print(f"Rows predicted: {len(submission_df):,}")

print("=" * 60)

display(
    submission_df.head()
)

C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['is_anchor'] = 0
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  infer_df[col] = np.nan
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:65: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_df['is_future'] = 0
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({
C:\Users\purna\AppData\Local\Temp\ipykernel_31420\2591345562.py:166: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({

============================================================
INFERENCE COMPLETE
============================================================
Rows predicted: 25,900
============================================================

,capturedAt,shopId,itemId,modelId,predicted_price
0,2025-03-22 04:27:05.325,1009757562,27904817781,241162534605,7467661.0
1,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,7474586.0
2,2025-03-22 04:27:05.325,1009757562,27904817781,139002028392,7474586.0
3,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,7438643.0
4,2025-03-22 04:27:05.325,1009757562,27904817781,241162534603,7438643.0

In [97]:
# =========================================================
# VIEW ENTITY-LEVEL MARKET SHIFTS
# =========================================================

# ---------------------------------------------------------
# GLOBAL DAILY SHIFT
# ---------------------------------------------------------

global_shift_view = global_drift.copy()

global_shift_view['pct_shift'] = (

    (global_shift_view['global_drift_factor'] - 1)

    * 100
)

# ---------------------------------------------------------
# MODEL DRIFT
# ---------------------------------------------------------

model_shift_view = model_drift.copy()

model_shift_view['pct_shift'] = (

    (model_shift_view['model_drift_factor'] - 1)

    * 100
)

# ---------------------------------------------------------
# ITEM DRIFT
# ---------------------------------------------------------

item_shift_view = item_drift.copy()

item_shift_view['pct_shift'] = (

    (item_shift_view['item_drift_factor'] - 1)

    * 100
)

# ---------------------------------------------------------
# SHOP DRIFT
# ---------------------------------------------------------

shop_shift_view = shop_drift.copy()

shop_shift_view['pct_shift'] = (

    (shop_shift_view['shop_drift_factor'] - 1)

    * 100
)

# =========================================================
# DISPLAY
# =========================================================

print("=" * 60)
print("GLOBAL DAILY SHIFT")
print("=" * 60)

display(
    global_shift_view.sort_values('date')
)

print("=" * 60)
print("MODEL-LEVEL SHIFT")
print("=" * 60)

display(
    model_shift_view.sort_values(
        ['date', 'modelId']
    ).head(20)
)

print("=" * 60)
print("ITEM-LEVEL SHIFT")
print("=" * 60)

display(
    item_shift_view.sort_values(
        ['date', 'itemId']
    ).head(20)
)

print("=" * 60)
print("SHOP-LEVEL SHIFT")
print("=" * 60)

display(
    shop_shift_view.sort_values(
        ['date', 'shopId']
    ).head(20)
)

============================================================
GLOBAL DAILY SHIFT
============================================================

         date  global_drift_factor  pct_shift
0  2025-03-22             1.001779   0.177863
1  2025-03-23             0.999636  -0.036412
2  2025-03-24             1.000631   0.063133

============================================================
MODEL-LEVEL SHIFT
============================================================

          date       modelId  model_drift_factor  pct_shift
0   2025-03-22   22840360764            0.992852  -0.714843
1   2025-03-22   42512247244            1.009110   0.910962
2   2025-03-22   79402056144            1.005356   0.535628
3   2025-03-22   88733781447            0.973364  -2.663550
4   2025-03-22   88763971694            0.999257  -0.074302
5   2025-03-22   89089179973            1.016024   1.602443
6   2025-03-22   98763881764            0.995057  -0.494306
7   2025-03-22   99387637906            1.011648   1.164848
8   2025-03-22  108119862274            1.014206   1.420568
9   2025-03-22  108119862277            1.006869   0.686903
10  2025-03-22  108979317001            1.008555   0.855469
11  2025-03-22  117890556423            0.993774  -0.622640
12  2025-03-22  118114439748            1.010163   1.016315
13  2025-03-22  128675862015            1.004504   0.450371
14  2025-03-22  137602040917            1.016612   1.661240
15  2025-03-22  137868816492            1.011319   1.131883
16  2025-03-22  137928899407            0.999501  -0.049864
17  2025-03-22  137928899408            0.999499  -0.050113
18  2025-03-22  138947869978            0.999501  -0.049864
19  2025-03-22  138947869980            0.999501  -0.049864

============================================================
ITEM-LEVEL SHIFT
============================================================

          date       itemId  item_drift_factor  pct_shift
0   2025-03-22    385460336           1.014411   1.441118
1   2025-03-22   1306662193           1.009110   0.910962
2   2025-03-22   4265785842           1.000675   0.067507
3   2025-03-22   6040744499           1.004105   0.410517
4   2025-03-22   9196952643           1.000359   0.035926
5   2025-03-22  13594426011           1.002980   0.297957
6   2025-03-22  14697728192           0.992506  -0.749351
7   2025-03-22  15147672778           1.003659   0.365948
8   2025-03-22  17792936040           0.997843  -0.215748
9   2025-03-22  18690320030           0.996740  -0.325972
10  2025-03-22  18691902635           1.008555   0.855469
11  2025-03-22  19470910586           0.993774  -0.622640
12  2025-03-22  19989926210           1.010163   1.016315
13  2025-03-22  20683326126           0.996665  -0.333466
14  2025-03-22  20989935093           1.004504   0.450371
15  2025-03-22  21192819679           1.000344   0.034360
16  2025-03-22  21491883776           1.002816   0.281602
17  2025-03-22  21648360818           0.999800  -0.019950
18  2025-03-22  21690245739           0.999548  -0.045181
19  2025-03-22  21691888175           1.014347   1.434652

============================================================
SHOP-LEVEL SHIFT
============================================================

          date      shopId  shop_drift_factor  pct_shift
0   2025-03-22     1003777           1.003659   0.365948
1   2025-03-22    10032825           1.004105   0.410517
2   2025-03-22    10033683           1.008826   0.882626
3   2025-03-22    10036638           1.011319   1.131883
4   2025-03-22    10047096           1.017186   1.718615
5   2025-03-22    10048076           1.000675   0.067507
6   2025-03-22    10050107           0.997796  -0.220398
7   2025-03-22    10055250           0.998294  -0.170590
8   2025-03-22    10060557           1.014411   1.441118
9   2025-03-22    10064462           0.993921  -0.607893
10  2025-03-22    10079859           1.010508   1.050831
11  2025-03-22   100291901           1.000359   0.035926
12  2025-03-22   100302219           0.998623  -0.137734
13  2025-03-22   100314387           1.001171   0.117068
14  2025-03-22   100336528           1.003429   0.342875
15  2025-03-22   100402479           1.016024   1.602443
16  2025-03-22   100423447           0.999800  -0.019950
17  2025-03-22   100595620           1.002980   0.297957
18  2025-03-22   100626474           0.997843  -0.215748
19  2025-03-22  1002675141           0.992585  -0.741503

In [98]:
# =========================================================
# ENTITY-LEVEL ANCHOR DIAGNOSTICS
# =========================================================

anchor_df['pct_error_before_adjustment'] = (

    (
        anchor_df['predicted_price']
        -
        anchor_df['price']
    ).abs()

    /

    anchor_df['price'].clip(lower=1)

) * 100

# =========================================================
# DAILY OVERALL DIAGNOSTICS
# =========================================================

daily_anchor_diag = (

    anchor_df

    .groupby('date')

    .agg(

        anchor_count=(
            'price',
            'count'
        ),

        global_median_shift=(
            'shift_ratio',
            'median'
        ),

        global_mean_shift=(
            'shift_ratio',
            'mean'
        ),

        mean_anchor_mape=(
            'pct_error_before_adjustment',
            'mean'
        ),

        unique_shop_count=(
            'shopId',
            'nunique'
        ),

        unique_item_count=(
            'itemId',
            'nunique'
        ),

        unique_model_count=(
            'modelId',
            'nunique'
        )
    )

    .reset_index()
)

# =========================================================
# MODEL-LEVEL DIAGNOSTICS
# =========================================================

model_anchor_diag = (

    anchor_df

    .groupby(
        ['date', 'modelId']
    )

    .agg(

        anchor_count=(
            'price',
            'count'
        ),

        model_shift=(
            'shift_ratio',
            'median'
        ),

        model_anchor_mape=(
            'pct_error_before_adjustment',
            'mean'
        )
    )

    .reset_index()
)

# =========================================================
# ITEM-LEVEL DIAGNOSTICS
# =========================================================

item_anchor_diag = (

    anchor_df

    .groupby(
        ['date', 'itemId']
    )

    .agg(

        anchor_count=(
            'price',
            'count'
        ),

        item_shift=(
            'shift_ratio',
            'median'
        ),

        item_anchor_mape=(
            'pct_error_before_adjustment',
            'mean'
        )
    )

    .reset_index()
)

# =========================================================
# SHOP-LEVEL DIAGNOSTICS
# =========================================================

shop_anchor_diag = (

    anchor_df

    .groupby(
        ['date', 'shopId']
    )

    .agg(

        anchor_count=(
            'price',
            'count'
        ),

        shop_shift=(
            'shift_ratio',
            'median'
        ),

        shop_anchor_mape=(
            'pct_error_before_adjustment',
            'mean'
        )
    )

    .reset_index()
)

# =========================================================
# DISPLAY
# =========================================================

print("=" * 60)
print("DAILY OVERALL DIAGNOSTICS")
print("=" * 60)

display(
    daily_anchor_diag
)

print("=" * 60)
print("MODEL-LEVEL DIAGNOSTICS")
print("=" * 60)

display(
    model_anchor_diag.head(20)
)

print("=" * 60)
print("ITEM-LEVEL DIAGNOSTICS")
print("=" * 60)

display(
    item_anchor_diag.head(20)
)

print("=" * 60)
print("SHOP-LEVEL DIAGNOSTICS")
print("=" * 60)

display(
    shop_anchor_diag.head(20)
)

============================================================
DAILY OVERALL DIAGNOSTICS
============================================================

,date,anchor_count,global_median_shift,global_mean_shift,mean_anchor_mape,unique_shop_count,unique_item_count,unique_model_count
0,2025-03-22,100,1.001779,1.012974,1.346954,37,73,98
1,2025-03-23,100,0.999636,1.025805,1.526825,41,72,94
2,2025-03-24,100,1.000631,1.010845,1.327176,34,75,98

============================================================
MODEL-LEVEL DIAGNOSTICS
============================================================

          date       modelId  anchor_count  model_shift  model_anchor_mape
0   2025-03-22   22840360764             1     0.992852           0.719989
1   2025-03-22   42512247244             1     1.009110           0.902738
2   2025-03-22   79402056144             1     1.005356           0.532774
3   2025-03-22   88733781447             1     0.973364           2.736437
4   2025-03-22   88763971694             1     0.999257           0.074357
5   2025-03-22   89089179973             1     1.016024           1.577170
6   2025-03-22   98763881764             1     0.995057           0.496761
7   2025-03-22   99387637906             1     1.011648           1.151436
8   2025-03-22  108119862274             1     1.014206           1.400670
9   2025-03-22  108119862277             1     1.006869           0.682217
10  2025-03-22  108979317001             1     1.008555           0.848213
11  2025-03-22  117890556423             1     0.993774           0.626541
12  2025-03-22  118114439748             1     1.010163           1.006090
13  2025-03-22  128675862015             1     1.004504           0.448351
14  2025-03-22  137602040917             1     1.016612           1.634094
15  2025-03-22  137868816492             1     1.011319           1.119215
16  2025-03-22  137928899407             1     0.999501           0.049889
17  2025-03-22  137928899408             1     0.999499           0.050138
18  2025-03-22  138947869978             1     0.999501           0.049889
19  2025-03-22  138947869980             1     0.999501           0.049889

============================================================
ITEM-LEVEL DIAGNOSTICS
============================================================

          date       itemId  anchor_count  item_shift  item_anchor_mape
0   2025-03-22    385460336             1    1.014411          1.420645
1   2025-03-22   1306662193             1    1.009110          0.902738
2   2025-03-22   4265785842             3    1.000675          0.295375
3   2025-03-22   6040744499             1    1.004105          0.408839
4   2025-03-22   9196952643             1    1.000359          0.035913
5   2025-03-22  13594426011             2    1.002980          0.297072
6   2025-03-22  14697728192             2    0.992506          1.943936
7   2025-03-22  15147672778             1    1.003659          0.364614
8   2025-03-22  17792936040             1    0.997843          0.216215
9   2025-03-22  18690320030             1    0.996740          0.327038
10  2025-03-22  18691902635             1    1.008555          0.848213
11  2025-03-22  19470910586             1    0.993774          0.626541
12  2025-03-22  19989926210             1    1.010163          1.006090
13  2025-03-22  20683326126             2    0.996665          0.334724
14  2025-03-22  20989935093             1    1.004504          0.448351
15  2025-03-22  21192819679             1    1.000344          0.034348
16  2025-03-22  21491883776             1    1.002816          0.280811
17  2025-03-22  21648360818             1    0.999800          0.019954
18  2025-03-22  21690245739             4    0.999548          0.105616
19  2025-03-22  21691888175             1    1.014347          1.414361

============================================================
SHOP-LEVEL DIAGNOSTICS
============================================================

          date      shopId  anchor_count  shop_shift  shop_anchor_mape
0   2025-03-22     1003777             1    1.003659          0.364614
1   2025-03-22    10032825             1    1.004105          0.408839
2   2025-03-22    10033683             2    1.008826          0.874896
3   2025-03-22    10036638             1    1.011319          1.119215
4   2025-03-22    10047096             1    1.017186          1.689577
5   2025-03-22    10048076             3    1.000675          0.295375
6   2025-03-22    10050107             1    0.997796          0.220885
7   2025-03-22    10055250             4    0.998294          2.669895
8   2025-03-22    10060557             1    1.014411          1.420645
9   2025-03-22    10064462             1    0.993921          0.611611
10  2025-03-22    10079859             1    1.010508          1.039903
11  2025-03-22   100291901             1    1.000359          0.035913
12  2025-03-22   100302219             1    0.998623          0.137924
13  2025-03-22   100314387             1    1.001171          0.116931
14  2025-03-22   100336528             1    1.003429          0.341703
15  2025-03-22   100402479             1    1.016024          1.577170
16  2025-03-22   100423447             1    0.999800          0.019954
17  2025-03-22   100595620             2    1.002980          0.297072
18  2025-03-22   100626474             1    0.997843          0.216215
19  2025-03-22  1002675141             1    0.992585          0.747042

In [99]:
# =========================================================
# SAVE CATBOOST MODEL
# =========================================================

model.save_model(
    "catboost_price_model.cbm"
)

print("Model saved: catboost_price_model.cbm")

Model saved: catboost_price_model.cbm

In [100]:
submission_df.to_csv(
    'submission_catboost.csv',
    index=False
)